- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/FilterManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/JavaFilterTable.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/10
> Backport Bug 576615 - fix to use filter defaults only when requested

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/ConstantsForSystemPropertiesCleanUpCore.java
Add trailing semicolon to the sample code
> Fix system property sample

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewEnumWizardPage.java
- add override for typeNameChanged() method in NewEnumWizardPage to
ensure that user does not specify type parameters for enum
> Bug 514816 - [type wizards] Better validation for Enums and Annotations

- README.md
> Repository README needs updates to point to github issues #83

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
> POM and product version changes for 4.25 release

- README.md
- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
> Merge Master to BETA_JAVA19 post 4.24 

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageTwo.java
Inline module info question #59. Fixes #59
> Inline module info question #59

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
> ArrayOutofBounds exception during refactor operation

- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
> Remove useless bundle requirements

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/JUnitContainerInitializer.java
- org.eclipse.jdt.junit5.runtime/META-INF/MANIFEST.MF
> Apiguardian

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaSourceHover.java
This fix adds support for hover on TextBlock and shows the exact value of the TextBlock String 
Hover on TextBlock area and the hover window appears and shows the String value this TextBlock resolves to. 
The default key binding for Source hover option is `Shift + hover` . Use `hover` or `Shift + hover` to see the new enhancement option provided.
> JavaSourceHover support for TextBlock. Fixes #164

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/ProblemsLabelDecorator.java
Don't schedule too often, don't schedule from sync block
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/187
> Reduce schedule times in decorator (#187)

- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/wizards/NewTestSuiteWizardPage.java
- switch back NewTestSuiteWizardPage to default the class name to
AllTests
- if AllTests already exists, ensure it is not selected in the
list of suite classes
- fixes #219
> Change NewTestSuiteWizard behavior for existing AllTests class

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CodeStyleConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/CodeStyleConfiguration.java
Needed by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/482
> Javadoc fixes as found by Java 17 javadoc tool.

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocSnippetStringEvaluator.java
use `AbstractTextElement` for snippets
> Use AbstractTextElement for snippets.

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/514
> Opening of 4 26 stream for development

- org.eclipse.jdt.ui/forceQualifierUpdate.txt
> Comparator errors in I20220902-1100

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/540
> Version bumps for 4.26 stream

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/HierarchicalASTVisitorTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocSnippetStringEvaluator.java
Merging code changes from master to Beta branch post 4.25  RC2
> Merge master post 4.25 RC2

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.jeview/pom.xml
Bump version number post Update ASTView and JEView Marketplace Entries for 4.25. Required for #256
> Bump version number post Update ASTView and JEView Marketplace Entries for 4.25

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java
> [19] Update ASTFlattener

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Beta java19 update plugin versions of the changed plugins
> Beta_java19 update plugin versions

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SealedClassFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- Use SealedClassFixCore to define the AST rewrite required for the quick fix
- Use helper methods for retrieving the sealed type and permitted type
- Instead of 'problem.getProblemArguments()[0]', use the type declaration's identifier to get the simple name
- Add createCorrectionProposalFromCURewriteOperation(..) helper method
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>
Moves addSealedAsDirectSuperTypeProposal(..) (from LocalCorrectionsSubProcessor of jdt.ui) to (to a new class, SealedClassFixCore of jdt.core.manipulation)
The code being refactored is tested in [QuickFixTest17](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest17.java), which I used to confirm there was no breakage.
You can also …
> Move addSealedAsDirectSuperTypeProposal into jdt.core.manipulation.

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/AddImportTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddImportsOperation.java
I don't think the removed check was necessary in the first place. The containerName (the class that the method is called on) shouldn't have to be equal the methods declaringClass, otherwise we can't go up the class hierarchy.
fixes #276
> Fix "Add import" for static references through subclasses

- org.eclipse.jdt.ui/dictionaries/en_GB.dictionary
- org.eclipse.jdt.ui/dictionaries/en_US.dictionary
The word "downloaded" should also be included in our spellchecker list.
> Adds downloaded to the spellchecker

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ModifierCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/ModifierChangeCorrectionProposal.java
- fixes #310
If fix for missing body is to add abstract modifier, then the abstract modifier should be added to the type declaration.
See issue.
> Add abstract to class declaration if abstract added to method

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit4TestFinder.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit5TestFinder.java
- fixes #302
Does some minor changes to JUnit4TestFinder and JUnit5TestFinder classes to make the finders perform better for very large projects with many anonymous classes.
Try running tests in a package that has many classes and many anonymous classes.
> Make some performance enhancements to test finders

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/712
> POM and product version changes for 4.27 release

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Version bump for new build. Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/729
> Comparator issues in I20221130-1800

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/ProblemsLabelDecorator.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/345
> Don't log decorator errors for closed projects

- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PluginsNotLoadedTest.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/activation/JavaActivationTest.java
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/748
And apply some minor code enhancements.
> Migrate to javax.servlet.jsp-api from Maven-Central

- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaProjectHelper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/AutomatedSuite.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/views/SmokeViewsTest.java
Added trivial smoke tests
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/387
> Smoke tests for JDT views not yet tested

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.jeview.feature/feature.xml
* Remove feature's update sites
* Make labels to explicitly mention Java to make it clear
> Improve AST and element views feature metadata

- Jenkinsfile
No need to look for such issues in Jenkins.
> There is no cobol source in jdt.ui

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916
> POM and product version changes for 4.28 release

- org.eclipse.jdt.ui/forceQualifierUpdate.txt
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/947
> Comparator errors in I20230307-0840

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/917
> Version bumps for 4.28 stream

- pom.xml
> [20] Add support to run gerrit builds for JDT UI on BETA_JAVA20 branch

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/464
> [20] Add AST level 20 to AST view

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest1d5.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- don't convert if boxing is involved but types of if/else are different
- fixes #446
See issue.
See issue.
> Add additional checking for convert if to conditional

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/ChainElement.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ChainCompletionTemplateBuilder.java
- Move static methods from ChainCompletionTemplateBuilder (jdt.ui) into ChainElement (jdt.core.manipulation)
> Move static methods into jdt.core.manipulation.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/nls/NLSUtil.java
- fixes #475
See issue.
See issue test.
> Fix StringFixCore.createNLSEdits method to support Text blocks

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/util/TypeNameMatchLabelProvider.java
- add logic to properly calculate the effective modifiers for classes and interfaces that are nested in interfaces
- fixes Bug 567663
Fixes the images displayed in the Open Type dialog for nested interfaces and classes of an interface so they match the ones
used in the Outline dialog (i.e. to infer various defaulted modifiers such as public and static).
See original Eclipse bug.
> Make Open Type dialog icons consistent with Outline View

- .github/workflows/checkMergeCommits.yml
@iloveeclipse I think we can just try it out here as you even has a test-case PR ...
> Create a workflow to check for merge commits in PR

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/487
> Remove beta and disclaimers from copyright notes and UI

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- pom.xml
> [20] Increase bundle versions for BETA_JAVA20 changes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
> [20] Provide implementation for new ASTVisitor methods concerning new AST node EnhancedForWithRecordPattern

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- pom.xml
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/897
> Merge BETA_JAVA20 into master

- org.eclipse.jdt.astview/plugin.properties
- org.eclipse.jdt.astview/plugin.xml
- org.eclipse.jdt.jeview/plugin.properties
- org.eclipse.jdt.jeview/plugin.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/510
> Externalize AST and Java Element view names

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/plugin.properties
- org.eclipse.jdt.astview/plugin.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.jeview.feature/feature.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.jeview/plugin.properties
- org.eclipse.jdt.jeview/plugin.xml
- org.eclipse.jdt.jeview/pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/521
> Backport issue 510 - Externalize AST and Java Element view names

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/CompletionProposalCollector.java
- fixes: https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/239
Fixes regression in debug tests caused by: #535
Run debug testsuite.
> Fix regression in debug tests caused by #535

- pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/550
> [21] Run Gerrit builds for JDT UI BETA_JAVA21 branch with latest Y-build

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/569
> [21] Add AST level 21 to AST view

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100
> POM and product version changes for 4.29 release

- org.eclipse.jdt.ui/forceQualifierUpdate.txt
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1131
> Comparator errors in I20230607-0720

- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test155_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test155_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test156_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test156_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- fixes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573643
See bug.
See new tests.
> Fix extract local to recognize super() and this() constructor calls

- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract18/A_test120_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract18/A_test120_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests1d8.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- modify ExtractTempRefactoring.createAndInsertTempDeclaration() to put statement in front of enhanced for statement
- add test to ExtractTempTests1d8
- fixes #546
See issue cited.
Run ExtractTempTests1d8
> Add support for extracting local from enhanced for statement

- org.eclipse.jdt.ui.junit.sampleproject/src/main/java/junit/framework/TestResult.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/StringBuilderCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/BestMatchHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/LibrariesWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ProjectsWorkbookPage.java
Avoiding type-casts makes code easier to read.
> Use typed for-each loop

- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
Adds default filtering for parameter name code minings to match default filters used in original plug-in.
See new test.
> Codeminingfilter

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/JavaFilterTable.java
To avoid calculation on right side.
> Use short-circuit logic

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallerMethodWrapper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_394725.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_394725.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyTestHelper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/CallHierarchyTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest10.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/search/NLSSearchTest.java
- org.eclipse.jdt.ui/plugin.properties
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/nls/search/NLSSearchQuery.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/nls/search/NLSSearchResultRequestor.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/ReorgMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaUIMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ActionMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/FoldingMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/NoStringCreationCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/VarCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/OpenCallHierarchyHyperlinkDetector.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavadocHover.java
> Merge master into BETA_JAVA21

- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.text.tests/test.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/ImporterTest.java
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1150
> An attempt to disable automated JVM discovery & install on startup

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/HistoryDropDownAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/DynamicSourcesWorkingSetUpdater.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/WorkingSetConfigurationDialog.java
see
https://stackoverflow.com/questions/8777257/equals-vs-arrays-equals-in-java
> Compare Array content instead of instance comparison

- org.eclipse.jdt.ui.junit.sampleproject/src/main/java/junit/framework/Assert.java
- org.eclipse.jdt.ui.junit.sampleproject/src/test/java/junit/samples/SimpleTest.java
- org.eclipse.jdt.ui.junit.sampleproject/src/test/java/junit/samples/VectorTest.java
> Resolve usage of constructors deprecated for removal

- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/FilterManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
> remove unnecessary semicolon

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UpdateProperty.java
- org.eclipse.jdt.junit.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/RemoteTestRunner.java
> Avoid String.toLowerCase() using equalsIgnoreCase

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/feature.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.ltk.core.refactoring.tests/META-INF/MANIFEST.MF
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/META-INF/MANIFEST.MF
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring/META-INF/MANIFEST.MF
- org.eclipse.ltk.ui.refactoring/pom.xml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184
> Added missing bundle version bumps

- org.eclipse.jdt.bcoview/forceQualifierUpdate.txt
- org.eclipse.jdt.jeview/forceQualifierUpdate.txt
- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.ltk.ui.refactoring.tests/forceQualifierUpdate.txt
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184
> Implement JEP 280: Indify String Concatenation

- org.eclipse.jdt.bcoview/META-INF/MANIFEST.MF
- org.eclipse.jdt.bcoview/forceQualifierUpdate.txt
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.jeview/forceQualifierUpdate.txt
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/META-INF/MANIFEST.MF
- org.eclipse.ltk.ui.refactoring.tests/forceQualifierUpdate.txt
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
> version increments for 4.29

- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.jeview.feature/feature.xml
- org.eclipse.jdt.jeview.feature/pom.xml
> version increments for features

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryWithResourcesRefactoringCore.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/util/SideEffectChecker.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameTypeWizardSimilarElementsPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/CategoryFilterActionGroup.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/GenerateConstructorUsingFieldsSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/GenerateToStringDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/OverrideMethodDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/StaticInnerClassCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/infoviews/AbstractInfoView.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarimport/RefactoringLocationControl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javadocexport/JavadocWizard.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javadocexport/RecentSettingsStore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/AlreadyExistsDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/AssignToVariableAssistProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/StatusBarUpdater.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/AddSourceFolderWizardPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/LibrariesWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/NewVariableEntryDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ProjectsWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/SourceContainerWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/AddGetterSetterAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/AddUnimplementedConstructorsAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
> Add missing "static" modifier for constants

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- fixes #660
- add additional logic to AdvancedQuickAssistProcessor
- add new test
Recognizes a return statement after an if with single return statement can be converted to ternary expression.
See new test.
> Add refactoring proposal from if-return to ternary

- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationTab.java
- fixes #686
Deactivates Run button of JUnit launch configuration if test does not exist.
See issue.
> Fix JUnit launch tab to disable run button if test doesn't exist

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fixes #727
Fixes possible NPE in QuickAssistProcessor.
See new test.
> Fix possible NPE in QuickAssistProcess.getDeprecatedProposal()

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.ltk.core.refactoring.tests/pom.xml
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.ui.refactoring.tests/pom.xml
- org.eclipse.ltk.ui.refactoring/pom.xml
- pom.xml
- tests-pom/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1289
> POM and product version changes for 4.30 release

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java
Update UI code
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1340
> [21][dom] APIs deprecation and cleanup - UI changes

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1319
> Version bumps for 4.30 stream

- .gitignore
Build artifacts should not be seen as dirty or new or untracked. They should be ignored
Run the build. Then run git status.
> Build artifacts should be ignored from git

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitDocumentProvider.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/61
> fix StatusLine progress

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringAvailabilityTesterCore.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/RefactoringAvailabilityTester.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/RefactoringExecutionStarter.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceIndirectionRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceParameterRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameCompilationUnitProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameEnumConstProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameFieldProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameJavaProjectProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameMethodProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameModuleProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameNonVirtualMethodProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenamePackageProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameSourceFolderProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameTypeParameterProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameTypeProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameVirtualMethodProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/reorg/JavaDeleteProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/HierarchyProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
This PR moves many functions from RefactoringAvailabilityTester to RefactoringAvailabilityTesterCore so that they may be used more widely. These functions have no dependency on UI and more properly belong made available in a core part of JDT. 
This will assist in migrating core logic for many core refactors into a plugin with no UI dependencies for use in either a headless environment or outside of eclipse, such as in jdt.ls.
> Availability tester issue

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
For https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1380
> Update bundle versions

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
- add logic to do unsigned parsing and to do Integer parsing when l/L suffix is missing
- add negation support
- add floating-point exponent sign support
- fixes #795
Fixes some additional scenarios with Java constant hover.
See issue.
> Do further improvements to Java constant hover

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
For https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1380
> Remove BETA and disclaimers

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.jeview.feature/feature.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- pom.xml
Fixes github build errors following BETA 21 branch merge.
> Remove reference to Y-builds in pom.xml

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- fixes #780
- add new test to CleanUpTest16
See issue.
See new test in CleanUpTest16 or issue.
> Remove import if not needed in Pattern instanceof cleanup

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
Adds test case that was omitted from while to for-each patch.
See new test.
> Add missing test case for while to for-each

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- modify VariableDeclarationFixCore to add a check for a field that is written in a constructor but is referred to prior to the write in a lambda
- fixes #769
Adds additional checks to final modifier cleanup to prevent error as noted in issue.
See new test in CleanUpTest1d8 or issue.
> Fix final modifier cleanup for lambdas in constructors

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.jeview.feature/feature.xml
Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730
> Remove unnecessary attributes from feature.xml files

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/881
> [quick fix] Provide quick fix for illegal fall-through to a pattern in switch statement

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessorUtil.java
- org.eclipse.jdt.ui/build.properties
- fixes #917
- fix API errors in JDT UI build
Fixes NPE.
See issue.
> Fix NPE in QuickAssistProcessorUtil

- .github/workflows/updateRelease.yml
> Add release workflow

- .github/workflows/updateRelease.yml
> Add release workflow - fix quotes

- org.eclipse.jdt.astview.feature/pom.xml
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.jeview.feature/pom.xml
- org.eclipse.jdt.jeview/pom.xml
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit4.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.examples.projects/pom.xml
- org.eclipse.jdt.ui.junit.sampleproject/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui/pom.xml
- pom.xml
- tests-pom/pom.xml
> Update for release 4.31

- org.eclipse.jdt.ui/forceQualifierUpdate.txt
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557
> Comparator errors in I20231127-0750

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
> Version Bump for 4.31

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/CodeFormatCleanUp.java
for example
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1624
> CodeFormatCleanUp: mention the resource that caused Exception

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/CopyTest.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/CopyToClipboardActionTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
> fix "The static method should be accessed directly" warnings

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/InlineMethodFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringFixCore.java
> fix "Redundant superinterface" warnings

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/views/SmokeViewsTest.java
Tests and fix added for https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/972
> Tests and fixes for Javadoc view

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/JavaElementLabels.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
Contributes to
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1531
> Javadoc format fixes

- Jenkinsfile
- org.eclipse.jdt.ui/pom.xml
https://github.com/eclipse-platform/.github/issues/144
> Jenkinsfile: fail when number of problems increased

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDoc2HTMLTextReader.java
JDT-LS is attempting to override javadoc html generation with custom tags. This maintains current behavior while providing some protected methods to do so.
> Expand exposure for JDT-LS to extend some elements of CoreJavaDoc2HTMLTextReader

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaElementPropertyTester.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/SelectionConverter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/DeferredMethodWrapper.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/FilteredTypesSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditorInputFactory.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaElementHyperlinkDetector.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaOutlinePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaSourceViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ShowInBreadcrumbAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/TogglePresentationAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/BestMatchHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavadocHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/HierarchyInformationControl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TraditionalHierarchyViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyLifeCycle.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyViewPart.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/DecoratingJavaLabelProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/SelectionListenerWithASTManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/SelectionProviderMediator.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/OverrideIndicatorLabelDecorator.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/OpenAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SelectionDispatchAction.java
Improves performance of Call-Hierarchy, Type-Hierarchy, Hover, ...
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1614
> Performance: cache JARs during UI Operations- jdt.core#1614

- org.eclipse.jdt.astview/forceQualifierUpdate.txt
- org.eclipse.jdt.junit.runtime/forceQualifierUpdate.txt
- org.eclipse.jdt.junit4.runtime/forceQualifierUpdate.txt
- org.eclipse.jdt.junit5.runtime/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1661 
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659
> Touch bundles affected by the changed compilation settings

- Jenkinsfile
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1026
> Unrelated errors reported during Jenkins build

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/FilteredTypesSelectionDialog.java
partially revert of fc6a25a6a1d46627eae34f4aeab98cafb71a5f70
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1051
> FilteredTypesSelectionDialog: fix save after open #1051

- pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1061
> [22] Run Gerrit builds for JDT UI BETA_JAVA22 branch with latest Y-build

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/JavadocTagsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/JavadocTagsSubProcessorCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/SerialVersionBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnInitializedFinalFieldBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CompilationUnitRewriteOperationsFixCore.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CompilationUnitRewriteOperationsFix.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/GetterSetterCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/JavadocTagsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/SerialVersionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnInitializedFinalFieldSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CorrectMainTypeNameProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/LinkedNamesAssistProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
> Sub processor pushdown1

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
> OwningAnnotationsConfigurationDialog_title missing

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fixes #1096
Fixes a ClassCastException caused by the convert field name quick assist.
See issue.
> Fix ClassCastException in convert field name quick assist

- org.eclipse.jdt.jeview/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1750
> Touch bundle affected by compiler implementation change

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1131
> SemanticHighlighting: fix BadLocationException #1131

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/OpenCallHierarchyAction.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1132
> OpenCallHierarchyAction.getEnclosingMethod silence NPE #1132

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/CompletionProposalComputerDescriptor.java
for example
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/230
> CompletionProposal: log error and keep going with other providers

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1050
> [22] Add AST level 22 to AST view

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CodeFormatingTabPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/CodeFormatterConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/CustomCodeFormatterBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/ModifyDialogTabPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/ProfileConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/ProfileManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
There is no plan to change the implementation
> Suppress deprecation: java.util.Observable

- Jenkinsfile
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1169
> qualityGate unstable

- org.eclipse.jdt.junit/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1781
> Touch bundles affected by compiler implementation change

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
* use concurrent datastructures, volatile fConflict
* do not spinloop burning cpu
> ChangedValueChecker: multithreading fixes

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1189
> NPE in SemanticHighlightingReconciler

- Jenkinsfile
- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- pom.xml
Version updates to jdt ui plugins in beta java 22 branch
> Version updates to jdt ui plugins in beta java 22 branch

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CleanUpContextCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CleanUpOptionsCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CleanUpRequirementsCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/ICleanUpFixCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/ui/cleanup/CleanUpContext.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/ui/cleanup/CleanUpOptions.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/ui/cleanup/ICleanUpFix.java
> Incremental delete of duplicate interfaces part5a

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2164
> [22] Remove Beta Disclaimers in Java 22 in JDT UI

- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview/META-INF/MANIFEST.MF
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.jeview.feature/feature.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/forceQualifierUpdate.txt
- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.text.tests/forceQualifierUpdate.txt
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.unittest.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/forceQualifierUpdate.txt
See: eclipse-platform/eclipse.platform.releng.aggregator#1923
> Updated bundles with comparator errors

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/HierarchicalASTVisitorTest.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
Fixes eclipse.jdt.ui build errors due to latest merge.
Build should work.
> Fix o.e.jdt.ui failures due to latest JVM branch merge

- .mvn/extensions.xml
- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.ui/.settings/.api_filters
Uses latest tycho-bulid and removes unused api filters.
Build still works.
> Releng updates

- org.eclipse.jdt.astview.feature/build.properties
- org.eclipse.jdt.astview/build.properties
- org.eclipse.jdt.bcoview/build.properties
- org.eclipse.jdt.jeview/build.properties
Add missing about.html to source bundles.
Remove stale and wrong build configs.
Next I-build have no failing BuildTests once this is merged.
> Fix tests in I-builds

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/AssignToVariableAssistProposalCore.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/NewVariableCorrectionProposalCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/AssignToVariableAssistProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewVariableCorrectionProposal.java
- "Create local variable/field" & "Assign to new local variable/field"
Based on a request from https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2371 .
> Add fAddFinal to insert 'final' modifier to some proposals.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SplitTryResourceFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
JDT UI fixes for fixing #1261
See issue or ignored test in AssistQuickFixTest1d8 which has new changes once jdt.core fix is in.
> Split try-with-resources indent fix

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
Initialization of some of the fields in JavaPlugin was not thread safe.
This change tries to add thread safe init without holding extra locks in critical paths to prevent possible deadlocks while loading 3rd party code.
This may result in possible double creation of some objects but should avoid errors on multiple threads initializing same JavaPlugin fields in parallel.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2276
> Make remaining JavaPlugin lazy init fields thread safe

- org.eclipse.jdt.core.manipulation/forceQualifierUpdate.txt
- org.eclipse.jdt.ui.tests/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1979
> Touching bundles after compiler change

- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/TestMethodsCache.java
> Fix javadoc in TestMethodCache and inner class

- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/.settings/.api_filters
- org.eclipse.jdt.ui.unittest.junit/pom.xml
Removes redundant parts of the build files and enables api tooling
Build still works
> Releng improvements for unittest view junit support

- org.eclipse.jdt.ui.unittest.junit/plugin.properties
Improves user visible labels.
Old:
New:
Verify new look is for you
> Improve Generic Test view label capitalization

- pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1343
> [23] Run Gerrit builds for JDT UI BETA_JAVA23 branch with latest Y-build

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1362
> [23] Remove String Template preview feature from JDT UI

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1352
> Remove unused API filter for RecordPattern

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OneIfRatherThanDuplicateBlocksThatFallThroughFixCore.java
> Update client code that references removed jdt.dom APIs

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1392
> Remove unused API filters

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
- modify the logic for <pre>{@code that handles the case where the code has } in it so that it only looks for }</pre> when the pre counter matches and also add a check to ensure that the IOOB exception cannot happen
- add new test to JavadocHoverTests with an invalid <pre> which forces a }</pre> to occur without a <pre>{@code
- fixes #1394
Fixes IOOB exception that occurs in Javadoc hover.
See new test.
> Fix IOOB exception in Javadoc hover

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1376
> [23] Add AST level 23 to AST view

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/HierarchicalASTVisitorTest.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/PasteAction.java
Requires https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2483
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2481
> Updated JDT UI to AST changes around AbstractUnnamedTypeDeclaration

- .mvn/extensions.xml
Synchronizes tycho version used in build to 4.0.8 
Build works
> Update tycho-build to 4.0.8

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AbstractAnnotateAssistTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/EditorUtility.java
explicitly request a ClassfileEditor
2nd attempt at https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/736
> AnnotateAssistTest1d8 test failed

- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview/META-INF/MANIFEST.MF
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/compare/TypedElement.java
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/views/HelpUtils.java
- org.eclipse.jdt.junit.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/RemoteTestRunner.java
- org.eclipse.jdt.ui.tests/chkpii/org/eclipse/jdt/ui/tests/chkpii/HTMLTidyTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/buildpath/BuildpathProblemQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d5.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d8.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/util/History.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackager/JarPackageReader.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackager/JarPackageWriter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/ModifyDialog.java
Avoids NON-NLS and possible UnsupportedEncodingException
> Replace "UTF8" with StandardCharsets.UTF_8

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UtilitiesTest.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1489
> UtilitiesTest.testGetPossibleTypeKindsForTypes - update JDK to 17

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaSourceViewer.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1443
> fix "Show Tooltip Description": Not ReadOnly  #1443

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
+ more tests along https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2831
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1472
> [23] JEP 467: Render markdown doc comments (#1587)

- Jenkinsfile
Add -Pbuild-individual-bundles to jenkins file
> Add -Pbuild-individual-bundles to jenkins file

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaElementHyperlinkDeclaredTypeDetector.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1613
> fix JavaElementHyperlinkDetector logs NotPresentException #1613

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/infra/RefactoringTestPlugin.java
> [test] fix "The constructor URL(URL, String) is deprecated"

- org.eclipse.jdt.ui.tests/test.xml
add jit-exclusion also to test.xml for production test runs
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1639
> [23] many errors, some failure in AutomatedTestSuite with latest from JDT/Core 

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java
no types below package-info.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1651
> JUnitLaunch: fix ArrayIndexOutOfBoundsException #1651

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreMarkdownAccessImpl.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/AbstractFastJavaPartitionScanner.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/ui/text/IJavaPartitions.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java23SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest23.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java23ProjectTestSetup.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/template/java/JavaFormatter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/IndentUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/CodeTemplateSourceViewerConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaPartitionerManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaAutoIndentStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/SmartSemicolonAutoEditStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaSourceHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocAutoIndentStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/JavaSourceViewerConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1647
> [23] Remove beta and disclaimers from copyright notes and UI

- pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1697
> [24] Run Gerrit builds for JDT UI BETA_JAVA24 branch with latest Y-build

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1764
> ClassCastException when ctrl+hover over a 'case' literal

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RenameUnusedVariableCleanUpCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedCodeCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/RenameUnusedVariableFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnusedCodeFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest22.java
> Enhance unused local to unname variable

- org.eclipse.jdt.ui.tests/leaks/org/eclipse/jdt/ui/leaktest/reftracker/ReferenceTracker.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1664
> JavaLeakTests: workaround for error in JDK #1664

- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail36/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- fixes #1773
Adds test to verify change made in JDT.Core.
See new test.
> Add new test for pulling up method in anonymous class that should fail

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyViewPart.java
see https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1830
> Configure initial maximum viewer limit for Type Hierarchy view.

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1696
> [24] Add AST level 24 to AST view

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RenameTypeTests.java
- org.eclipse.jdt.ui.tests/chkpii/org/eclipse/jdt/ui/tests/chkpii/ChkpiiTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/launcher/AdvancedJUnitLaunchConfigurationDelegateTest.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/internal compatibility/org/eclipse/jdt/internal/ui/dialogs/TypeInfoViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/FilteredTypesSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/breadcrumb/EditorBreadcrumb.java
Use new Platform.OS API to determine the running platform introduced in:
- https://github.com/eclipse-platform/eclipse.platform/pull/704
> Use new Platform.OS API to determine the running platform

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/WorkingSetModel.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1863
> WorkingSetModel.setWorkingSets: improve error msg #1863

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/generics/InferTypeArgumentsRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
As ECJ no longer supports lower levels.
> Projects are always at 1.8+ level

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/ImportReferencesCollector.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnnecessaryArrayCreationCleanUpCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/GenerateHashCodeEqualsOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertIterableLoopOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLoopFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/Java50FixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/JoinVariableFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnnecessaryArrayCreationFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ValueOfRatherThanInstantiationFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineConstantRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/ExtractInterfaceProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeRefactoringProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/AddAllCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/AutoboxingCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/BooleanLiteralCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/UnboxingCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ParameterGuesser.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/SuperInterfaceSelectionDialog.java
Java 1.8 is mandated by ECJ thus removed code is non-reachable anymore.
> Remove dead code

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaIndenter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewDefiningMethodProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaTypeCompletionProposalComputer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewPackageWizardPage.java
ECJ supports min 1.8 and JDT UI provides no way to set BREE lower than that thus all this code is non reachable.
> Remove pre 1.8 support

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiCatchCleanUpCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/VarargsWarningsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/JoinVariableFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UpdateProperty.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/RefactoringMessages.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/GenerateHashCodeEqualsDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/HashCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ObjectsEqualsCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/TryWithResourceCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SurroundWithTryMultiCatchAction.java
ECJ support 1.8 as lowest version and JDT UI converts projects to that as a min level thus this code is non reachable.
> Remove Java 7 checks

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java24SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/testResources/semanticHighlightingTest1/Java24.java
Contributes to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1763
> [24] update Java23SemanticHighlightingTest to 24 as it requires preview

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/NewMethodCorrectionProposalCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceIndirectionRefactoring.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
ECJ mandates 1.8 thus this code is not reachable.
> Remove some usages of JavaModelUtil.is1d8OrHigher from o.e.jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposalCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ChainCompletionProposalComputer.java
`Potential resource leak: 'executor' may not be closed at this location
`
> fix executor resource warning since 19

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
> Add new test to QuickFixTest1d8

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
Ensure that only AST levels supported by the compiler are used.
> Use only supported AST levels in ASTView

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/BestMatchHover.java
for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1163
> BestMatchHover: add code snippet to error msg

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameInformationPopup.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1897
> fix NPE in RenameInformationPopup with eclipse restart #1897

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/SaveParticipantTest.java
contents was not changed / contents was not formated / contents was wrong formated
And stress test with 2 runs
> SaveParticipantTest: enhance error message

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDependenciesPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDialog.java
Fixes broken commit c3f2219b2e480995adca0f3e28fa17da2e3894f8 . Fixed approach used here given in
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1958#issuecomment-2613058811
> Fix release option in module dialog/page

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingPresenter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
when document was changed when async execution happens. Happens sometimes during SaveParticipantTest
> SemanticHighlightingPresenter: prevent BadLocationException

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpStressTest.java
Fixes test failure.
Run CleanUpStressTest.
> Fix CleanUpStressTest failure

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/OrganizeImportsAction.java
When skipping an import except the last.
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1996
> fix IndexOutOfBoundsException in OrganizeImportsAction.doChooseImports

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OneIfRatherThanDuplicateBlocksThatFallThroughFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryCatchAnalyzer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/MergeConditionalBlocksCleanUp.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1994
> Handles the TypePattern DOM API modifications in the JDT.UI

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingsCore.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightings.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorColoringConfigurationBlock.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2009
> Add syntax coloring for records

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingsCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OneIfRatherThanDuplicateBlocksThatFallThroughFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryCatchAnalyzer.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/MergeConditionalBlocksCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightings.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorColoringConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/HierarchyInformationControl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/OrganizeImportsAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
sync witch 4.35 M3
needed for https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1994
> Merge master (4.35 M3) into BETA_JAVA24

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
Let them run both for the new folding and the old one. Some tests were skipped since the old folding doesn't fold as much as the new one.
Required by: #2020
> Parameterize FoldingTests

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
Add regression test for #1992
Requires: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2019
> Add regression test

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
> Merge master into BETA_JAVA24

- org.eclipse.jdt.ui.unittest.junit.feature/feature.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/.settings/.api_filters
- org.eclipse.jdt.ui.unittest.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.unittest.junit/pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2024
> Removes unused API filters

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest22.java
- modify PatternInstanceofToSwitchFixCore to recognize when using Java 22 and up and the name specified in the pattern instanceof is not used by the if's then statement in which case replace it with an unnamed pattern instanceof in the switch
- add new tests to CleanUpTest22
- fixes #2016
See issue.
> Add pattern name fixing for pattern instanceof to switch for Java 22

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreMarkdownAccessImpl.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
Markdown comment TextElement order corrected. 
This PR closes: #2068
> Markdown comment TextElement order correction

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
- add new test to QuickFixTest1d8
- fixes #2076
See issue.
> Fix NullAnnotationsRewriteOperations to handle AnnotatableType

- org.eclipse.jdt.ui.tests.refactoring/resources/ConvertAnonymousToNested/canConvert/A_test33_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test54/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateHashCodeEqualsTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ModifierCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest.java
See #2011
Run JDT UI test suite with new core fix: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3795
> Fix indenting of various UI tests after fixing core indenting

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2048
> Remove BETA_JAVA24 disclaimers

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2048
> Remove BETA and disclaimer from compiler preferences

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/AbstractFastJavaPartitionScanner.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java24SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/testResources/semanticHighlightingTest1/Java24.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/infoviews/JavadocView.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- pom.xml
> [24] Merge BETA_JAVA24 into master

- org.eclipse.jdt.astview.feature/feature.xml
- pom.xml
> Remove references to Y-builds repo

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/TypeArgumentMismatchSubProcessor.java
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3883 and especially
https://github.com/eclipse-jdt/eclipse.jdt.core/commit/af83290c268e95d01e3c8e6f571c4e909b9efbac
> Remove dead code for problems never reported for Java < 1.8

- README.md
Hey. maybe this link would be better, what do you think?
https://www.eclipse.org/legal/epl-2.0/
> docs: the old license link didn't work

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/BuildPathBasePage.java
> extract to local variable

- pom.xml
> Remove early-draft disclaimer

- org.eclipse.jdt.core.manipulation/forceQualifierUpdate.txt
- org.eclipse.jdt.ui.tests/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2995
> Touch bundles affected by compiler changes

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorHoverConfigurationBlock.java
> Code style update

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- for #2208
See title.
Run PDE cleanup job.
> Remove potential CCE in PatternMatchingForInstanceofFixCore

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail38/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- add new PullUpRefactoringProcessor.checkIfHidingMethod() method and call it from checkFinalConditions()
- add new test to PullUpTests
- fixes #1868
See issue.
> Fix pull up to check for hiding method

- Jenkinsfile
- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java25SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/testResources/semanticHighlightingTest1/Java25.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
Ensure plugins with changes in the branch have higher version than master (+ .50).
> Bump some versions

- org.eclipse.jdt.ui/icons/full/ovr16/run_co.svg
It's the green arrow that is added to the class icon if the class has a main method (in the _Outline_ view).
Looks better in Dark Theme.
**Before**
Selected
Not selected
**After**
Selected
Not selected
> Remove white frame from run_co.svg

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/performance/EditorTestHelper.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2338
> Update JDT UI EditorTestHelper to match AbstractReconciler changes

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/MethodsContentProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/JavaElementImageProvider.java
- fixes #2313
See issue.
See issue.
> Show record components in Type Hierarchy viewer like fields are

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d4.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/SerialVersionQuickFixTest.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2354
> 4 new test fails in jdt.ui since I20250718-0410 #2354

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/PackageExplorerContentProvider.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2363
> Call PackageExplorerContentProvider.postAsyncUpdate while synchronized

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaReconciler.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2365
> Improve management of JavaReconciler.fIsEditorActive

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/icons/full/obj16/release_option.svg
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPluginImages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/CPListElement.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ReleaseAttributeConfiguration.java
This allows the user to set the new 'release' option for source folders.
See
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3900
> Support configuration of the release for a a source folder

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
The extended folding mechanism needs to find the IJavaElement corresponding to folding region. This change replaces the use of codeSelect() with getElementAt() in order to fix a performance regression.
Fixes #2456
Backports https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2465 to R4_37_maintenance branch
> Backport of #2465 to 4.37

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2475
> [25] Remove (BETA) and early-draft disclaimer from compiler preferences #2475
