eclipse-jdt/eclipse.jdt.ui

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringSearchEngine2.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineConstantRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/TargetProvider.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/ConstructorReferenceFinder.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MemberVisibilityAdjustor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInnerToTopRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveStaticMembersProcessor.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestMethodSelectionDialog.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceFactoryRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameFieldProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameMethodProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameModuleProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenamePackageProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameTypeProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RippleMethodFinder2.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/reorg/CreateCopyOfCompilationUnitChange.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/sef/SelfEncapsulateFieldRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ChangeSignatureProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ChangeTypeRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/HierarchyProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeRefactoringProcessor.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/nls/search/NLSSearchQuery.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/JavaReferenceCodeMining.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/DefaultModulepathFixProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ModuleCorrectionsSubProcessor.java
SearchPattern.createPattern() can return null pattern if the input is
not valid. So don't pass null patterns down to the Search engine, it
doesn't like that.
> Bug 579635 - NPE in MatchLocator.findIndexMatches(MatchLocator.java:306)

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
- add null check to prevent NPE in TreeSet comparator
> Bug 99622 - [rename] Rename method misses ambiguously overridden method

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/TokenScanner.java
Unfortunately eclipse is unable to detect unused import if the import
references the class itself. The "organize imports" is able to find it
thought.
> remove unused import

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/NullAnnotationsQuickFixTest1d8.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/sef/SelfEncapsulateFieldRefactoring.java
- fix SelfEncapsulateFieldRefactoring create getter and setter methods
to copy over annotations from the base field
- add new test to NullAnnotationsQuickFixTest1d8
> Bug 562891 - Null annotations not honoured by create getter/setter

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/IndentUtil.java
- add check for multi-line string partition and don't indent line
in IndentUtil.indentLine() method if within that partition
- fixes #21
> Moving text blocks destroys the contents indentation

- org.eclipse.ltk.core.refactoring/META-INF/MANIFEST.MF
- org.eclipse.ltk.core.refactoring/pom.xml
- org.eclipse.ltk.core.refactoring/src/org/eclipse/ltk/internal/core/refactoring/UndoableOperation2ChangeAdapter.java
to prevent UI freeze during UNDO
needs
https://github.com/eclipse-platform/eclipse.platform.runtime/pull/30
> Bug 578871 - use ISchedulableOperation

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/IndentActionTest15.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/performance/EditorTestHelper.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_1/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_1/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_2/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_2/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_3/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_3/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_4/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue30_4/Modified.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/IndentAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaMultiLineStringAutoIndentStrategy.java
- fixes #30
- Text block indentation affects the final string and each line
is considered in relation to the minimum indentation used so
this relative indentation for lines that are more indented than
the minimum must be preserved across indentation strategies
- added a class to store Text block info across multiple lines
and pass this across calls in IndentAction when indenting lines
- changed IndentAction.getTextBlockIndentationString() to add any
additional indentation for the line if it has indentation past
the minimum for the text block
- added new IndentActionTest15
> Fix indentation of Text Block

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/FilterManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
assignment cleanup on JDT UI
To ensure that new JDT cleanups are stable and work as intended we
should apply them to the Eclipse code base. This change uses the changes
from Bug 572440 on the jdt ui plug-in
> [dogfooding] Apply new Combine declaration and init removing overriding

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
- Fixes #36
- fix OverriddenAssignmentCleanUp.OverriddenAssignmentOperation
to replace the ExpressionStatement with the new VarDeclaration
statement instead of replacing the assignment which is just
an expression
- disable removing of redundant semicolons in the CleanUpTest test
so it verifies no additional semicolons are added
> Remove overridden assignment can result in two semicolons

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewAnnotationWizardPage.java
- add override for typeNameChanged() method in NewAnnotationWizardPage
to ensure that user does not specify type parameters for annotation
> Bug 514816 - [type wizards] Better validation for Enums and Annotations

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ChainCompletionProposalComputer.java
- fixes #45
- add check in ChainCompletionProposalComputer.initializeRequiredContext
method
> NPE in ChainCompletionProposalComputer using CompletionProposalCollector

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
This fix explicitly calls the active JavaEditor refresh of semantic highlighting to highlight newly added content of the editor, Fixes #25.
> This fix explicitly calls the active JavaEditor refresh of semantic highlighting to highlight newly added content of the editor, Fixes #25.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_462038.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_462038.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- fix CallInliner.crossCheckArguments() so that it does not bother
marking a single assignment expression
> Bug 462038 - [inline] Inlining method changes (breaks) loop condition

- org.eclipse.jdt.ui.tests/examples/org/eclipse/jdt/ui/examples/MyClasspathContainerInitializer.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d8.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/ExternalNullAnnotationChangeProposals.java
Specifically, JDT/Core now supports locating annotation paths relative
to a classpath container. If any entry in a container resolves to a
workspace project, that project is indeed a candidate to write eea-files
to, and will now be used by the Annotated command.
> Improve the Annotate command to support more eea-path configurations

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
> Fixes #62. [19] Allow JDT to target Java 19 in compiler preferences

- org.eclipse.jdt.ui/.settings/.api_filters
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
Colouring 'when' keyword in guarded pattern. Fixes #65.
> Colouring 'when' keyword in guarded pattern

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
Fix the preview of the _Remove overridden assignment_ cleanup (in the _Unnecessary Code_ tab) when the option _Move declaration if necessary_ is not enabled.
See also https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/27
> Fix "Remove overridden assignment" cleanup preview

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/CleanUpAction.java
- fixes #34
- support IProject selection in CleanUpAction.isEnabled() and
CleanUpAction.getCompilationUnits()
> Cannot run JDT cleanups for multiple projects in project explorer

- .github/workflows/rebase.yml
Posting comment containing "/rebase" would trigger PR rebase on target
branch
Copied from
https://github.com/eclipse-platform/eclipse.platform.swt/pull/199
> Add possibility to do rebase via comments on github PR

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UseIteratorToForLoopFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #100
- use TightSourceRangeComputer for new cleanup and tie it to the
while loop being transformed
- add new test
> Fix source range computer for while -> enhanced for cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest14.java
- fixes #104
- recognize switches that have return statements or throw statements
from every case and convert switch statement to a return of a
switch expression
- add new tests to CleanUpTest14
> Enhance SwitchExpression cleanup to support return statements

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/109
public static void before() {
Map<String, Object> map = Map.of("Hello", new Object());
Iterator<Entry<String, Object>> iterator = map.entrySet().iterator();
while (iterator.hasNext()) {
Entry<String, Object> entry = iterator.next();
System.out.println(entry);
}
}
public static void after() {
Map<String, Object> map = Map.of("Hello", new Object());
for (Entry<String> entry : map.entrySet()) {
System.out.println(entry);
}
}
In this case the Entry<String> is wrong and should be Entry<String,Object>
The code now considers a more complex case Entry<String,Object>
Run the junit test case or a code sample as given above where loop if over a map.entrySet()
- The change is following the [coding …
> Fix while loop to enhanced for loop conversion issue with EntrySet github issue 109

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
Fixes part of issue 109
Don't convert a for loop to enhanced for loop that refers to a collection's get() method more than once in the loop body.
Try the Convert to enhanced for loop cleanup on:
public void before1() {
List<String> list1 = List.of(""); //$NON-NLS-1$
for (int i = 0; i < list1.size(); i++) {
String s1 = list1.get(i);
String s2 = list1.get(i);
System.out.println(s1 + "," + s2); //$NON-NLS-1$
}
}
> Forloopbug

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
public void foo() {
List<String> list1 = List.of(""); //$NON-NLS-1$
for (int i = 0; i < list1.size(); i++) {
String s1 = list1.get(i);
String s2 = list1.get(i);
System.out.println(s1 + "," + s2); //$NON-NLS-1$
}
List<String> stringList = List.of("Hello", "World"); //$NON-NLS-1$ //$NON-NLS-2$
for (int i = 0; i < stringList.size(); i++) {
System.out.println(stringList.get(i));
System.out.println(stringList.get(i));
}
}
should convert to enhanced for loops as follows:
public void foo() {
List<String> list1 = List.of(""); //$NON-NLS-1$
for (String s1 : list1) {
String s2 = s1;
System.out.println(s1 + "," + s2); //$NON-NLS-1$
}
List<String> stringList = List.of("Hello", "World"); //$NON-NLS-1$ //$NON-NLS-2$
for (String element : stringList) {
System.out.println(element); …
> Forloopbug2

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- Fix EntrySet issue 109 with complex iterator types
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/109
- use same logic from for-with-iterator to enhanced for cleanup
to properly set the type of the enhanced for loop variable
Fix the while loop to enhanced for loop cleanup to properly set the loop var type for all cases
Run CleanUpTest1d8 as new test has been added with generic array
> Fix type logic for while iterator to enhanced for cleanup

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/131
Launch Y build using Java 19 and create a java project. The old logic of ends with will not work for 19 and 9. Since 19 ends with 9. I have changed that logic
How to test
Launch Y build using Java 19 and create a java project
Author checklist
I have thoroughly tested my changes
> Default Execution Environment for Y build is 9 (fixes #131 )

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsSubProcessor.java
Fixes #137
Signed-off-by: Noopur Gupta <noopur_gupta@in.ibm.com>
Prevents adding @SuppressWarnings("preview") to PatternInstanceofExpression SVD
Follow steps in #137
> [19] Quickfix for "you are using preview feature" causes compilation error. 

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/LibrariesWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDependenciesAdapter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDependenciesPage.java
This is a follow-up from issue [eclipse.jdt.core#114](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/114), where a new buildpath error has been implemented.
In this current PR we try to signal the problem right while configuring a project:
* **Build Path**: When `--release` is set, the Module Dependencies tab will disable the "Expose Package" button for all system modules - providing an info message why this is not possible.
* **Compiler Options**: When `--add-exports` exists on a system module, let selection of `--release` raise an error, thus disabling "Apply".
I chose this slightly asymmetric design, because
* I didn't find a suitable why to explain the problem on the Compiler Options page short of raising an error when the illegal combination is selected.
* On the Module …
> Detect/avoid illegal combination of --release and --add-exports

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
Checks two things and prevents moving the initializer if true:
1. Whether a variable is reassigned in a statement that may have sub-
statements (like an if statement)
2. Whether the initializer uses variables that are not define at the
place the initializer would be move up to.
Fixes #136
* Have a looks at the new test cases introduced and play around with similar cases
* Apply cleanup to Eclipse source code.
> Prevent moving initializer in error cases.

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
This PR makes sure any line end comments are moved with the corresponding initializer when cleaning up an overriding assignment. The new code checks that both the initializer and the overriding assignment are alone on a line except for a trailing comment. Otherwise the clean-up is not applied. The cleanup then replaces the line end comment in the declaration with the one in the overriding assignment. 
This is a fix for #56
Experiment with overriding assignments inside blocks, in particular in the presence of the line end comments. For example, see the related issue.
> Move trailing comments with initializer. Fixes #56

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
Fixes #159
Adds AST levels 18 and 19 in AST view's menu
Open AST view and use the view menu to select the AST 18 and 19 levels
> [19] Add AST levels 18 and 19 in AST view

- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/RenameVirtualMethodInClass/test49/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/RenameVirtualMethodInClass/test49/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RenameVirtualMethodInClassTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RippleMethodFinder2.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
- fixes #158
- add check in RippleMethodFinder2.findAllRippleMethods() to bypass
an issue where search cannot find the original method in the
compilation unit
- fix logic in RenameLinkedMode.start() so that the name node isn't
added twice and the additional methods found by RippleMethodFinder2
are processed correctly
- add new test to RenameVirtualMethodInClassTests and enable some
tests that weren't being run
Run test49 in RenameVirtualMethodInClassTests.java or see original issue
> Fix rename regression with renaming overridden interface method

- org.eclipse.ltk.core.refactoring/src/org/eclipse/ltk/core/refactoring/CompositeChange.java
- fixes #169
Adds check to CompositeChange that change is already a CompositeChange before casting
Run test from specified issue.
> Fix ClassCastException in CompositeChange

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- Test cases assumed target proposal was the first element in list
returned by collectAssists(..)
- Use findProposalByName(..) to improve resilience of the test cases
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>
See : 
- https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/master/1/
- https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/view/change-requests/job/PR-168/2/
- https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/view/change-requests/job/PR-149/9/
- https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/view/change-requests/job/PR-124/4/
The same 4 tests have been broken for the past while. They fail locally when run in `mvn` but pass when run in Eclipse.
> Fix failures in AssistQuickFixTests1d8#testSurroundWithTryWithResource_*

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
Add a unit test case for issu e#120 with the reproducer presented there.
This test case also shows that the fix for #120, PR #123, falsely adds an additional import for the generic type `V`.
> Add unit-test case for #120 and fix generic-import bug of enhanced-for-loop cleanUp

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaProjectHelper.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/JavaMethodParameterCodeMining.java
- Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/148
- Use IMethodBinding#getParameterNames() to support parameter name code
mining for records
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>
This change requires https://github.com/eclipse-jdt/eclipse.jdt.core/pull/201 to use the new API for IMethodBinding.
> Add parameter name code mining support for records.

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpTabPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/UnnecessaryCodeTabPage.java
Prevent the initializer in a overriden assignment cleanup from being moved up when the initializer uses variable which are undefined at the location the initilizer is being moved to.
Fixes #38 
On the unnecessary code cleanup page, enable "Remove overridden assignement" and disable "Move declaration if necessary". Write some code that overrrides an initializer (see issue for example) and play with cases where the initializer uses identifiers that are undefined at the variable declaration site: think of local variables and fields of local classes.
- I have signed the [Eclipse Contributor Agreement …
> Don't move up initializer when using undefined vars. Fixes #38

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/BuildPathsBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDependenciesPage.java
improve Dark Theme on Windows eclipse-platform/.github#27
Using CTabFolder and CTabItem, instead of TabFolder/TabItem, improves the look when in Dark Theme; the background of the tab no longer has a non-dark background.
This relates to multiple commits to fix:
[Windows][Dark theme] Multiple preference pages use tab widgets, that are not dark theme aware eclipse-platform/.github#27
> eclipse.jdt.ui #27: Use CTabFolder to improve Dark Theme on Windows

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavadocHover.java
Fixes #85 by using the platform line separator
Since this only happens in the case where the platform browser widget is not available, you can use the testing procedure from https://github.com/eclipse-platform/eclipse.platform.text/pull/37 .
> Use platform line separator in hover. Fixes #85

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/SelectionConverter.java
- for all white-space selection, don't set a white-space offset
in SelectionConverter.getElementAtOffset() and don't cause IOBException
Fixes problem with selecting all white-space characters
Select area with only white-space characters and right-click
> Whitespaceissue

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/ModifyDialogTabPage.java
Change new cleanup tab page button functions to be public with noop default implementations to help the Xtend
project which is using the internal ModifyDialogTabPage.
Build the Xtend plug-ins.
> Make new cleanup tab page buttons default to noops to help Xtend

- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RefactoringScanner.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/reorg/MoveCuUpdateCreator.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ParameterObjectFactory.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/PasteAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/selectionactions/GoToNextPreviousMemberAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/TaskMarkerProposal.java
To avoid InvalidInputException if the source code contains elements not
covered by Java 1.3 JLS, specify proper source/target arguments while
creating scanner.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/203
> Use ToolFactory.createScanner() with source compliance set if possible

- org.eclipse.ltk.ui.refactoring/src/org/eclipse/ltk/internal/ui/refactoring/PreviewWizardPage.java
- org.eclipse.ltk.ui.refactoring/src/org/eclipse/ltk/internal/ui/refactoring/RefactoringUIMessages.java
- org.eclipse.ltk.ui.refactoring/src/org/eclipse/ltk/internal/ui/refactoring/RefactoringUIMessages.properties
With the addition of the number of files that are affected by a cleanup in the preview the zero hit case has been left out.
This patch checks for no hits and adds a third variant of text as title in the preview "No changes to perform".
Run a cleanup on a file where you have no hit. In the preview you see the new title that differs from the 1 hit and >1 hit case.
> Cleanup preview: Cover zero hit case

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaSourceHover.java
Fix NPE in getTextBlockHoverInfo
> Fix NPE in getTextBlockHoverInfo. Fixes #200

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
Don't assume the "CODEASSIST_FAVORITE_STATIC_MEMBERS" preference is
always set and check for NPE.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/209
> NPE in OrganizeImportsOperation.addStaticImports() (#209)

- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/wizards/SuiteClassesContentProvider.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/wizards/UpdateTestSuite.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/wizards/WizardMessages.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/wizards/WizardMessages.properties
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/wizards/NewTestSuiteWizardPage.java
- fixes #142
- modify NewTestSuiteWizardPage, SuiteClassesContentProvider, and UpdateTestSuite classes
Add JUnit 5 support to the NewTestSuiteWizard
Invoke the NewTestSuiteWizard via the New -> Other -> Java -> JUnit -> JUnit Test Suite
Select JUnit 5 Test Suite from the radio buttons
> Add JUnit5 support to New TestSuite Wizard

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AddUnimplementedMethodsOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnimplementedCodeFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTestSuite.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest16.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest17.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest1d8.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddUnimplementedMethodsOperation.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceFactoryRefactoring.java
Rework the search for unimplemented methods to be closer to JLS 17
8.4.8. etc. Also replaced feature flags with a method filter for clarity
and extensibility of the algorithm.
Fixes #161 and #182 
* creating types via wizards and checking "create unimplemented method" 
* Cleaning up "unimplemented methods"
* "Add unimplemented methods" quickfixes for weird cases
A lot of the cases should be covered by tests, though.
> Rework searching for unimplemented methods. Fix #161, #182

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression4.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression4.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests16.java
This patch fixes the NPE reported by #197 as well as support inlining of yield statement within a switch expression
Please use the steps reported in #197
> Support Inlining within switch expression. Fixes #197

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringScopeFactory.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameMethodProcessor.java
During a refactor rename, its possible that new occurrences of the
renamed methods are not correctly detected by
RenameMethodProcessor.batchFindNewOccurrences().
This is due to batchFindNewOccurrences() creating a scope based on the
set of new (renamed) methods, using
RefactoringScopeFactory.create(IMember[]). This create() method
essentially picks the project of the first of the specified IMember
objects, at least for trivial refactor renames. However that project
might not be sufficient to search for all new renamed method
occurrences, it might instead be a project that is a leaf dependency and
not a root dependency.
This change adjusts the used scope to be that of the project scopes of
all new methods provided to batchFindNewOccurrences(), instead of just
using the first method.
Fixes: …
> Refactor rename wrongly reports shadowings#201

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
Fixes isStatic() and isPrivate() methods in StubUtility2Core which have mixed up the flags to test.
Examine the source.  It is an obvious fix.
> Fix mixups in isStatic and isPrivate methods in StubUtility2Core

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #190
Prevents a while iterator loop to enhanced for loop cleanup to occur if an iterator is used by multiple while loops.  This is
necessary because the iterator declaration gets removed.
See #190.
> Don't allow while to forEach if iterator used in multiple while stmts

- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/forceQualifierUpdate.txt
Signature of com.ibm.icu.text.UTF16.isSurrogate(char) changed to
com.ibm.icu.text.UTF16.isSurrogate(int). The affected code need to be
touched to avoid comparator errors
Comparator differences from current build
/home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20220814-0600
compared to reference repo at
https://download.eclipse.org/eclipse/updates/4.25-I-builds
1.  eclipse.jdt.ui/org.eclipse.jdt.ui
no-classifier: different
org/eclipse/jdt/internal/ui/text/JavaWordFinder.class: different
The main artifact has been replaced with the baseline version.
The following attached artifacts have been replaced with the
baseline version: [sources]
2.  eclipse.jdt.ui/org.eclipse.jdt.junit …
> Update ICU4J to version 71.1

- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/wizards/NewTestCaseWizardPageOne.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaWordFinder.java
This should avoid issues with incompatible ICU4J change in 70, see
details in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/476
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/217
> Change com.ibm.icu.text.UTF16.isSurrogate() -> Character.isSurrogate()

- org.eclipse.ltk.core.refactoring/src/org/eclipse/ltk/core/refactoring/RefactoringStatusContext.java
As found by Java 17 javadoc tool.
Needed by
eclipse-platform/eclipse.platform.releng.aggregator#482
> Fix Javadoc warnings and errors.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/HierarchicalASTVisitorTest.java
Fixes `HierarchicalASTVisitorTest` failure because of new DOM AST Node added `AbstractTextElement`
Run `HierarchicalASTVisitorTest` locally. All tests should pass.
> Adding Hiererarchical visitor nodes for AbstractTextElement. Fixes #231

- org.eclipse.jdt.junit5.runtime/src/org/eclipse/jdt/internal/junit5/runner/JUnit5TestListener.java
Fixes #237 
Throw a __subclass__ of `ComparisonFailure` from a JUnit5 test and see that the compare dialog works for it.
> Bug #237: No comparison dialog for subclasses of ComparisonFailure in JUnit5

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PropertyAndPreferencePage.java
If element is PackageFragmentRoot then resource is Folder.
If resource is already IProject then getProject() returns this - as
before.
This solution was already suggested in bug 467761 and 579428.
To test: show Properties of "src" folder. Then Select "Java Compiler".
> fix ClassCastException in some PropertyDialogAction #78

- org.eclipse.jdt.junit5.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/InferTypeArguments/testCuWithLocalClass1/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InferTypeArguments/testCuWithLocalClass1/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InferTypeArguments/testCuWithLocalClass2/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InferTypeArguments/testCuWithLocalClass2/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InferTypeArgumentsTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/generics/InferTypeArgumentsRefactoring.java
- fixes #224
Fixes an issue where an import of a local class is added and ends up adding new in the import which is invalid.
See the issue or run the new tests added to InferTypeArgumentsTests.java
> Protect against import of local class when inferring type arguments

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit5TestFinder.java
- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/pom.xml
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/util/TestSearchEngine.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationTab.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchShortcut.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/TestTestSearchEngine.java
- org.eclipse.jdt.ui.unittest.junit.feature/feature.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui.unittest.junit/src/org/eclipse/jdt/ui/unittest/junit/launcher/JUnitLaunchConfigurationTab.java
- org.eclipse.jdt.ui.unittest.junit/src/org/eclipse/jdt/ui/unittest/junit/launcher/JUnitLaunchShortcut.java
instead of a list, which makes picking test cases easier.
It changes the dialog which is shown when "Run As/Debug As" -> "JUnit Test" action is executed in a file, which has multiple test 
classes. Previously, only a simple listing of the found types are shown, which is not the most optimal solution, if there are multiple nested classes, the original structure of the classes are lost. Specially, finding the root class is not trivial. 
Changing the dialog to show the tree structure of the classes, helps tremendously.
Create a **JUnit** test class with multiple inner classes, with **Nested** annotations and test methods in it. Try to start them...
> Use tree selection for picking the nested test classes

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Adopt the new constant `IProblem.IsClassPathCorrectWithReferencingType` from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/327 and treat it identically to `IProblem.IsClassPathCorrect`
> Adopt new IProblem.IsClassPathCorrectWithReferencingType from jdt.core

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
This fix adds the visit function for RecordPattern in  HierarchicalASTVisitor, so that HierarchicalASTVisitorTest does not fail.
Run HierarchicalASTVisitorTest as a `junit plugin test` and it should not fail.
> HierarchicalASTVisitorTest fails due to RecordPattern ast node visit not being present

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/pom.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.jeview/pom.xml
Tycho generates these properties automatically such that they don't become stale over time.
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/256
Ensure that there are not stale SCM URLs in the Tycho-built bundle.
Check the MANIFEST of the Tych-built bundle.  E.g., the bundle https://download.eclipse.org/eclipse/updates/4.25/R-4.25-202208311800/plugins/org.eclipse.jdt.ui_3.27.0.v20220824-0714.jar  has this property:
```
Eclipse-SourceReferences: scm:git:https://github.com/eclipse-jdt/eclipse
.jdt.ui.git;path="org.eclipse.jdt.ui";tag="I20220824-0600";commitId=054
cfef225a81a6958a61deb10484577d8de9ef0
```
I don't think these bundles are published to the build result so probably that's why no one notices.
> Remove Eclipse-SourceReferences properties

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpTabPage.java
- fixes #253
Has the new code to select all/deselect all on a cleanup tab page ignore radio button preferences which are meant to choose
one sub-option and only one sub-option.
Go to Source -> Clean Up ... -> Configure...
Go to the Code Style tab
Push Select All button
The radio buttons under Use blocks in if/while/for/do statements should not change
Press Deselect All button
The radio buttons above should not change
Press Select All again
This time change the radio button above
Press Reset Profile button
The radio button should return to its initial value
> Don't select all/deselect all for radio button cleanup options

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/JoinCleanUp.java
- make sure ASTNodes.createMoveTarget() gets used in a new node
- fixes #189
Fixes #189
See the issue.  When testing, use the Next button to see a preview of the cleanup.  A normal cleanup without preview works for the test.
> Fix No Target Edit Provided error in Use String.Join cleanup

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ASTHelper.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsSubProcessor.java
Remove beta and disclaimers from copyright notes
Fixes #407 for jdt.ui
Remove beta from code and disclaimers from copyright notes
See Compiler preferences. There shouldn't be any reference to BETA or early-draft. Also, no early-draft disclaimers in copyright notes in the code.
> Remove beta and disclaimers from copyright notes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/PackageJavadocTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeMismatchQuickFixTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/ChangeMethodSignatureProposal.java
- for quick fix when a method specifies a thrown exception that is not used, check if import of exception can be removed
- fixes #277
- add new function in ASTNodes to count type references in cu
- modify ChangeMethodSignatureProposal when removing an exception to check type reference count and remove if there is only 1
- modify existing tests in LocalCorrectionsQuickFixTest and add new one
Adds logic to remove unnecessary import when correcting an unused throws exception for a method.
See issue.
> When unused thrown exception is removed, check if import is needed

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackagerfat/FatJarPackageWizardPage.java
Additionally report warning for launch configs with the name of the unknown project and launch config.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/286
> Don't fail export wizard if a launch config contains undefined project

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
Add test that verifies that the bug reported in #276 doesn't happen for the "Convert to static import" quickfix.
Run the test.
> Test "Convert to static import" quickfix on references to subclass

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SealedClassFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- Use CompilationUnitRewriteOperationsFixCore to define the AST rewrite required for the quick fix
- Use helper methods for retrieving the sealed type, subtype, and compilation unit for the sealed type
- Instead of 'problem.getProblemArguments()[1]', use the Java element name of the sealed type
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>
Moves `addTypeAsPermittedSubTypeProposal(..)` (from `LocalCorrectionsSubProcessor` of jdt.ui) to (to a new class, `SealedClassFixCore` of jdt.core.manipulation)
The code being refactored is tested in [`QuickFixTest17`](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest17.java), which I used to confirm there was no breakage.
You can also simply create a new class …
> Move addTypeAsPermittedSubTypeProposal into jdt.core.manipulation.

- org.eclipse.jdt.ui/templates/default-postfixtemplates.xml
- use ${index} in templates everywhere the index is accessed
- fixes #299
Makes the for, fori, forr postfix loops use just one variable name for the indexing instead of mixing generated name and i.
Create a method that passes an array of String[] args
Type args.fori and do postfix completion.  The name used for the index should be the same as the variable used in the test of
the forloop.
> Fix postfix templates regarding for loops to be consistent with index

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/sef/SelfEncapsulateFieldRefactoring.java
- check affected CUs and their super types for pre-existing getter/setter of chosen name
- fixes Bug 209316
Fixes: [Bug 209316](https://bugs.eclipse.org/bugs/show_bug.cgi?id=209316) - [encapsulate field] should check for overriding methods
See bug report.
> Add additional checks for encapsulate field

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/JavaElementLinks.java
- add check for URL starting with "data:" which occurs when setText is called on Edge browser and use handler.handleTextSet()
- fixes: #248
Fixes issue caused by trying to interpret location change issued by MS Edge browser as a URL when setText is used in browser.
Use MS Edge browser in Eclipse using "-Dorg.eclipse.swt.browser.DefaultType=edge" and examine JDT tooltips as specified
in the original issue: #248
> Add check for Edge browser setText issuing a location change url

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest.java
Signed-off-by: Shi Chen <chenshi@microsoft.com>
Allow `OrganizeImportsOperation` to have a change to restore existing imports. Currently it directly call ` CodeStyleConfiguration.createImportRewrite(astRoot, false)` to create corresponding `ImportRewrite`. If we do not want to change the current import statements but only want to add all missing imports, there is no easy way to achieve this. 
There is a scenario in JDT.LS to support "Add all missing imports" quick fix without changing the current import statements, see the related enhancement issue https://github.com/redhat-developer/vscode-java/issues/2748. With this change the implementation can make use of `OrganizeImportsOperation` directly, see the draft PR https://github.com/eclipse/eclipse.jdt.ls/pull/2292.
With this change, we can …
> Allow OrganizeImportsOperation keeping existing imports

- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddImportsOperation.java
Following the [boy scout rule](https://www.informit.com/articles/article.aspx?p=1235624&seqNum=6) I removed the warnings from AddImportsOperation, which I changed in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/297.
> Remove use of deprecated SubProgressMonitor from AddImportsOperation

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/contentassist/JavaPrecomputedNamesAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ExternalAnnotationsAttachmentBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ExternalAnnotationsAttachmentDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ExternalAnnotationsAttributeConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/BuildPathDialogAccess.java
Fixes #315
Adds a 3rd option to the dialog by which "annotationpath" details are edited in the Java Build Path page. This option consists of two fields:
* Selection among the classpath containers used in the current Java project
* Name of a resolved element within the selected classpath container. Here "name" is loosely used as any prefix of the element names, which ends at some word "boundary" (a char other than letter or digit). This interpretation should support ignoring customary suffixes like version, classifier, file extension...
The 1st field is a drop down with available container names (which internally will be mapped to the actual container ID).
The 2nd field offers content assist and is also validated against the actual resolved elements of the container.
Open OK, the dialog …
> UI for configuring annotation path relative to a classpath container

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavadocContentAccess2.java
Fixes Javadoc hover when <pre>{@code ... }</pre> is used for a code sequence.
See issue.
> Javadocbug

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewMethodCorrectionProposal.java
Fixes the case where a new method is created and requires its own type parameters.
See: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/322
> Fix new method creation to add required type parameters

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClipboardOperationAction.java
---
The original bug was filed here:
https://github.com/eclipse-platform/eclipse.platform.text/issues/101
Very likely that is the wrong place, but at the time I didn't know where the fix will end up.
Let me know if you want me to file an equivalent bug here (or close than one and open it here)
Thank you,
Mihai
> Fix the Java editor not saving HTML to Clipboard (#89)

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInnerToTopRefactoring.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew10/test_Bug567020_Issue338_0/in/p1/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew10/test_Bug567020_Issue338_0/out/p1/Bar.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew10/test_Bug567020_Issue338_0/out/p1/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/AllRefactoringTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInnerToNewTests10.java
- fixes #338
- don't try to qualify a var type descriptor in MoveInnerToTopRefactoring class
- add new MoveInnerToNewTests10 test
Fixes Bug 567020 which has an inner class moved to its own file and causes invalid code.  This is also discussed
in the issue.
Try the scenario described in the issue or run the new test case.
> Fix move to top refactoring when var variable is used

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/MissingAnnotationAttributesFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/MissingAnnotationAttributesProposalOperation.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/MissingAnnotationAttributesProposal.java
Moves all the text editing logic of the "add missing attributes to annotation" QuickFix to org.eclipse.jdt.core.manipulation so that it can be reused in jdt.ls.
Test that `MissingAnnotationAttributesFixCore` can be accessed from another project without needing to require any ui packages.
Signed-off-by: David Thompson <davthomp@redhat.com>
> Move the logic of MissingAnnotationAttributes to o.e.j.core.manipulation

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewMethodCorrectionProposal.java
- refine type parameter logic to handle substitution of class type parameters when appropriate
- also handle adding type parameters when needed that may come from either the enclosing method or from a type
- add new tests to UnresolvedMethodsQuickFixTest1d8
- fixes #330
Fixes the new method creation quick fix for a missing method so it handles the case where type parameters are needed
in the new method.  It also handles the case where the type parameter names need to be changed to match existing
type parameters for the class that the new method is being created.
See issue #330
> More fixes for new method creation proposal

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryWithResourcesRefactoringCore.java
- org.eclipse.jdt.ui.tests.refactoring/resources/SurroundWithWorkSpace/SurroundWithTests/trycatch_in/TestIssue353.java
- org.eclipse.jdt.ui.tests.refactoring/resources/SurroundWithWorkSpace/SurroundWithTests/trycatch_out/TestIssue353.java
- org.eclipse.jdt.ui.tests.refactoring/resources/SurroundWithWorkSpace/SurroundWithTests/tryresources18_in/TestIssue353.java
- org.eclipse.jdt.ui.tests.refactoring/resources/SurroundWithWorkSpace/SurroundWithTests/tryresources18_out/TestIssue353.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithResourcesTests1d8.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java
- fixes #353
Fixes the code that generates a catch clause for surround with try/catch and try-with-resources so it doesn't
unnecessarily rename the exception local variable.
See test in issue.
> Fix scope calculation for surround with try/catch and resources

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaCodeScanner.java
- fixes #367
Fixes colorization of the comparison editor so that "sealed" and "record" keywords are colored properly.
Modify an existing source file and add a record and specify sealed keyword for the class.  Perform a Compare with -> and specify the file in local history before the change.  When you do this, you should see the sealed and record differences and the sealed/record keywords should be colored.
> Add sealed and record keywords for comparison editor

- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test126_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test126_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test127_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test127_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test128_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test128_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test129_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test129_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test130_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test130_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test131_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test131_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/util/Checker.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/util/UnsafeCheckTester.java
**This is a patch based on the solution explained in the bug report.**
The main changed file is `Checker.java`, the description of the modification of this file is as follows:
Compared with the solution proposed in the original issue, we apply a more generalized solution. First, we traverse the selected expression and create a mapping from expression to type for each `CastExpression`. Second, we validate the code snippet between the variable declaration and the first expression matching the selected expression. If we detect the `InstanceofExpression` and value corresponding to the key value, `leftOperand` of  `InstanceofExpression`, is equal to the `rightOperand` of  `InstanceofExpression` or its supertype, we would assert that such extracting is unsafe.
Considering this class not only …
> Improve the Safety of Extract Local Variable Refactorings concering ClassCasts #331

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/SpellCheckIterator.java
- use the old next value to avoid adding whitespace to end of Javadoc tag token
- fixes #365
Fixes problem with spell checker flagging Javadoc tags.
Create a class with method that has at least one parameter.  Create Javadoc for the method by adding /** and hitting enter.
The Javadoc should be added and the param tag should not be flagged as a spelling error, nor should the parameter name.
> Fix token for Javadoc tag in SpellCheckIterator

- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/FirstRunExecutionListener.java
- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/IListensToTestExecutions.java
- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/RerunExecutionListener.java
synchronized test failure notifications with multiple socket writes to prevent mixed-up output caused by calls from concurrent threads (resolves https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/378)
(hopefully) by running parallel tests, e.g. in console mode
> Support Junit5 parallel test execution through RemoteTestRunner (#378)

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchExpressionsFixCore.java
- modify code that generates yield statement to be prepared for throw being last statement
- fixes #380
Fixes a ClassCastException that occurs when there is more than one statement in a case that ends in a throw statement.
See issue test case.
> Fix ClassCastException in SwitchExpressionFixCore

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest14.java
- fixes #381
Stops the switch expression cleanup if any case has a return statement with no expression.
See test in issue.
> Don't do switch expression cleanup if there is an empty return statement

- org.eclipse.jdt.junit.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.runtime/pom.xml
As it can be seen at https://download.eclipse.org/eclipse/downloads/drops4/I20230114-1800/buildlogs/reporeports/reports/versionChecks.html only qualifier changed in this stream:
org.eclipse.jdt.junit.runtime | 3.7.0.v20220609-1843 | 3.7.0.v20230112-1828
-- | -- | --
org.eclipse.jdt.junit.runtime.source | 3.7.0.v20220609-1843 | 3.7.0.v20230112-1828
> Version bump for 4.27 stream

- Jenkinsfile
Makes Jenkins build complain if version hasn't been bumped for the current stream.
That would safe a lot of churn on releng side having to request JDT committers to bump versions after looking at I-build reports.
Current build should just work and when a version  bump is needed in some bundle the build will fail with message which bundle has to increase version
> Enable releng version comparison

- pom.xml
Builds AST and Element views as part of the Maven build so they can be later added to SDK feature. Tracked in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/387
Check the console log that the respective bundles and features are build
> Build AST and Element views as part of the Maven build

- Jenkinsfile
Ensures only one build is ongoing for branch or PR. Currently there are multiple concurrent builds in the current setup if new commits are pushed to branch/PR before the previous one finished. This patch configures Jenkins to stop the running one and start the new one.
> Do not run concurrent jenkins builds for same branch/pr

- org.eclipse.jdt.bcoview.feature/.project
- org.eclipse.jdt.bcoview.feature/.settings/org.eclipse.core.resources.prefs
- org.eclipse.jdt.bcoview.feature/.settings/org.eclipse.core.runtime.prefs
- org.eclipse.jdt.bcoview.feature/build.properties
- org.eclipse.jdt.bcoview.feature/feature.properties
- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview.feature/pom.xml
- pom.xml
Adds `org.eclipse.jdt.bcoview.feature` and integrates with maven build
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364
> Add Bytecode Outline feature

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/views/SmokeViewsTest.java
Original code was doing too much, we don't need that here since we run the test in same JVM.
System property "java.specification.version" has all we need
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/387
> Fixed smoke tests for JDT UI views failing to understand JDK version

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/browsing/MembersView.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/GenerateToStringDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaOutlinePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyViewPart.java
Fixes static usages to reduce warnings noise in the workspace
> Use static methods/fields from declaring classes.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/TryWithResourceFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/TryWithResourceCleanUp.java
Moves the "try-with-resource" clean up logic to org.eclipse.jdt.core.manipulation so that it can be used in jdt.ls as well.
Confirm that TryWithResourceFixCore can be accessed without needing to import any jdt.ui packages.
> Move tryWithResourceCleanUp into jdt.core.manipulation

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/JavaReferenceCodeMining.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorCodeMiningConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
- add a new preference to ignore inexact results for Code Mining references and have this used instead of the Search preference
- fixes #370
Adds a Code Mining preference to ignore inexact references which will be used instead of reading the similar preference
in the Search preferences which is not intuitive to the end-user.
Perform Code Mining and specify to show method references.  The new option will match the results of setting the Search preference regarding ignore potential matches.
> Add new preference to ignore inexact refs for Code Minings

- Jenkinsfile
@iloveeclipse if you don't mind, I would recommend to add these options permanently to the Jenkisn build to be able to better identify issues in the build.
> Add option to update snapshots and print a stacktrace on failure

- Jenkinsfile
Fix for https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/407
> Fix maven options to be in the right order in Jenkinsfile

- org.eclipse.jdt.astview/plugin.xml
- org.eclipse.jdt.jeview/plugin.properties
- org.eclipse.jdt.jeview/plugin.xml
- org.eclipse.jdt.jeview/src/org/eclipse/jdt/jeview/views/JavaElementView.java
* Never use the _type_ of a UI element in its name (view, wizard, dialog, ...).
* Also use a blank for "Java Element", even though that is related to the JavaElement class. People not knowing that class will assume a typo otherwise.
The new names will still work with Ctrl-3 and typing the old name, so committers don't have to re-learn muscle memory.
> Improve names of new views

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavadocContentAccess2.java
This adds support for inline return tags which were introduced in java 16.
Inline return tags along with being added with the normal tags like the normal return tag they also get inserted into the main text where the inline return tag is but prepended with "Returns " when using English.
The spec for the inline return tag is: https://docs.oracle.com/en/java/javase/19/docs/specs/javadoc/doc-comment-spec.html#return
Add a Javadoc to a method containing an inline return tag and either hover over the method or open the Javadoc view.
> Add support for inline return tags

- Jenkinsfile
pom.xml is the default file, so it is not needed
> remove superfluous maven argument

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CodeStyleFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- fixes #411
- fix ThisQualifierVisitor.hasConflict() to not flag field accesses when field declaration is equal
- add new test
Fixes the unnecessary this cleanup work for fields of generic classes.
See issue.
> Fix code style cleanup to remove this from generic class field

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CodeGeneration.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/CodeTemplateContextType.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/StubUtility.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.core.manipulation/pom.xml
* Adds code template that can be used to generate a method stub in the case of a super method invocation.
* Adds a parameter to`createImplementationStubCore()` to indicate whether the method to be generated is a super method invocation.
The use of the modified methods are tested in https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java, and the behavior is retained.
> Create new template permitting alternative method body statements.

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
- change UnresolvedElementsSubProcessor.addSimilarTypeProposals() to check if an interface is expected in which case make sure that each suggested class to import has the interface in its hierarchy
- fixes #349
Fixes the quickfix for an undefined type that is used to initialize or return an interface so that any suggested import class has the given interface in its hierarchy.
Create the following:
```
package tests;
public class BundleInfo {
public int getInt() {
return 43;
}
}
package tests2;
public interface ISomePath {
public String getPath();
}
package tests2;
public class BundleInfo implements ISomePath {
@Override
public String getPath() {
// TODO Auto-generated method stub
return null;
}
}
package tests3;
import tests2.ISomePath;
public class TestBundleInfo {
public ISomePath …
```
> Make quickfix that suggests importing a class smarter

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/IndentActionTest15.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_1/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_1/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_2/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_2/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_3/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_3/Modified.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_4/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_4/Modified.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/IndentAction.java
- make text block indentation the same whether the open quotes occur on a separate line or at the end of another line
- fixes #414
Fixes #414
See issue.
> Make Text Block indentation consistent

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/JUnitPropertyTester.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationTab.java
Allow JUnitLauncher to launch all tests in a Package including subpackages.
Fix : https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/420
Create a package "a" without test and add a "a.b" with test "C" and in Eclipse run test on "a".
Verify that "C" is run.
> Allow JUnitLauncher to launch all tests in a Package including subpackages

- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/reorg/ReorgPolicyFactory.java
- fixes #430
- fix PackagesReorgPolicy to not show binary IPackageRoots such as jar files as destinations
- also mark IPackageRoots as not having children as destinations
Fixes the reorg policy for packages so that binary source roots are not offered as destinations.  Also don't mark a
root as having children that can be destinations.
Select a package and right-click to bring up the Refactor->Move... menu.  No jars should be shown.
> Moving a package shows many JRT as possible target

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/426
> [20] Allow JDT to target Java 20 in compiler preferences

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #373
Adds more validity checking to While to for each cleanup so that if the iterator variable
is referenced outside of valid usage, the cleanup will not occur.
See issue.
> Add more validity checking to While to for each cleanup

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchExpressionsFixCore.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest14.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest14.java
- fixes #388
- fix code in SwitchExpressionsFixCore when forced to use old-style case format because of trailing comments to convert return statements into yield statements and not the return expression
- add new tests
Fixes convert to switch expression quick-assist/clean-up to not convert return statements to expressions when
forced to use old-style case statements due to a trailing comment.  See issue.
See issue.  Tests added.
> Fix convert to switch expression failing to add yield statements

- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/nls/NLSSourceModifierTest1d8.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/nls/NLSTestSuite.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/nls/AccessorClassCreator.java
- add check for Java 9 or above compliance before using the Class.getPackageName() method which was added in Java 9
- add new NLSSourceModifierTest1d8 test to NLSTestSuite
- fixes #466
Adds compliance checking before using getPackageName() which was added in Java 9.
See new test case.
> Add compliance checking to AccessClassCreator

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/StringCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- fixes #448
Refactors jdt.ui StringFix to StringFixCore in jdt.core.manipulation
Perform NLS cleanups/quick fixes as the functionality has not changed.
> Move StringFix to StringFixCore in jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/nls/NLSScanner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/nls/NLSUtil.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTestSuite.java
- fixes #450
- modify NLSScanner to support Text blocks
- modify NLSUtil to properly figure out endof Text block for tag insertion
- add new LocalCorrectionsQuickFixText15
- modify LocalCorrectionsQuickFixTest to add a test to add a non-NLS tag for a String
> Add support to add non-NLS marker for Text blocks

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/StringConcatToTextBlockCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstants.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstantsOptions.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/JavaFeatureTabPage.java
- fixes #725
- add new logic to StringConcatToTextBlockFixCore to support changing a StringBuffer or StringBuilder append sequence to a Text block if the buffer is converted to string
- add new preference to include StringBuffer/StringBuilder sequences for the StringConcatToTextBlock cleanup
- add preference to JavaFeature tab page
- add new tests
Adds support to cleanup and quick assist to convert a StringBuffer or StringBuilder sequence
of appends that eventually are used as a String into a Text Block.
See issue and added tests.
> Support StringBuffer/StringBuilder concat to Text Block

- org.eclipse.jdt.ui/plugin.xml
Preventing conflicts with other plugins that provide same binding for other commands in more generic context
> Forces key binding to Open Type inside JDT editor

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/nls/NLSUtil.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- add new method getCommentsForRegion() to ASTNodes
- modify StringConcatToTextBlockFixCore to support NLS comment checking for the various lines of the string concatenation and fail if inconsistent
- make NLSUtil scanCurrentLine() public
- add new tests to CleanUpTest15 and AssistQuickFixTest15
Adds checking to the string concat to text block cleanup and quick fix so that it does not occur if all segments are not consistent in being non-NLS or not.
See issue and new tests.
> Make string concat to text block NLS consistent

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedTypesQuickFixTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
- fix problem introduced by #352
- check for inheritance should not be run if the suggested class binding has same name as the missing class
- fixes #485
Fixes regression.
Run tests specified in new issue and old issue.
> Fix regression in UnresolvedElementsSubProcessor

- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/performance/EditorTestHelper.java
Removes one more reference to the long deprecated Navigator view.
Verification build still succeeds.
> Remove Navigator view id constant in tests

- org.eclipse.ltk.ui.refactoring/src/org/eclipse/ltk/internal/ui/refactoring/PreviewWizardPage.java
- fixes #474
Properly updates the PreviewWizardPage title when reentered.
See issue.  Perform Source->Cleanup and choose multiple cleanups then hit Next button.  Click the filter icon on top right and choose one of the cleanups to filter.  This will change the message to state which cleanup is being shown.  Hit the Back  button and then re-select the Next button.  When the page is shown again it should not state that items are being filtered in the title message (should just be "Changes to be performed")
> Cleanup wizard summary must be refreshed on page entry

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/MoveTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedTypesQuickFixTest.java
- ensure that new imports or package statements don't obliterate header comments
Adds tests to verify #649
Run tests or see issue.
> New tests for verifying #649

- org.eclipse.jdt.ui/plugin.xml
- fixes #102
Fixes enablement for Source menu to work if multiple projects are selected and at least 1 is a Java project.
Create a Java project and a generic project.  Select both the Java project and generic project and invoke the context menu.  The Source menu should appear.  If just the generic project is selected, the Source menu should not appear.
> Allow Source menu for multi-project selection if at least one is Java

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/CopyQualifiedNameAction.java
Only copy the name when the user asks for that.
"copy qualified name" from package explorer of any file, paste to Teams/Word
> CopyQualifiedNameAction: never copy file eclipse.platform#372

- org.eclipse.jdt.ui/templates/default-codetemplates.xml
This was useful at times where many people did not have version control or a version control system that was not easy to use and query. Today that leads to lots of problems:
* The same information is better available in the version control history, with attribution by line instead of assuming this one author for every line currently in the file
* People copy/paste classes to create "something similar", without fixing this comment.
* It may leak information of the private user account to the public (at least on Windows, this defaults to your local user account id, and my company admin would surely not like me posting that account id everywhere).
* Even developers without an underlying version control system should not rely on this information, but rather be nudged to set up a real version …
> remove author from default code templates (#374)

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitEditor.java
- fixes #509
If two quotes already exist and text blocks are supported by the project, don't close a third quote.
See issue.
> Don't add closing quote to three quotes if text blocks are supported

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/BuildPathBasePage.java
Adjust `BuildPathBasePage.moveCPElementAcrossNode()` to use selection index only if this index is in the bounds of the new container.
Fixes: #478
> IOOBE when moving JUnit5 container from module path to classpath

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
- fix layout to accommodate long JRE names
- fixes #517
Fixes New Java Project Wizard layout when the default JRE has a long name and avoids horizontal scrolling.
Set up the default JRE to be one with a long name (e.g. openjdk JREs can have long names).  Open the New Java Project wizard and verify there isn't horizontal scrolling required.
> Fix New Java Project Wizard layout

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/IndentActionTest15.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/IndentAction.java
- fixes #572
- don't calculate additional indentation for start of text block and don't apply text block indent rules to start of text block if previous token is a comma which implies an array init or a parameter list for example (i.e. use default indentation rules for array init or parameters)
Fixes SIOOBE caused when moving start of text block.
See issue.
> Fix SIOOBE in IndentAction when moving start of text block

- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TextualTrace.java
- don't start filtering lines until we have the first stack trace line
- fixes #372
Avoids filtering of JUnit trace until the stack trace lines start.
See issue test.
> Refine filtering of JUnit stacktraces

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/MethodInsertCompletionTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/CompletionProposalCollector.java
- fixes #417
- add new test to MethodInsertCompletionTest
Does not filter out types when completing a method reference as the type is already known and specified.
See issue.  A new test has been added as well to filter out java.lang.String and then to try to complete a method call for a variable declared as java.lang.String.
> Don't filter type for method completion as type is known

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/buildpath/BuildpathTestSuite.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/buildpath/ClassPathElementsOrderTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/BuildPathBasePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/LibrariesWorkbookPage.java
Class path order is fixed and can be changed manually on Order and Export tab. Addition of any element to class path should be added at the end of the list and previous elements should be at their location.
Fixed redundant notification to adapter in case of removing all elements in the Libraries List.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/519
> Java Build Path : Adding an external jar in the Libraries tab incorrectly changes the class path order in Order and Export tab #519

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/IndentActionTest15.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_5/Before.java
- org.eclipse.jdt.text.tests/testResources/indentation15/issue414_5/Modified.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/IndentAction.java
- fix IndentAction for text blocks to properly identify current line vs opening of text block
- enable IndentActionTest15 in JdtTextTestSuite
- add issue414_5 test
Fixes moving the opening quotes of a text block in a better manner than fix for #532
Run IndentActionTest15
> Create better fix for #532

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterModifyDialog.java
- required by: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/991
Adds new option to not put html block tags in Javadoc on separate lines.
This is just the options and will require JDT core functionality added.
> Add new formatter option for not separating html block tags in Javadoc

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- fix PatternMatchingForInstanceofFixCore to check if variable to move has final modifier in which case add it to pattern
- fix CleanUpTest16 test
- fixes #1012
Fixes the instanceof pattern matching cleanup to preserve final modifier if used in variable declaration.
Run CleanUpTest16.
> Instanceof pattern cleanup should preserve final modifier

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/AbstractJavaCompletionProposal.java
Unreproducible exception after bigger code block editing/undoing/switching between editors, and triggering code completion.  
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.IDocument.get(int, int)" because "document" is null
at org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal.isAutoInsertable(AbstractJavaCompletionProposal.java:1338)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.canAutoInsert(CompletionProposalPopup.java:1624)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.lambda$0(CompletionProposalPopup.java:513)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
```
Adds an extra check, before IDocument.get(int, int) is called in the code completion generator.
As this …
> Fix NPE in AbstractJavaCompletionProposal

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/CreateMultipleSourceFoldersDialog.java
... using the Java Build Path properties.
Fixed regression introduced via
https://github.com/eclipse-platform/eclipse.platform.ui/pull/243/ in 4.25.
The default wizard modality was changed from SWT.APPLICATION_MODAL to SWT.PRIMARY_MODAL. This seem to break nested modal dialogs opened from the Java Build Path property page on Mac and Windows.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/557
> [Mac/Win] Unable to add a new source folder to a Java project

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/search/NLSSearchTest.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/nls/search/NLSSearchQuery.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/nls/search/NLSSearchResultRequestor.java
- add enhancement to be able to specify XXXX.usedproperties file which contains property keys known to be used (e.g. a key that gets dynamically created where it is used such as in ResourceAction
- modify NLSSearchResultRequestor to read .usedproperties files if they exist and keep a set of used properties
- modify NLSSearchQuery to check if an unused key has actually been specified as used via the .usedproperties file
- add new test to NLSSearchTest
- for #555
Adds the ability to specify that NLS property keys are known to be used and should be ignored by the "Find broken NLS strings" action.  It does this by allowing properties from XXXX.properties to be added to XXXX.usedproperties.  The NLS search will mark such properties as used and will not report them.
A new test has been added to …
> Add ability to specify used properties to avoid NLS search marking them

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_394725.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_394725.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- modify InlineMethodRefactoring to verify imports are not in CU
- fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=394725
Removes extraneous import to a class that is in the current CU when doing a method inline.
See added test or bug.
> Fix extraneous import to class in current CU when inlining method

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavadocHover.java
The hovers shown for content assist **are** immediately disposed, and that seem to be OK. 
So why not the editor hovers?
The idea is just to dispose the controls once they are hidden for at least 5 seconds. This seem to work for me, but I haven't checked why we actually don't do this by default.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/528
> Dispose javadoc hover widgets after delay

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/567
> [21] Allow JDT to target Java 21 in compiler preferences

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/ReorgMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaUIMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ActionMessages.usedproperties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/FoldingMessages.usedproperties
- part of #555
Adds .usedproperties files to protect known used messages that are normally flagged when searching for broken externalized strings.
Perform a Find Broken Externalized Strings actions on org.eclipse.jdt.ui.  Messages and keys in these files will not show up as unused.
> Add usedproperties files for known used messages in org.eclipse.jdt.ui

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallerMethodWrapper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyTestHelper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/CallHierarchyTest.java
Adjust `CallerMethodWrapper.getAccurateSearchScope()` to consider also record components, when checking if a member is private. This avoids reducing the search scope to just the compilation unit of the record defining the component, and so results in the expected search results.
Fixes: #571
> Call Hierarchy for Record components does not work

- org.eclipse.jdt.ui/plugin.properties
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/OpenCallHierarchyHyperlinkDetector.java
Add ability to open the Call Hieararchy viewer whenever the user click on a method call or declaration
Sometimes, when navigating around codebases with the mouse, I miss an easy way to lookup the callers of a method - by default, I must release the mouse, and move my right hand to the keyboard to press the required key-combo to open the view, so I thought, why not add next to the already existing 'Open Declaration'/ etc hyperlinks? And this is what this patch actually does.   
1. Open a non trivial project, with a couple of methods, calling each others.
2. Control click on method declaration or call.
3. Click on the newly provided 'Open Call Hierarchy' link
4. Happiness
> Open call hierarchy view

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest10.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/VarCleanUp.java
- add new test to CleanUpTest10
- fixes #573
Removes unused imports due to a var cleanup.
See new test in CleanUpTest10.
> Add import removal support to VarCleanUp

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
- add verification that iMethod root is same as root we are using NodeFinder on
- fixes #592
Fixes regression.  See issue.
See issue.
> Fix regression in RenameLinkedMode

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/StubUtility.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertIterableLoopOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLoopOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ConvertLoopOperationTest.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- modify StubUtility() to add new rules to generate names for extracted local variables.
- add popular plural words (irregular cases) to ConvertLoopOperation.java to support the singularization of plural words.
- add test to ExtractTempTests.
- fixes #601 .
see issue cited.
Run test153, and test154 in ExtractTempTests.
> Automated Name Recommendation For The Extract Local Variable Refactoring

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CreateObjectReferenceProposal.java
- fixes #597
Change-Id: I50c839c0b749a3cc0631a10520a8e61161a19542
Adds null check.
> Add null check to CreateObjectReferenceProposal.findReference()

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/NoStringCreationCleanUpCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/NoStringCreationCleanUp.java
- fixes #577
Refactors NoStringCreationCleanUp to jdt.core.manipulation so jdt.ls can use it.
Run CleanUpTest.
> Refactor NoStringCreationCleanUp to jdt.core.manipulation for jdt.ls use

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/MissingCodeTabPage.java
- register the annotations preference as well as the add SUID preference so that select all/deselect all works for them
- fixes #582
Allows select all/deselect all buttons to work for annotations cleanup.
Go to Source -> Cleanup -> Configure -> Missing Code  page and use the select all/deselect all buttons.
> Fix MissingCodeTabPage to work with select all/deselect all

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewClassWizardPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
Adds checks for new class wizard so it flags any super class that is final as an error and also when calculating the super class, it will not propose a final class.  Fixes #554
See issue.
> Fix NewClassWizard to prevent final super classes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- use AbstractTypeDeclation instead of TypeDeclaration to handle enums and their constructors
- add new tests to CleanUpTest
Fixes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=475462
See new tests in CleanUpTest and in bug.
> Fix for Bug 475462

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/EnumConstructorTargetFinder.java
- fixes #622
Removes an extraneous check in an if/else.
Examine code.
> Remove extraneous if case in EnumConstructorTargetFinder

- org.eclipse.jdt.ui/plugin.properties
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
- add new JavaConstantHover class
- add new hover to o.e.jdt.ui plugin.xml
- add new hover property strings
- fixes #639
- for Bug 559614
Adds new hover to use on hex, octal, and binary constants to see value.
See bug.
> Add new hover for Java hex, octal, and binary constants

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/LambdaExpressionsCleanUpCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstants.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstantsOptions.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/JavaFeatureTabPage.java
- make the default behavior for a quick fix or Java feature convert to lambda cleanup to use method refs
- add new preference under Java feature page for lambda conversion to simplify expression and make it true by default
- have the cleanup check for either the new preference or the preference for simplify lambda expression and method reference syntax which fixes the issue that cleanups are not recursive so user does not have to do two cleanups in a row
- make quick fix default to use method refs
- add new tests to CleanupTests1d8
- fix cleanup ordering in jdt plugin.xml so when recursive cleanups are supported it will just work and duplicated code can be removed
- fixes #629
Enhances the convert to lambda cleanup to also do method ref simplification instead of forcing the end-user to …
> Merge method ref simplification support into LambdaCleanUpFixCore

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionAndMethodRefFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Adds a new quick fix to convert a lambda expression: x -> x instanceof Y; into  x -> Y.class::isInstance;  Also adds logic to lambda cleanup to recognize when an instanceof can be converted into a type method reference.
See new tests.
> Lambdainstanceof

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedCodeCleanUpCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/SaveParticipantTest.java
- fixes #313
- add new tests to SaveParticipantTest
Fixes save actions to not remove unused parms when not asked to.
See test case and issue.  Modify file and do a save.  Method parameter should not be removed unless specified in save actions.
> Fix save actions to not automatically remove unused private parameters

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/ExtractInterfaceProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractInterface/testDeprecated1/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractInterface/testDeprecated1/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractInterface/testDeprecated1/out/I.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractInterfaceTests.java
- fixes #630
- add new test
Adds '''@Deprecated''' annotation to any deprecated method declared in new interface.
See new test.
> Fix extract interface to properly specify deprecated methods

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedTypesQuickFixTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsSubProcessor.java
- fixes #657
- add new code in UnresolvedElementsSubProcessor to recognize when a lower-case enhanced for-loop variable that has no type causes a "create loop variable xxxx" proposal and then do not suggest creating new types, records, etc...
- modify existing test in UnresolvedTypesQuickFixTest
See issue.
Run UnresolvedTypesQuickFixTest.
> For lower-case for-loop variable without type, only suggest adding type

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CoreASTProvider.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaElementLabelComposerCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaManipulationPlugin.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingPresenterCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/SerialVersionHashOperationDisplayCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/core/refactoring/descriptors/JavaRefactoringDescriptor.java
- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestRunnerViewPart.java
- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/CodeMiningTriggerTest.java
Replace `Platform.getLog` with new `ILog.of` to reduce references to single singelton from split package.
> Use new ILog.of(...) method instead of Platform.getLog(...)

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/flow/InputFlowAnalyzer.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_in/A_testIssue671.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_out/A_testIssue671.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- fixes #671
- add BreakStatement method in InputFlowAnalyzer.LoopReentranceVisitor to ignore break statements that precede the selected code
- fix binding equality check in ExtractMethodAnalyzer
- add new test to ExtractMethodTests
See issue.
> Fix refactor method false error regarding ambiguous return value

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/StringCleanUp.java
- when doing a quick fix for missing nls markers and choosing to fix n instances of same warning, don't add missing NLS markers to lines covered by a SuppressWarnings(nls) whereby they don't cause a problem info of warning to be generated
- fixes #626
Fixes add nls quick fix when missing nls markers are a warning to not extraneously fix missing nls markers that are
covered by a SuppressWarnings("nls") statement
See issue.
> Don't add nls markers for lines covered by SuppressWarnings

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitDocumentProvider.java
The `CompilationUnitDocumentProvider` uses in its Java-specific annotation model a utility map to navigate from document positions back to annotations (called `ReverseMap`). The current implementation is slow whenever a document contains plenty of annotations (such as the occurrences of the name of a marked method), as the map internally uses a list for representing the annotations which becomes slow in adding/removing when containing plenty of data. This is especially a problem on batch replacements of annotations (e.g. when selecting a different method to be marked in the document), as every single annotation is processed by the map individually. In addition, the map currently stores data that is never used, as only the specific JavaMarkerAnnotations are used from that map.
This change …
> Remove unused data from compilation unit annotation model util map #665

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddUnimplementedMethodsOperation.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/util/JDTUIHelperClasses.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceFactoryRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ExtractSupertypeProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/AnonymousTypeCompletionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/OverrideCompletionProposal.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/700
This patch moves one function out of StubUtility2 and into StubUtilityCore2, as well as migrate callers to using the Core version.  This helps make more logic accessible to headless installations or consumers like jdt.ls. 
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/700
This is a code cleanup patch and should theoretically have no effect on functionality or performance.
> Move functionality and migrate callers from StubUtility2 to StubUtility2Core

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/JUnitPreferencesConstants.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/JUnitContainerInitializer.java
- additionally avoids returning "null" classpath entries from JUnit 5 container and properly logs if a bundle was missing.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1245
> Fixes broken Unit 4 & 5 support after hamcrest update from 1.x to 2.x

- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.properties
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/util/TestSearchEngine.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationTab.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/TestMethodsCache.java
Move the logic to search for test methods from `JUnitLaunchConfigurationTab` to `TestSearchEngine::findTestMethods`. Extract the whole logic for caching the results into `TestMethodsCache` (new class) and do the whole searching and caching more efficiently i.e. only when necessary and showing the progress with a monitor by using `ModalContext::run`
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/683
Contributes to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/653
This PR shows a progress indicator when searching for test methods in a class (which may happen when one opens a JUnit run configuration). The progress indicator looks like this when you first open the _Run configurations_ and a JUnit configuration is selected:
... and like this when you select or edit an …
> Show progress when searching test methods in JUnit run configuration #653

- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestSessionLabelProvider.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorBreadcrumb.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaOutlinePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/PackageExplorerPart.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaOutlineInformationControl.java
**This PR won't compile unless you have changes from [810](https://github.com/eclipse-platform/eclipse.platform.ui/pull/810) on your workspace**
This will limit the number of elements populated in Package Explorer, Outline view for Java editor and editor breadcrumb viewer to the common value defined by the workbench.
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/810 for detailed theory of operation and use case examples.
> Use limit based viewers #631

- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
Hard require at least 3.204.0 version of `org.eclipse.ui` which re-exports new API we use from `org.eclipse.ui.workbench`.
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/1051
> Final version bump for org.eclipse.ui dependency

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
was ArrayIndexOutOfBoundsException
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/740
> QuickAssistProcessor: prevent AIOOBE in getAddMethodDeclaration() #740

- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithResourcesTests1d8.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithTests16.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithTests1d7.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/SurroundWithTests1d8.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryWithResourcesRefactoring.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SurroundWithTryCatchAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SurroundWithTryMultiCatchAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SurroundWithTryWithResourcesAction.java
The refactors themselves should not require UI, whenever possible, while the actions that call them are inherently UI creatures and should have access to the UI classes. 
This patch removes some utility functions which help create SurroundWithTryCatchRefactoring.java and SurroundWithTryWithResourcesAction.java, and ask the action to provide the various required integers themselves instead of passing in a UI element. 
This will help separate core and UI more effectively in the near future.
> Remove ITextSelection references from some refactors

- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstantsOptions.java
Change the default settings of the built-in clean-up profile and in the "_Additional actions"_ of the "_Save Actions_"; set them to always use brackets for blocks of code (even for one-liners).
These settings are just the defaults, they can be overwritten.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/667
* Open a newly created workspace
* Open _Window > Preferences > Java / Editor / Save Actions_
* Check _Perform the selected actions on save_
* Check _Additional actions_
* Click _Configure_
* Switch to the tab _Code Style_ --> _Use blocks in if/while/..._ should be checked
* If it's not checked then you probably loaded some preferences from your user-space. Click _Restore defaults_ --> it should now be checked.
* Open a newly created workspace
* Open _Window > Preferences > …
> Always use brackets in blocks of code by default #667

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/Java50FixCore.java
- org.eclipse.jdt.core.manipulation/pom.xml
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest10.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTestSuite.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- add var checks to Java50FixCore.createRawTypeReferenceOperation()
- make some static methods public in Java50FixCore regarding raw type reference checking
- add var checking to LocalCorrectionsSubProcessor
- add new LocalCorrectionsQuickFixTest10
- fixes #765
Removes proposals to add type parameters to a var typed variable declaration.
See issue and new test case.
> Don't offer to add type parameters to var type variable

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- retain the comment for the declared variable that is cast to the type in the instanceof expression that will be converted to instanceof pattern
- modify existing test in CleanUpTest16
- fixes #729
Fixes the pattern instanceof cleanup to preserve the comment for the cast statement that gets removed.
See test modification.
> Preserve comment on variable cast when doing pattern instanceof cleanup

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavadocContentAccess2.java
- fixes #743
- add new test to JavadocHoverTests
Adds unicode support in Javadoc hover so unicode characters are properly displayed.  See issue.
See new test and issue scenarios.
> Add unicode support to Javadoc hover

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/JavaSpellingEngine.java
- add text block partitions to ignore logic in JavaSpellingEngine
- replaces #707
- fixes #770
Fixes spell checking to ignore both Java regular string literals and Java text blocks when the user has chosen to ignore spelling in Java strings.
See issue.
> Ignore spelling in java string literals should apply to text blocks too

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
getResourceAttributes() can return null
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/738
> JavaModelUtil: fix NPE in isEditable() #738

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaManipulationPlugin.java
This patch adds some logging utility methods to the Plugin class in jdt.core.manipulations. While these logging functions are not strictly necessary right now, they will be necessary in the very near future when patches that move large numbers of classes from the 'core refactor' folder in jdt.ui  into jdt.core.manipulations are proposed. 
This patch will ensure that those classes can be moved / renamed without having to modify much code during the move other than necessary constants.
> Add logError(String) to Manipulations plugin

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- modify QuickFixProcessor to recognize an UndefinedVariable error for an annotation value and propose import if possible
- add new tests to QuickFixTest1d8
- fixes #717
Fixes old bugzilla bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=421693 which has a missing import for an annotation value and Eclipse does not propose adding an import.
See bug or new tests.
> Propose import quick fix for missing annotation value

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- if an uninitialized field is used inside a lambda expression to initialize another field, it cannot be made final
- add this logic to VariableDeclarationFixCore
- fixes #769
Adds checks to the add final specifier to private fields cleanup so it doesn't do this for fields that are used in other field's initializers that are lambdas.
> Don't make a field final if used in lambda exp used to initialize field

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaElementImplementationHyperlink.java
newTypeHierarchy is a JavaModelOperation which uses SubMonitor.convert since https://bugs.eclipse.org/bugs/show_bug.cgi?id=477790 That is not allowed when beginTask is already called. See SubMonitor.convert javadoc.
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1107
> JavaElementImplementationHyperlink: fix progress during newTypeHierarchy

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/783
Provides quick fix: Add 'default' case
Before:
```
package pkg;
public class Snippet {
int m1(R<X> c) {
return switch (c) {
case R<X>(X x, Y y) -> 1;
case R<X>(Y y, X x) -> 2;
};
}
}
class X {}
class Y extends X {}
record R<T> (T x, T y){}
```
After:
```
package pkg;
public class Snippet {
int m1(R<X> c) {
return switch (c) {
case R<X>(X x, Y y) -> 1;
case R<X>(Y y, X x) -> 2;
default -> throw new IllegalArgumentException("Unexpected value: " + c);
};
}
}
class X {}
class Y extends X {}
record R<T> (T x, T y){}
```
> [21][quick fix] Provide quick fix to add default case for exhaustive enhanced switch statement

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- make sure before creating a change operation that any InfixExpression that has NLS tags has either a Statement or FieldDeclaration ancestor in StringConcatToTextBlockFixCore
- fixes #779
Fixes potential NPE in string concat to text block cleanup/quick-fix.
Declare a String field that initializes using a string concatenation and has at least one NLS tag for concatenation parts.
> Fix NPE for StringConcatToTextBlockFixCore

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
Show hovers also in the following cases:
```java
int bin1 = 0B11111111; // uppercase "0B"
int bin2 = 0b1111_1111; // binary with an underscore
int oct = 0_377;  // octal with an underscore
int hex = 0xff_ff_ff; // hex with underscores
```
Do not show hovers for doubles starting with "0", e.g.:
double d= 01e6D;
This does not fix the issue that hovers are shown in the following cases where they are not make sense:
```java
double d2= 012.045;
```
- First hover for "012": "10 : [0xa]"
- Second hover for "045": "37 : [0x25]"
See also https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/640
> Improve hover for Java hex, octal, and binary constants

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeConstraintsCreator.java
- org.eclipse.jdt.ui/.settings/.api_filters
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/surround/SurroundWithTryCatchAnalyzer.java
- new AST for 20 and up changes PatternInstanceofExpression and this needs to be accommodated in some refactoring logic
- change SuperTypeConstraintsCreator and SurroundWithTryCatchAnalyzer to handle updated version of PatternInstanceofExpression
- fixes #745
Fixes some problems found in the Y-builds due to newer AST API level.
See tests in question.
> Fix build test errors due to AST API >= 20

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeConstraintsCreator.java
- modify endVisit(Type) to support all AST api levels 21 and below
Tweaks the logic in SuperTypeConstraintsCreator for PatternInstanceofExpression to handle AST api 21 and below.
Run the UseSuperTypeWherePossibleTests and UseSuperTypeWherePossibleTests16 tests.
> Tweak SuperTypeConstraintsCreator logic

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/DestinationContentProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/StandardJavaElementContentProvider.java
findPackageFragmentRoot() searches through all PackageFragment Roots for every IContainer.member. This can be slow due to involved file access. see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/303
Instead call getAllPackageFragmentRoots() only once, index the result and use O(1) hash access.
> performance: avoid O(n^2) in ContentProviders

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/CleanUpRefactoringWizard.java
To avoid sorting using toString() which uses
org.eclipse.jdt.internal.core.JavaElement.toStringChildren(int, StringBuffer, Object) on every project ...
> performance: use JavaElementComparator in CleanUpRefactoringWizard

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpTabPage.java
Fixes number of selected cleanups. Since
CleanUpTabPage.registerSlavePreference calls registerPreference(master) again.
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/797
> Clean Up Preferences: register each preference only once #797

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/jarexport/FatJarExportTests.java
Increase timeout to 30s per test instead of 5s. This doesn't slow down the tests execution, it just lets the tests run a bit longer if the hardware is slow.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/699
Run the tests in `org.eclipse.jdt.ui.tests.jarexport.FatJarExportTests`, they should pass.
✔️  I have thoroughly tested my changes
✔️ The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
✔️ I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)
> Increase timeout in FatJarExporTests to reduce the chances of tests failing randomly on slow hardware

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fixes #820
Fixes regression caused by new constant naming proposal trying to cast TypeBinding to IVariableBinding.
See issue.
> Fix regression caused by convert field name proposal

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/StubUtility.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test159_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test161_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test161_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
> Recommend variable name for Extracted Local Variable Refactoring when the extracted expression is a method invocation

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaSourceHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/SourceViewerInformationControl.java
Adds full semantic coloring to content of Java source hover viewer.
~~Functionality can be toggled with new checkbox added to Preferences / Java / Editor / Syntax Coloring / "Full semantic syntax coloring in Java source hover" at the very bottom, enabled by default.~~ edit: removed
Behaves exactly like current hover in terms of presented content, size and reaction when trying to "enter into" hover viewer with mouse cursor.
Only difference is that when hovering over class / method / field / constant / variable name, if the element has JavaDoc or single/multi line comment above it's declaration, it will also be part of hover viewer content, but will not be presented / visible right away, but only after user "enters into" viewer and scrolls up.
This difference is intentional since I believe …
> Apply semantic syntax coloring in Java source hover viewer. Fixes #437

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- add createTextChange() that uses delegate into FixCorrectProposal
- add getRelevance() method to call delegate as well
- fixes #826
Fixes regression #826
Try using CTRL+1 on String concatenation and selecting to change to Text Block.
> Add back some missing methods to FixCorrectionProposal

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/AbstractAnnotationHover.java
- new split of proposals into jdt.core.manipulation changed the computeNumberOfFixesForCleanUp() method to be passed an ICleanUpCore that is wrappered to be an ICleanUp but this code looks for an IMultiFix which gets lost in wrapping
- change computeNumberOfFixesForClean() to use the fCleanUp field that is already stored and is an ICleanUp
- fix getCleanUp() to return fCleanUp
- fix AbstractAnnotationHover.createCompletionProposalsList() to just call proposal.getCleanUp() and don't do any wrapping
Fixes regression so multiple NLS fixes will be offered for the whole file.
See issue.
> Fix FixCorrectionProposal to properly handle IMultiFix cleanups

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java15ProjectTestSetup.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- add check for being in Annotation before looking to see if NLS comments are set up
- bail if NLSUtil.scanCurrentLine() fails
- add new setup method to Java15ProjectTestSetup to make annotations accessible
- fixes #824
Fixes #824
See new tests or issue.
> Fix string concat to text block cleanup logic when in annotation

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/correction/CUCorrectionProposal.java
See https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/compilelogs/jdt.doc.isv.javadoc.txt
```
../../../eclipse.jdt.ui/org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/correction/CUCorrectionProposal.java:147: error: @param name not found
* @param delegate to set ^
```
Regression from 816a5d21cf7c29294915c50bd95503e0462eff02 / #815
> Javadoc error fix for CUCorrectionProposal.setDelegate()

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileLoopToChangeHit.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
- add new name checking logic so the chosen loop var name is not already used
- add some logic to remove added imports if they are found in the current file
- fixes #798
Fixes while to for-each loop cleanup.
See issue and new test.
> Fix while to for-each loop logic

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaOutlinePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/PackageExplorerPart.java
As we had introduced changes in getRawChildren to return remaining elements as children for ExpandableNode we had to explicitly make this change. Now we don't return remaining elements as children for ExpndableNode.
> isExpandableNode API usage is removed.

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/AbstractDeleteChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/CopyResourceChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/DeletePackageFragmentRootChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/DeleteSourceManipulationChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/PackageFragmentRootReorgChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/RenameJavaProjectChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/RenamePackageChange.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/UndoablePackageDeleteChange.java
The org.eclipse.core.resources.undo new API addition seems to require some cleanup to make it more usable. This PR will respond to that. 
This build is expected to fail until the changes at https://github.com/eclipse-platform/eclipse.platform/pull/729 are merged in. 
A simple build passing for compilation should be sufficient. Risk of change is minimal.
> Respond to changes in undo API

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/PackageExplorerPart.java
'Link with Editor' tries to select visible parent in case of element being linked is not created yet on tree viewer. Similar implementation is used for 'Show In'
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1014
> Support 'Show In' similar to 'Link with Editor'.

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/850
> Add quick fix to remove default case when present with unconditional pattern in switch #850

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/Java50FixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/generics/InferTypeArgumentsRefactoring.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest10.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- fixes #774
- add var check in InferTypeArgumentsRefactoring.rewriteTypeVariable()
- make Java50FixCore.getRawReference() method public
- modify LocalCorrectionsSubProcessor.referencesVar() method to handle more cases
- add new test to LocalCorrectionsQuickFixText10
See issue.
> Fix problem with adding type arguments to var variable

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/AddUnimplementedMethodsTest1d8.java
- fix add unimplemented methods to recognize when an abstract method is implemented via a parameterized type
- add new test to AddUnimplementedMethodsTests1d8
- fixes #863
See commit comment.
> Fix add unimplemented methods

- org.eclipse.jdt.ui.junit.sampleproject/.project
Remove the _maven_ nature for the sample project `org.eclipse.jdt.ui.junit.sampleproject`.
The tests seem to work just fine without it and the IDE keeps removing it for me anyway, which shows a change to be committed and it's annoying.
Run the test suite `/org.eclipse.jdt.ui.junit.sampleproject/src/test/java/junit/samples/AllTests.java`
> Remove maven nature from org.eclipse.jdt.ui.junit.sampleproject

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest.java
- fix OrganizeImportsOperation.addStaticImports() to not return when static favorite imports preference is unset
- add new test to ImportOrganizeTest
- fixes #853
Fixes organize imports when a static import is used in addition to a break label.  See issue and new test.
> Fix organize imports when break label used

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringBufferToStringBuilderFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #869
- add logic to handle StringWriter.getBuffer()
- add new test scenario to CleanUpTest1d8
Fixes StringBuffer to StringBuilder clean up to handle StringWriter.getBuffer().
See issue or new test scenario.
> Fix StringBuffer to StringBuilder cleanup

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
If there is a main method candidate it ensures that the class is runnable.
JavaModelUtils is used in JavaElementImageProvider and this change makes classes with instance main methods being shown as runnable in the Outline view if running on Java 21 with --enable-preview set.
> Recognize instance main methods as such in the UI

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/pom.xml
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/JUnitContainerInitializer.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/JUnitCore.java
This adds the infrastructure for disabling the adding of vintage engine/junit4 to the classpath of the JUnit5 container.
See 
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/837
This does not add the UI part yet as I first want to get generals agreement on this before I start with further improvements.
@iloveeclipse @akurtakov can you review and/or suggest a reviewer?
FYI @HeikoKlare
> Add support for disabling the vintage engine with an attribute

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/Bindings.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest16.java
- add logic to Bindings.getBindingOfParentTypeContext to handle records
- add new ImportOrganizeTest16
- fixes #890
Fixes organize imports to not add import for a nested class of a record.
> Do not create import for nested class of record with organize imports

- org.eclipse.jdt.junit5.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/src/org/eclipse/jdt/internal/junit5/runner/JUnit5TestReference.java
A VM property with name `JDT_JUNIT5_RUNNER_STOP_REQUESTED` is set when the JUnit view requested to stop JUnit 5 test execution.
This property can be used by test frameworks based on JUnit, to stop test execution. JUnit 5 itself doesn't yet support stopping test execution.
Partial workaround for: #889
> Set a VM property when JUnit view requested a stop during JUnit 5 tests

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/RemoteTestRunnerClient.java
- org.eclipse.jdt.junit5.runtime/src/org/eclipse/jdt/internal/junit5/runner/JUnit5TestReference.java
This change throws an OutOfMemoryError before a test starts (via TestExecutionListener), if the JUnit view requested a test execution stop during JUnit 5 tests.
An OOME is the only type of exception that is not swallowed by the JUnit 5 framework, when notifying a TestExecutionListener.
Fixes: #889
> Stop JUnit 5 execution on JUnit view stop request

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/infoviews/AbstractInfoView.java
The methods override the default empty implementation with the same empty implementation. This yields an unnecessary "info" in the problems view
> Remove some empty methods from internal class in AbstractInfoView

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/SourceViewerInformationControl.java
Fixes NPE causing Java source hover viewer to not be displayed from ClassFileEditor.
Open any Java class (one coming from library for which there is source code attached) inside ClassFileEditor, e.g. java.lang.String, and try to show Java source of some element, e.g. class itself, by hovering over it (e.g. class name) while holding SHIFT.
> Fix JavaSource hover not displayed from ClassFileEditor. Fixes #936

- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fix logic in QuickAssistProcessor.getStringConcatToTextBlockProposal() to also support StringBuffer or StringBuilder variable declaration that can be converted to Text Block
- add new test to AssistQuickFixTest15
- fixes #882
Provides a quick assist to convert a StringBuffer or StringBuilder concatenation to a text block similar to what is offered
in a cleanup.
See new test.
> Enable StringBuffer to Text Block quick assist

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/nls/NLSHint.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/nls/NLSHintStripQuotesTest.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/nls/NLSTestSuite.java
- fixes: #906
- fix NLSHint.stripQuotes() to recognize a text block
- add new NLSHintStripQuotesTest class
Fixes Externalize Strings wizard to recognize a text block input and properly calculate the externalized string.
See new tests or issue.
> Fix Externalize Strings when input is a Text Block

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateConstructorUsingFieldsTest.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/GenerateConstructorUsingFieldsSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/SourceActionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/GenerateNewConstructorUsingFieldsAction.java
- add new constructor to SourceActionDialog to accept flag that allows empty tree and pass this on to super class
- remove zero fields test in GenerateConstructorUsingFieldsAction
- add new test to GenerateConstructorUsingFieldsTest
- fixes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=552556
Fixes bug 552556
See new test.
> Allow generate constructor using fields on class with no fields

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/StaticImportFavoritesCompletionInvoker.java
Originally from https://github.com/redhat-developer/vscode-java/issues/3383
- Do not recompute favorite static imports for an unknown type
- Reuse compilation unit working copy in code completion logic
I tested at runtime against https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/XMLAssert.java by removing all imports and triggering the organize imports functionality. Any easy reproducer is just create some source file with **a lot** of static imports. Remove them all, and call "Organize Imports".
`ImportOrganizeTest*` were useful for testing this. If I have some time, I can investigate adding something to `OrganizeImportsPerfTest`. **Update:** The existing performance tests there don't seem to have any useful assertions as far as I can …
> Cache the list of names whose favorite static imports we have resolved.

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/914#issuecomment-1831635568
- jdt.core.manipulation received an unnecessary minor version bump, where a service bump was sufficient
> Work around API tooling warning regarding unnecessary minor bump.

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestSuiteElement.java
When running JUnit 5 @TestTemplate tests, extra test suites are shown in the JUnit view to represent the tests in the template. Those suites introduce unnecessary noise when the template contains only one test - e.g. when repeating tests that failed.
This change adjusts TestSuiteElement.getChildren(), pruning each TestSuiteElement that has a single TestCaseElement child that is also a dynamic test.
Fixes: #945
> Dont show children for JUnit 5 @TestTemplate tests that ran only once

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/StaticImportFavoritesCompletionInvoker.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest16.java
- Helper method createNewCompilationUnit should always return an array.
@robstryker adopted the latest 4.31-I-builds at https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2947, and they uncovered a regression in the organize imports logic : https://ci.eclipse.org/ls/job/jdt-ls-pr/4816/ when triggered in a module file.
```
java.lang.NullPointerException: Cannot load from object array because "res" is null
at org.eclipse.jdt.internal.corext.util.StaticImportFavoritesCompletionInvoker.getStaticImportFavorites(StaticImportFavoritesCompletionInvoker.java:54)
at org.eclipse.jdt.core.manipulation.OrganizeImportsOperation.addStaticImports(OrganizeImportsOperation.java:722)
at org.eclipse.jdt.core.manipulation.OrganizeImportsOperation.createTextEdit(OrganizeImportsOperation.java:621)
at …
```
> Fix incorrect return value in StaticImportFavoritesCompletionInvoker.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/rename/RefactoringAnalyzeUtil.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/rename/RenameAnalyzeUtil.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/IntroduceFactoryTestsBase.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyTestHelper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/HierarchicalASTVisitorTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/JarUtil.java
get rid of
"At least one of the problems in category 'javadoc' is not analysed due to a compiler option being ignored"	warnings
> remove not analysed @SuppressWarnings("javadoc")

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to not bail on a method parameter or assignment where a method is called and the result of the method is not String
- add new test scenarios to CleanUpTest15
- fixes #935
Fixes string concat to text block cleanup to not exclude some valid scenarios whereby the concatenation
is a parameter to a method that may not return a String.
See issue and new test scenarios.
> Fix string concat to text block when string is a parameter

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Fixes an NPE that occurs when a new StringBuffer() is initialized with a string concatenation and the user has specified
Convert String concenation to Text block cleanup with the StringBuffer/StringBuilder option also checked.
See new tests.
> Fix NPE in string concat to text block fix

- org.eclipse.jdt.ui/.settings/.api_filters
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/JavaUI.java
It is a plain oversight as I can not imagine anyone wanting these to be overridden.
Added api_filters to not cause extra warnings in the code.
> Make JavaUI view constants final

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringBufferToStringBuilderFixCore.java
- fixes #961
Fixes an AbortSearchException being thrown in StringBuffer to Stringbuilder cleanup.
See issue.
> Add null check to StringBufferToStringBuilderFixCore

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ComparingOnCriteriaCleanUp.java
- fixes #174
- add logic to buildField to handle wildcard types
- add new scenario to current test in CleanUpTest1d8
Fixes exception caused when using Comparator cleanup with wildcard type.
> Fix ComparingOnCriteriaCleanUp to handle wildcard types

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/InvertEqualsExpressionFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Refactor the invert-equals quick fix implementation to be used in headless mode such as in jdtls.
Existing tests and also making sure the invert equals works as expected through the IDE.
> Refactor invert-equals quickfix for headless mode.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AddInferredLambdaParameterTypesFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AddVarLambdaParameterTypesFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ChangeLambdaBodyToBlockFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ChangeLambdaBodyToExpressionFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/RemoveVarOrInferredLambdaParameterTypesFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/LambdaQueries.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Refactor the lambda related quick fix implementations to be used in headless mode such as in jdtls.
**Refactored QuickFix List**
- ChangeLambdaBodyToBlock
- ChangeLambdaBodyToExpression
- ConvertLambdaToMethodReference
- AddInferredLambdaParameterTypes
- AddVarLambdaParameterTypes
- RemoveVarOrInferredLambdaParameterTypes
Existing tests and also making sure the invert equals works as expected through the IDE.
> Refactor lambda quickfixes for headless

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/JUnitCore.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/testresources/testClasses/JupiterTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnit5TestFinderJupiterTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnitJUnitTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnitTestFinderTest.java
Use the proper test finder according to what the container has. Before this PR, the JUnit4 finder was hardcoded and some tests were not being found.
Fixes #952 
Needs:
1. Create a new Java project
2. Create a class with [nested tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) and add JUnit5 to the classpath
3. Right click on the **project** > _Run As > JUnit Test_
4. Export the _Ant Buildfiles_ of the project via _File > Export > General > Ant Buildfiles_
5. The resulting `build.xml` file doesn't contain the _Launch Configuration_ created in step 3.
After applying this PR, the launch configuration is exported.
Here's a screenshot of the difference in the `build.xml` files created before this PR (left) and after this PR (right)
Here are the generated files: …
> Remove hard-coded test finder from JUnitCore

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/IXMLTags.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestRunHandler.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1000
> JUnit view doesn't support "aborted" JUnit result

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/ResourcesUtility.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ReferenceFinderUtil.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ChangeSignatureTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/NewJavaProjectWizardTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/NewTypeWizardTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
> Fix some SubProgressMonitor

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/OpenAction.java
regression from "Performance: cache JARs during UI Operations" #933
During OpenAction arbitrary other events can be executed in swt thread during BusyIndicator.showWhile()
partial revert of 763d4d0a4c1cc6d5809639ec356a7d499f4d9018
> OpenAction: do not use readOnly - fixes #1005

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/BestMatchHover.java
regression from "Performance: cache JARs during UI Operations" #933
During hover of problems sometimes a dummy quickfix is applied. partial revert of 763d4d0a4c1cc6d5809639ec356a7d499f4d9018
> BestMatchHover: do not use readOnly - fixes #1005

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertIterableLoopOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ConvertIterableLoopQuickFixTest.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1008
The change fixes the conversion of an iterator based for loop to an enhanced for loop. When there is an iterator.next() in the body of the for loop and is not assigned to any variable, it becomes variable; on conversion which is an errorful statement in Java.
Create a for loop with iterator having iterator.next() in the body in any way possible and convert the loop to enhanced for loop from the quick fixes menu.
This PR uses the block of code used by fOccurences for replacing them with comments if available. We extract the block of the code in the fix to a new method so that it can be used by ASTVisitors as well for the statements which dont have any assignments but consists of iterator calls. The extracted block throws …
> Bugfix for Quickfix Converting to Enhanced For Loop Creates Invalid Code #1008

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SelectionDispatchAction.java
regression from "Performance: cache JARs during UI Operations" #933
During SelectionDispatchAction arbitrary other events can be executed in swt thread during BusyIndicator.showWhile()
partial revert of 763d4d0a4c1cc6d5809639ec356a7d499f4d9018
> SelectionDispatchAction: do not use readOnly - fixes #1010

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/dialogs/WizardsTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackager/JarPackageWizardPage.java
When exporting JAR description files from the JarPackageWizard, the elements to be exported into the JAR file are currently stored in a non-deterministic order. This makes it particularly difficult to merge the description files in case they are put under version control. For a detailed description, see #1024.
This change makes a JAR description file exported from the JarPackageWizard always list the exported elements in the same order by sorting them according to their names. It also adds an according regression test.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1024
The behavior can be tested by creating and updating a *.jardesc file from the JAR export wizard. Before this change, the order of elements in the *.jardesc file will vary upon each export, while after this …
> Make order of elements in saved JAR description file deterministic #1024

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnit5TestFinderJupiterTest.java
Read the contents of the java file (test class) as a stream to avoid `NoSuchFileException` in nightly builds.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/999
> Read java file as stream in JUnit5TestFinderJupiterTest #999

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringBufferFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ConvertStringConcatenationProposals.java
Refactor the string concatenation related quick fix implementations to be used in headless mode such as in jdtls.
The refactored quick fixes list
- ConvertToStringBuffer
- ConvertToMessageFormat
- ConvertToStringFormat
Existing tests and also making sure the invert equals works as expected through the IDE.
> Refactor string concat fixes to be used in headless mode.

- org.eclipse.jdt.junit/src/org/eclipse/jdt/junit/launcher/JUnitLaunchShortcut.java
Fixes compiler warning in both workspace and I-build reports (https://download.eclipse.org/eclipse/downloads/drops4/I20240103-1800/compilelogs/plugins/org.eclipse.jdt.junit_3.16.300.v20231218-1450/@dot.html#OTHER_WARNINGS)
> Remove not thrown but declared exception in JUnitLaunchShourcut

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractConstantRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractConstantTests1d7.java
- fixes #1023
- add new test to ExtractConstantTests1d7.java
Fixes the ExtractConstantRefactoring code to recognize when there isn't a target type to extract a constant to and fail gracefully.
See new test or original issue.
> Fix ExtractConstantRefactoring to recognize no type is available

- org.eclipse.jdt.ui/preview/formatter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterModifyDialog.java
Adds a new setting to align arrows on column in switch statements/expressions.
UI part for https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1817
> [formatter] Align arrows on column in switch statements/expressions

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceIndirectionRefactoring.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameTypeProcessor.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit3TestFinder.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit4TestFinder.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ChangeNonStaticToStaticTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpRefactoring.java
To get rid of SubProgressMonitor deprecation warnings
There is still 1 usage (and warning) of SubProgressMonitor in CleanUpRefactoring.CleanUpRefactoringProgressMonitor
> Junit, Refactoring: some SubMonitor usage

- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/schema/javaCompletionProposalComputer.exsd
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/CompletionProposalComputerDescriptor.java
Adds support for code completion within text blocks
This works in tandem with the JDT Core PR - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1803.
This change adds the text block related jdt ui partition to the relevant code completion extensions. 
Fixes #1038 
1. Create a Java15 compliant or above project.
2. Create class C1 and main function in it.
3. Add the below code in the function
4. press `Ctrl` + `Space`, positioning the cursor in the text block after `System.`  
```
String abc= STR."""
\{System.}
""";
```
The expected behavior is that the code completion suggestions should pop up at this stage.
> Add support for code completion inside text block templates #1038

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AddMissingMethodDeclarationFixCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Refactor AddMissingMethodReferenceDeclaration logic to be ready to consume by both Eclipse UI and headless consumers such as jdt.ls
Existing test suite
> refactor method-ref fixes to be used in headless mode.

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringBufferFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- fixes #1040
- don't perform convert to MessageFormat.format() or String.format() unless all string literals have NLS tags or none do
- add new tests to AssistQuickFixTest
Fixes extract string concatenation refactorings to StringBuffer/StringBuilder, MessageFormat, and to String.format() to handle the cases where String literals have NON-NLS tags specified.
See new tests in AssistQuickFixTest
> Fix ExtractConstantRefactorings to handle NLS tags

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- see https://bugs.eclipse.org/bugs/show_bug.cgi?id=148012
- use similar logic from QuickAssistProcessor in QuickFixProcessor when problem is IProblem.ParsingErrorInsertToComplete
- add new test to QuickFixTest1d8
Adds quick fix to assign an expression to a local or field as per the current quick assist.
See original bug or new test.
> Fix Bug 148012 - add quick fix to assign statement to local variable

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/makestatic/InstanceUsageRewriter.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodWithInvocationOnNewObject/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodWithInvocationOnNewObject/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
The "Make Static" refactoring currently adds a "this" parameter to the method in cases in which it is actually not necessary. This is particularly the case the body of the method to be refactored contains invocations of methods on a newly instantiated object. The according logic erroneously considers such a method invocation as a reason to add a parameter.
With this fix, the identification of whether a parameter needs to be added to the method depends on whether the logic calculating an actual change to the method body is actually applied. An according regression test for the behavior is added.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1044
It is easiest to test with either the example provided as a regression test within this PR or by applying the "Make Static" …
> Ensure "Make Static" refactoring only adds parameter if necessary #1044

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/makestatic/ChangeCalculator.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testCallsAroundRefactoredMethod/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testCallsAroundRefactoredMethod/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
The "Make Static" refactoring currently produces overlapping text edits in case there are changes in the source code file containing the refactored method before and after that method. The reason is that the calls to the refactored method are wrapped into a single MultiTextEdit whose scope is then overlapping with the TextEdit for the refactored method itself.
With this fix, the changes to callers of the refactored method are treated as individual TextEdits rather than one MultiTextEdit, so that none of the generated text edits have pairwise overlaps. An according regression test for the behavior is added.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1045
Take any class, in which you want to refactor an instance method to a static method which has callers in that class above …
> Avoid "overlapping text edits" in "Make Static" refactoring #1045

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/makestatic/ChangeCalculator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/ChangeSignatureProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/util/JavadocUtil.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testJavaDocInsertBetweenExistingTags/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testJavaDocInsertBetweenExistingTags/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testJavaDocShuffledTagsWithGenerics/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testJavaDocShuffledTagsWithGenerics/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
This change improves the Javadoc generation behavior of the "Make Static" refactoring and aligns it with other refactorings such as "Change Method Signature". It ensures that generated parameter tags are inserted at proper positions within an existing Javadoc comment.
<s>This change improves the Javadoc generation behavior of the "Make Static" refactoring and aligns it with other refactorings such as "Change Method Signature". This includes (1) adding a "TODO" to added parameter tags and (2) inserting parameter tags at proper positions within an existing Javadoc comment.</s>
The tag for the parameter itself is added as the first parameter tag, following any author or version tags. The tags for potential type parameters are added as the last parameter tags, preceding any other tags than …
> Improve Javadoc generated by "Make Static" refactoring #1043

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/makestatic/InstanceUsageRewriter.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClass/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClass/in/Other.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClass/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClass/out/Other.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClassExtendingRefactoredClass/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInAnonymousClassExtendingRefactoredClass/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInNestedAnonymousClass/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInNestedAnonymousClass/in/Other.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInNestedAnonymousClass/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testMethodCallInNestedAnonymousClass/out/Other.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
The "Make Static" refactoring erroneously interprets a method call within an anonymous class inside the refactored method as a call on `this` and thus changes the method invocation to be performed on the added input parameter of the method. This is (1) semantically incorrect and (2) leads to compile errors if the type of the added parameter does not provide the method.
With this fix, the identification of whether a method invocation is performed on the `this` object of the method to be refactored and not some instance of an anonymous inner class inside that method is corrected. For three different scenarios (anonymous class extending outer class, anonymous class extending other class, and nested anonymous classes), regression tests are added.
Fixes …
> Correct "Make Static" refactoring behavior for anonymous classes #1083

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1041
> [22] Allow JDT to target Java 22 in compiler preferences

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AddMissingMethodDeclarationFixCore.java
When the type declaration ancestor of the method reference to be created cannot be found, don't suggest the AddMissingMethodDeclarationFixCore proposal.
Use the scenario described in the issue.
> Fix NPE when type declaration is not found. Fix #1097

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyFiltersActionGroup.java
When modifying the filters of the Callhierarchy we must click on refresh to apply the filters.
Refresh CallHierarchy on FiltersDialog validation
Refresh CallHierarchy on FiltersDialog validation ==> No need to click on refresh anymore
> Refresh CallHierarchy on FiltersDialog validation

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyUI.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1098
> CallHierarchy: fix error when clicking a method that is gone #1098

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fixes #1111
- add new tests to AssistQuickFixTest15
Fixes String concat to text block quick assist to not extraneously add \s characters and to check tab setting.
See original issue or new tests added.
> Fix String concat to text block to properly handle spaces

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/GetterSetterCorrectionBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/JavadocTagsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/SerialVersionBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnInitializedFinalFieldBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/VarargsWarningsBaseSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/GetterSetterCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/VarargsWarningsSubProcessor.java
Separate core and ui for GetterSetterCorrectionSubProcessor and VarargsWarningsSubProcessor. 
Any UI entrypoint that would access the various code completions and quick fixes should be able to trigger this code.
> Sub processor push down part1

- org.eclipse.jdt.ui/jar in jar loader/org/eclipse/jdt/internal/jarinjarloader/JIJConstants.java
- org.eclipse.jdt.ui/jar in jar loader/org/eclipse/jdt/internal/jarinjarloader/RsrcURLStreamHandler.java
In order to open a JAR file in multi-release mode the URL of the file must be suffixed with `#runtime`.
Currently the `rsrc:` URL handler strips this fragment, which breaks multi-release JARs retrieved through the `rsrc:` protocol.
This PR copies the `#runtime` fragment from the `rsrc:` URL to the URL of the underlying resource.
Closes #1057.
A minimal reproducible example is available at [copernik-eu/bug-reproducibility/eclipse-jar-in-jar](https://github.com/copernik-eu/bug-reproducibility/tree/main/eclipse-jar-in-jar).
I can provide a JUnit test if you point to the right module, where to put it.
> Fix `jar-in-jar-loader` multi-release support

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
The other bundle might not be shutdown yet and would still want that key.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1093
> Don't set preference key of other bundle on shutdown

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/SourceViewerInformationControl.java
Fixes SourceViewerInformationControl not setting new String input content over existing one, causing e.g. code completion proposal preview not being updated with different content if user choses other proposal.
> In any Java file, type for and hit Ctrl+Space to get template proposals.
The list with multiple "for" templates is shown (and also some classes starting with "for"), but selecting any of the template proposals doesn't update proposal preview on the right side.
> Fix SourceViewerInformationControl not updating String input. Fixes #1125

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- fixes #1123
- modify LocalCorrectionsSubProcessor.addInvalidVariableNameProposals() to recognize a duplicate constructor and instead of a rename suggest removal of duplicate constructor
- add new test to LocalCorrectionsQuickFixTest.java
Fixes the quick fix logic when there is a duplicate constructor to not suggest renaming and instead remove the duplicate.
See issue and new test.
> Add quick fix for duplicate constructor that doesn't do rename

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ComparingOnCriteriaCleanUp.java
- fixes #915
- add wildcard support to ComparingOnCriteriaOperation.buildMethod() similar to what was added to buildField()
- add to existing test case in CleanUpTest1d8 for comparator cleanup
Fixes comparator cleanup when involving a wildcard type and creating a method reference.
See issue and new test scenario added.
> Fix exception in use comparator cleanup

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/StubUtility.java
When StubUtility.getMethodComment(etc) is called and passes in an incorrect MethodDeclaration that lacks a return type (for example, when the user has left out the return type incorrectly), the method fails with NPE and blows away the stack. 
This issue is currently replicatable via jdt.ls test suite.
> NPE in StubUtility when generating javadoc for method declaration with no return type

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/JavadocTagsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/ReturnTypeBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/SerialVersionBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnInitializedFinalFieldBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/VarargsWarningsBaseSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/UnInitializedFinalFieldSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/VarargsWarningsSubProcessor.java
The recent pushdown of many SubProcessor / quickfix processors could benefit from more clarity and uniformity in some of the variable names. Several of the abstract methods have parameters like `boolean b` or `Object object`, and several of the extenders are choosing to ignore those parameters and instead pass in their own hard-coded values when constructing the proposals. 
This should be cleaned up ASAP before consumers get a chance to extend or interact with these (admittedly, internal) classes.
> Cleanup in all -BaseSubProcessor classes and extenders

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/ImporterTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ActionUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/model/JavaModelLabelProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/GotoResourceAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/importer/JDTProjectNatureImportConfigurator.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/importer/ProjectWithJavaResourcesImportConfigurator.java
to use public API instead of type cast.
Failing since I20240130-1800
Java nature and java project are now implemented as separate instances https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1916
> fix ImporterTest.testImportRawJavaProject()

- org.eclipse.jdt.ui/.settings/.api_filters
CleanUpOptions @noextend is not intended to be subclassed by CLIENTS.
> suppress "illegally extends CleanUpOptions"

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/UseSuperTypeProcessor.java
tested with System.gc() behind
ExtractInterfaceTests1d8.testExtractInterfaceFromInterface2()
> SuperTypeRefactoringProcessor: fix deprecated finalize()

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/ChangeCorrectionProposalCore.java
- add missing synchronization for getCurrentChange() which accesses fChange which is created in a synchronized method
- potential fix for #1136
Potentially fixes a BadLocation error thrown by an Extract to local variable refactoring.  There appears to be a timing
issue as debugging and stopping fixes the problem.  There is a method in ChangeCorrectionProposalCore to return the
current change if calculated or null.  The creation of the change is protected by a synchronized method but this one does
not use any synchronization.  Exporting the jdt.core.manipulation plug-in and overriding in the I20240126 build seems to
fix the problem.  In some cases, a UI freeze occurs which might be used to determine the cause of the timing issue.  There
is extra calculation done for extracting and …
> Add missing synchronization for ChangeCorrectionProposalCore

- org.eclipse.jdt.ui.junit.sampleproject/src/main/java/junit/framework/TestResult.java
The type ThreadDeath has been deprecated since version 20 and marked for removal
> fix deprecated ThreadDeath

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/FilteredTypesSelectionDialog.java
The method createImage(ImageDescriptor) from the type ResourceManager is deprecated since version 3.31
> fix deprecated createImage(ImageDescriptor)

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsSubProcessor.java
Code that really should have belonged in ReorgCorrectionBaseSubProcessor when it was created was left in the UI extension, due to an uncertainty over how to handle delegation to other subprocessors. 
Since the time of its creation, other subprocessors have solved that issue by having abstract methods that get the other subprocessors in question, and this behavior can be used in the ReorgCorrectionBaseSubProcessor as well.
> Move some core code into ReorgCorrectionBaseSubProcessor

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fixes #1180
- add new logic to QuickAssistProcessor.getExtractVariableProposal()
- add new tests to AssistQuickFixTest
Suppresses extract to constant quick assist proposals unless the selected expression is all static and final.
> Don't offer extract to constant unless expression is final and static

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/base/RefactoringStatusCodes.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/RefactoringCorrectionProposalCore.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- fixes #1185
- don't run checkFinalConditions() from QuickAssistProcessor to see if extract to local variable proposals are valid
- override the preview for extract to local variable and extract to local variable (replace all occurrences) so they just display a message instead of creating the change
- fix ExtractTempRefactoring.checkFinalConditions() to recognize an invalid change in which case add an error status with a code that is RefactoringStatus.INFO
- modify RefactoringCorrectionProposalCore to recognize an error refactoring status in which case create a dummy edit and if the INFO code is found, then also create a log entry to note that the extraction will not occur
- fix AssistQuickFixTest tests proposal counts
Fixes UI freezes in quick assist processor due to Extract to local …
> Fix UI freeze due to extract to local computations

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ChangeSignatureTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/DeleteTest.java
Enabled some disabled tests which aren't in broken state anymore.
https://github.com/eclipse-platform/eclipse.platform/issues/525
- [x ] I have thoroughly tested my changes
- [ x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)
> Enabled tests

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/rename/RippleMethodFinder2.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1192
> fix endless loop in RippleMethodFinder2.UnionFind.find(IType) #1192

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d7.java
- fixes #1194
- add logic to ExtractTempRefactoring to determine if dealing with autocloseable expression taken from resource expression in try with resources in which case place the new variable declaration in the resource expressions
- add new tests to AssistQuickFixTest1d7
Fixes bug 401089: https://bugs.eclipse.org/bugs/show_bug.cgi?id=401089 which notes that extracting an autocloseable local from a set of resource expressions within a try-with-resources statement should put the new declaration in the resources
> Fix extract local for autocloseable expression in try with resources

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/ChainCompletionTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ChainCompletionProposalComputer.java
- More generally, handling of improper values in certain cases where the JDT UI preference initialization fails to set preferences
- Fixes #230
> Handle potential NumberFormatException in chain completion settings.

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestSuiteElement.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestViewer.java
We revert the changes from:
#946
#1022
Since there are other regressions we see, such as showing the string comparison dialog not working.
> Revert workaround for #945, as it causes problems in the JUnit view

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #1209
- fix LambdaExpressionsFixCore to create a QualifiedName reference rather than a QualifiedType
- add new tests to CleanUpTest1d8 and AssistQuickFixTest1d8
Fixes lambda quick assist and cleanup to not cause an exception creating the lambda body.
> Fix lambda cleanup/quick assist when static field is returned

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/launcher/AdvancedJUnitLaunchConfigurationDelegateTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/launcher/JUnitLauncherTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/launcher/MockLaunchConfig.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/AutomatedSuite.java
Currently, when running tests from a source folder with JUnit 5, all tests that share a package with those packages in the selected source folder will be run (see #920). This attempts to fix this by enumerating all tests as suggested in #920.
I don't know if JDT uses a mocking framework so I mocked the needed classes by hand.
I've added a test case. I'm not sure if that is sufficient.
Edit: I've added a few more tests so I've set the checkmark for through testing.
> Correct enumeration of tests when running tests from a folder (#920)

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java
Fixes test fail `HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy. No method visit(EitherOrMultiPattern) was found in HierarchicalASTVisitor.`
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2011
> HierarchicalASTVisitor update after JDT core API change

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- modify PatternMatchingForInstanceofFixCore to recognize when an instanceof expression is used in an infix expression but not with conditional and (&&) or conditional or (||)
- modify tests in CleanUpTest16
- fixes #1218
Prevents the pattern matching instanceof cleanup from changing the code when the instanceof expression is used in an infix expression that doesn't use the conditional-and or conditional-or.  Such a sequence is invalid.
See issue or test changes in CleanUpTest16
> Don't create pattern instanceof expression for non-conditional infix

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnwrapNewArrayOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- fixes #1213
- add logic to UnwrapNewArrayOperation to look for non-NLS tags in which case just remove the array specifier and its braces to preserve non-NLS markers
- add new test to CleanUpTest1d5
Fixes the remove unnecessary array creation cleanup to not remove non-NLS markers.
> Fix remove unnecessary array cleanup to handle non-NLS markers

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest16.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaTextMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaTextMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/RecordAccessorCompletionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/CompletionProposalCollector.java
Enhances code completion to propose adding a record accessor in addition to a method.
> Record accessor completion proposal

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringBufferFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- don't use NLSUtil.scanCurrentLine(cu) which scans the entire compilation unit to find one line; instead get the text of the line and use NLSScanner.scan(String)
- add code in StringConcatToTextBlockFixCore when looking for comments to also ensure that nls prefix is found before doing any NLS checking
- fixes #1237
Fixes performance lag in String to text block conversions via cleanup or quick assist.
See issue example which converts a large file (CleanUpTest.java) which also has line comments at the end of every
concatenated string.
> Fix performance lag for String to text block cleanups/fixes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/core/manipulation/search/ExceptionOccurrencesFinder.java
when @throws in javadoc doesn't have anything after it.
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1241
Shows the no exception instead:
> ExceptionOccurrencesFinder: fix IndexOutOfBoundsException #1241

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore.escapeTrailingWhitespace() method
- add new test to CleanUpTest15
- fixes #1240
Fixes problems with converting to text block when text ends with tab and has other white-space prior to that.
See original issue or new test.
> Fix trailing tab logic for converting to Text Block

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to look at resultant buffer before adding final block quotes and if last 1 or 2 characters are un-escaped quotes, replace them with escaped quotes
- add new scenarios to CleanUpTest15
- fixes #1238
Fixes conversion to text block when the string ends in quotes.
See issue or new test changes.
> Fix text block conversion when ending in quotes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionAndMethodRefFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- modify ConvertLambdaToMethodReferenceFixCore, LambdaExpressionsFixCore, and LambdaExpressionAndMethodRefFixCore when generating method refs to check if the method ref will be a method argument and if that method is overloaded, add a type cast to prevent an ambiguous error
- add new tests to CleanUpTest1d8 and AssistQuickFixTest1d8
- fixes #1047
Fixes lambda cleanups and assists that create method refs to add a cast when needed to avoid a compiler error saying that the call is ambiguous.
See original issue and new tests.
> Fix lambda method ref generation to avoid ambiguous error

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CodeStyleFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #1211
- add check for a field reference in a lambda in a field initializer in which case, skip
Fixes code error caused by "remove this" cleanup removing a this specifier for a forward referenced field in a lambda expression.
> Fix removal of this cleanup to avoid forward field refs in lambdas

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OneIfRatherThanDuplicateBlocksThatFallThroughFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- fixes #1200
- add new PatternInstanceof logic to OneIfRatherThanDuplicateBlocksThatFallThroughFixCore
- add new test to CleanUpTest16
Fixes single if cleanup to handle case of pattern instanceof expressions.
> Fix one if cleanup to watch for PatternInstanceof nodes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- fixes #1198
Adds check to lambda cleanup to not generate lambda when interface method is generic.
> Fix lambda cleanup to not generate if interface method is generic

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SplitTryResourceFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- add new SplitTryResourceFixCore.java
- add new logic to QuickAssistProcessor
- add new tests to AssistQuickFixTest1d8
- fixes #1220
Adds new quick assist to split up resources in try-with-resources into an inner try-with-resources.
> Add quick assist for splitting try-with-resources

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to handle case where all lines start with white-space and the last line doesn't end in newline so that the text block end-quotes get put on a separate line and the last text is a continuation character so that proper indentation occurs
- add new tests to CleanUpTest15 and AssistQuickFixTest15
- fixes #1240
Fixes indentation when all lines of text block start with white-space and last line doesn't end with new-line.
> Fix string to text block indentation when last line has no newline

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to recognize when appending a concatenated string via StringBuffer/StringBuilder append() and treat each StringLiteral as if they were appended separately
- fix error handling when append is invalid (e.g. uses a variable name)
- fix string name allocation to recognize body declaration boundaries and reset excluded name list
- add new test to CleanUpTest15
- fixes #1238
Fixes StringBuffer/StringBuilder to text block clean-up to work properly when a string concatenation is being appended and also
fixes the code to cleanly bail when conditions aren't correct.
See original issue or new test scenario.
> Fix StringBuffer/StringBuilder to text block when concat string appended

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Fix issue with string concat to text block whereby name collision occurs with other local variable.
See issue or new test scenario added.
> Fix name collision in string concat to text block cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore.escapeTrailingWhitespace()
- add new test to CleanupTest15
- fixes #1240
Fixes another white-space issue with string concat to text block conversion of test suite.
See issue or new test scenario added.
> Fix StringConcatToTextBlockFixCore escape logic when string is size 1

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringBuffer/StringBuilder to text block support when original code has one or more redundant constructors preceding the first append
- fix StringBuffer/StringBuilder look-ahead to next constructor statement logic so it doesn't change next constructor to VariableDeclarationStatement if the initial declaration never gets removed (i.e. first concenatation was invalid for conversion)
- add new test scenarios to CleanUpTest15
- fixes #1238
Fixes more edge-case scenarios discovered by converting test suite to use text blocks.
See issue or new test scenarios.
> Fix string concat to text block handling of redundant constructors

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore.StringBufferFinder() to fail if a StringBuffer/StringBuilder constructor is used and isn't passed a StringLiteral or a NumberLiteral or an InfixExpression of StringLiterals concatenated
Fixes StringBuffer to text block when a non-String-literal is passed to constructor.
> Fix StringBuffer to text block clean-up when constructed with String

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix regression whereby a future constructor assignment of a variable needs to be converted to a VariableDeclarationStatement due to the original declaration is removed but the future assignment needs to be kept
- fixes #1238
Fixes regression.
See issue or new tests added.
> Fix regression in StringBuffer to text block cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Adds support to text block clean-up for using chained StringBuffer/StringBuilder append() calls.
> Add chained append support to text block clean-up

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to not convert to text block if any of the concatenated elements have non-empty line comments or block comments
- also fix the last line of a text block when formed from a concatenation that ends in a space or tab-character as it still requires escaping
- fixes #1273
Does not perform string concat to text block clean-up if lines in the concat have block comments or non-empty line comments.
> Do not remove comments for string concat to text block

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- add new test to CleanUpTest15
- fixes #1240
Fixes string concat to text block so that escaped single quotes are represented by single quotes.
See new test or see issue.
> Fix string concat to text block so it does not escape single quotes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- fix StringConcatToTextBlockFixCore.StringConcatFinder when visiting an InfixExpression, ensure it is not considered part of another InfixExpression implying that all items are not StringLiterals
- add new test to AssistQuickFixTest15
- fixes #1284
Makes quick assist consistent with clean-up with regards to not converting a string concatenation if it involves a non-StringLiteral.
See original issue or new test.
> Do not offer string concat to text block if a variable is used

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- fixes #1261
Re-instates the split try-with-resources tests now that jdt.core fixes are in nightly build.
See tests that are now enabled.
> Re-enable split try-with-resources tests now that indenting is fixed

- org.eclipse.jdt.ui.unittest.junit/META-INF/MANIFEST.MF
Fix version-ranges to have exclusive upper-bounds
> Fix version-ranges to have exclusive upper-bounds

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestSuiteElement.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestViewer.java
Don't show children for JUnit 5 `@TestTemplate` tests that ran only once
When running JUnit 5 `@TestTemplate` tests, extra test suites are shown in the JUnit view to represent the tests in the template. Those suites introduce unnecessary noise when the template contains only one test - e.g. when repeating tests that failed.
This change adjusts TestSuiteElement.getChildren(), pruning each TestSuiteElement that has a single TestCaseElement child that is also a dynamic test.
```
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.Assume;
import org.junit.jupiter.api.MethodOrderer.MethodName;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
@TestMethodOrder(MethodName.class)
public class …
```
> Don't show children for JUnit 5 @TestTemplate tests that ran only once

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/JavaElementLinks.java
Removes unnecessary log message when interrupted while JavaElementLinks code was waiting for CSS fragments lock (performed for purposes of applying new Javadoc styling enhancements #1074 ).
I was not able to reproduce the reported issue so I can't give exact steps/flow to test the fix. Issue description is however right in saying:
> while editing or navigating inside Java file, mouse hover request may be cancelled because of some user actions that make the request obsolete.
> Do not log locking CSS fragments cache for read was interrupted #1294

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/flow/FlowAnalyzer.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/flow/InOutFlowAnalyzer.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/flow/InputFlowAnalyzer.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/flow/ReturnFlowInfo.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- add YieldStatement support to FlowAnalyzer
- add YieldStatement support to InOutFlowAnalyzer that marks an exposed yield statement (parent SwitchExpression is not part of selected nodes) the same as a return value
- add code to ExtractMethodRefactoring to change exposed yield statements that are moved to extracted method into return statements and replace the extracted code with a yield statement that calls the new method
- in the case of non-exposed yield statements, leave them alone as the whole SwitchExpression gets moved into the new method
- fixes #1286
Fixes extract method to handle the case where a subset of statements within a Switch Expression are moved and
they have yield statements.
See issue.
> Fix extraction of yield statements into method

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaElementLabelComposerCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/JavaElementLinks.java
Fixing 2 (lets call them) corner cases when types parameters coloring was not working as expected.
- Missing coloring (for classes/interfaces from other compilation unit) ![missing_types_coloring](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/36334098/bbd54a06-7119-4c07-ba06-dc7727f54c4e)
- Unwanted coloring of type label(s) outside of generic signature (diamond brackets) ![unwanted_types_coloring](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/36334098/cc198d2a-af2d-4a52-b65e-898347b7822a)
After fix
- ![missing_types_coloring_fix](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/36334098/dcac0c90-1597-4666-b94c-d631a16d368e)
- ![unwanted_types_coloring_fix](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/36334098/b84490e4-3aaa-4757-87fc-51951d8d7590)
- have Javadoc …
> Fix type parameters coloring corner cases (#1073 #1074)

- .mvn/extensions.xml
Unifies the maven extension version with the plugin version configured in the parent
Build still works
> Build with tycho 4.0.7

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/AssignToVariableAssistProposalCore.java
- This permits clients to modify the behaviour prior to computation
- UnresolvedElementsBaseSubProcessor (abstract) creates the "new variable" proposal and only delegates it to implementors, so the setter is required to change behaviour and insert 'final' modifier
> Add setter for fAddFinal field.

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/AssignToVariableAssistProposalCore.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/NewVariableCorrectionProposalCore.java
- Remove setAddFinal from AssignToVariableAssistProposalCore and place it in NewVariableCorrectionProposalCore
This reverts commit 14c5480d51e36a79b37142f89e71de440b08fc9e.
See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1324 for the change this is addressing.
> Place setAddFinal in the correct proposal.

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUp.java
- treat variable declarations that have no initializer the same as ones that do for the first declaration that gets overridden
- fixes #1330
See issue.
See new test or bug or issue.
> Bug 572440 - combine declaration and overridden assignment

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
- fixes #1328
Adds an error message when Java project has module descriptor and user attempts to create a class in the default package.
Create a Java project with module-info.java file.  Attempt to create a new class using wizard where package is not specified.
> Mandate a package name in NewClassWizard when project is a module

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
Fixes a warning about unused local variable
> Remove unused local variable.

- org.eclipse.jdt.ui.unittest.junit/plugin.xml
- org.eclipse.jdt.ui.unittest.junit/src/org/eclipse/jdt/ui/unittest/junit/internal/launcher/JUnitTabGroup.java
Enables the the prototype support for Generic Test view - JUnit.
Majority of the tabs are already providing labels support for the prototype tab.
Create a prototype of type "JUnit Test (generic Test view)" and link existing JUnit test launch of same type, link them and  see that e.g. VM args from template are appiled to the test launch.
> Enable prototype support for Generic Test view - JUnit

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
Rewrites ChangeValueChecker.findFunctionDefinition() method to not use type hierarchy which can take a very long time to complete and instead use SearchEngine when needed.
See issue.
> Fix extract temp refactoring freezes

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/MarkOccurrenceTest.java
Test is unstable (e.g. failed in tonight's I-build https://download.eclipse.org/eclipse/downloads/drops4/I20240421-1800/testresults/html/org.eclipse.jdt.text.tests_ep432I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html ).
This change replaces silent fails with proper exception reporting.
Test should continue to work as expected but whenever it randomly fails there will hopefully be better message to give hints what to look at.
> Improve "silent" fails in MarkOccurrenceTest

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1349
> [23] Allow JDT to target Java 23 in compiler preferences

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/browser/BrowserTextAccessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/javadoc/SignatureStylingMenuToolbarAction.java
Regression from cbc03c25f6059c774d8766bd7b02489c9df53acf / https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/941 
The code moved from JavadocContentAccess2 to CoreJavadocAccessImpl changed dt/dd tags to ul/li tag pairs, and that broke javadoc alignment.
This commit restores original tag pairs used for javadoc formatting.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1346
> Javadoc sections misaligned

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- expose some text block logic from StringConcatToTextBlockFixCore
- change ConvertToMessageFormatFixCore to use a text block for JVM 15 and above
- add new tests to AssistQuickFixTest15
- fixes #1311
Modifies the string concat to MessageFormat quick assist to use a text block on JVM 15 or above.
See issue and new tests.
> Fix string concat to MessageFormat to use text block when possible

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- change ConvertToStringFormatFixCore to use a text block for JVM 15 and above
- add new tests to AssistQuickFixTest15
- fixes #1311
Fixes string concat to String.format quick fix to use a text block if JVM 15 or above.
> Fix string concat to String.format to use text block when possible

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- for MessageFormat, put parentheses in single quotes and look for open/closed parentheses one after another
- for String.format, escape % as %%
- modify tests in AssistQuickFixTest15
- fixes #1366
Escapes certain characters when converting string concat to MessageFormat or String.format as part of a quick assist.
See new tests.
> Escape specifiers when converting to MessageFormat or String.format

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/OverriddenAssignmentCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OverriddenAssignmentFixCore.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/UnnecessaryCodeTabPage.java
- create new OverriddenAssignmentCleanUpCore and OverriddenAssignmentFixCore classes in jdt.core.manipulation
- modify OverriddenAssignmentCleanUp to use core class
- remove old OverriddenAssignmentCleanUp
- fixes #1370
Refactors OverriddenAssignmentCleanUp to jdt.core.manipulation.
Perform an overridden assignment cleanup on code that applies.
> Refactor OverriddenAssignmentCleanUp to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/ElseIfCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ElseIfFixCore.java
- org.eclipse.jdt.ui.tests/performance/org/eclipse/jdt/ui/tests/performance/views/CleanUpPerfTest.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CodeStyleTabPage.java
- create new ElseIfCleanUpCore and ElseIfFixCore classes
- modify CodeStyleTabPage, CleanUpPerfTest, and plugin.xml to refer to new core clean-up
- fixes #1373
Refactors ElseIfCleanUp to jdt.core.manipulation for use by jdt.ls.
Set up project to do appropriate else if cleanup set by CodeStyleTabPage of the clean-up preferences dialog.
> Refactor ElseIfCleanUp to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1360_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1360_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1360_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1360_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1360_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1360_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression5.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression6.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression7.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression5.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression6.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression7.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/warning_in/TestSync1.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/AbstractJunit4SelectionTestCase.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTestSetup.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests16.java
- modify CallInliner to add logic to add a synchronized block if the method to inline is synchronized
- issue warning if synchronized block cannot be substituted for expression call
- add new tests to InlineMethodTests and InlineMethodTests16
- fixes #1360
Adds support for synchronized methods being inlined.
> Fix inline method to handle a synchronized input method

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/ChainFinder.java
Add a new constructor to pass in the token so that the token will be used when matching the chains. This helps to better control how much chains are produced by using the text that is already typed in an editor as the token. This helps to provide better chains selection without increasing the number of chains to produce for JDT.LS. The existing constructor will preserve the current behavior uneffected.
This new behavior can be only tested with JDT.LS PR https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2835
> Add support to filter chain by passing the in the token

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- for a single line concat, don't use a text block when converting a string concat to MessageFormat or String.format in ConvertToMessageFormatFixCore and ConvertToStringFormatFixCore
- add new tests to AssistQuickFixTest15
- fixes #1384
See title.
> Don't use text block for MessageFormat/String.format if one line concat

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1351 seems to have fixed an inadvertent change to the value of some constants in a file that was being abstracted out for subclassing. 
It's clear that the abstraction process was incomplete and only appeared complete because of these changed constants. The reversion of those constants to their historical value has revealed that jdt.ls cannot override the behavior as expected. 
In an attempt to allow jdt.ls to override these values, this PR will make getters for the 6 values, which subclasses may override. All references to those constants in this file can be changed to make use of the getters instead. 
This should allow jdt.ls more flexibility in overriding these values and using different formatting as they require. 
This commit should …
> Make CoreJavadocAccessImpl more extendable for jdt.ls

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/OpenCallHierarchyHyperlinkDetector.java
Adds 'Open Call Hierarchy' item to the list of "hyperlinks" (actions offered on CTRL + mouse hover) for Java types (classes/enums/records) as well.
CTRL + mouse hover over various elements in opened editor, 'Open Call Hierarchy' should be offered for elements for which call hierarchy can be actually shown.
> Add 'Open Call Hierarchy' hyperlink for type elements too. Fixes #1231

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiCatchCleanUpCore.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/JavaFeatureTabPage.java
- fixes #1382
See title.
Clean up code that is eligible for a multi-catch cleanup.
> Refactor MultiCatchCleanUp to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceAnalyzer.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1358_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1358_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1358_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1358_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/invalid/Test_issue_1358_1.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- add new checkAccessCompatible() method to SourceProvider that checks if code from declaration can be moved to target without causing an access violation
- add new AccessVisitor to SourceAnalyzer to log non-public accesses (private, package-private, and protected)
- add call to checkAccessCompatible() in CallInliner
- fixes #1358
Fixes inline method to consider the various access modifiers of members being accessed by the code to be inlined and to fail if there would be access violations from performing the inline.
See issue and new tests.
> Fix inline method to check access modifiers of inlined code

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/invalidSelection/A_testIssue1356_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/invalidSelection/A_testIssue1356_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- fix ExtractMethodAnalyzer to add a new check if selected statements to extract contain a final field assignment and fail if this is true
- add new tests to ExtractMethodTests
- fixes #1356
Does not allow final field initialization statements to be moved as part of an extract method refactoring.
> Don't allow extracting a final field assignment to a new method

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/DocumentAdapter.java
This change adds a lock object to `Document` use in `DocumentAdapter`, in order to prevent concurrent text buffer access. See: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1059
> Add lock object to fDocument in DocumentAdapter.initialize()

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test501.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test502.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test509.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test518.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_in/A_testIssue1357_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_in/A_testIssue1357_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_out/A_testIssue1357_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_out/A_testIssue1357_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/wiki_out/A_test2001.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- modify ExtractMethodRefactoring.createMethodBody() to check all locals that needed to be created in new method to see if the old declaration is still needed (i.e. referenced outside of the selected statements) and if not, remove the original declaration
- modify all ExtractMethodTests where the locals are left behind and not used elsewhere
- add new tests to ExtractMethodTests
- fixes #1357
See title.
See original issue or modified tests or new tests.
> Remove locals moved via extract method if they aren't used elsewhere

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MemberVisibilityAdjustor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test70/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test70/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
- fix MemberVisibilityAdjustor.thresholdTypeToMethod() so that when two classes are in same compilation unit but are separate, use a threshold of default (null) instead of private
- add new test to MoveInstanceMethodTests
- fixes #1300
See title.
See original issue or new test.
> Fix move of method with private method call when classes in same CU

- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/launcher/LaunchErrorStatusHandler.java
This prevents the dialogs to appear behind the possible opened progress dialog (or any other modal dialog).
See https://github.com/eclipse-platform/eclipse.platform/issues/1373
> Use proper shell for modal dialogs

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyLifeCycle.java
partial revert of fc6a25a6a1d46627eae34f4aeab98cafb71a5f70
The used firePostSelectionChanged may run events that try to edit java model.
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1408
Since "Increase JavaModelCache #1929" its not a performance impact anymore anyway, since the jdt.core typically keeps a cached JavaModel of the TypeHierarchy after computing it anyway and does not need to compute it in ui again.
> Do not use runReadOnly during TypeHierarchyViewPart.updateViewers #1408

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/reorg/ReorgPolicyFactory.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail22/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail22/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
- fix ReorgPolicyFactory.MoveSubCuElementsPolicy.validateDestination() to restrict moving an interface member to anything other than another interface
- add new test to MoveMemberTests
- fixes #1299
See title.
See original issue or new test.
> Only allow moving an interface member to another interface

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/PasteAction.java
After introducing implicit types via
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2066 the snippet that contains only main() method is recognized as
ImplicitTypeDeclaration that does not inherit AbstractTypeDeclaration but common super class AbstractUnnamedTypeDeclaration.
Make sure we don't fail with CCE and don't generate extra main method that wraps around pasted main method.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1414
> Fix for pasting snippet with main method to Package Explorer

- org.eclipse.jdt.core.manipulation/forceQualifierUpdate.txt
- org.eclipse.jdt.junit.core/forceQualifierUpdate.txt
- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2044
> Force signing of split package bundles to use new certificate

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test71/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test71/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test72/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test72/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test75/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test75/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
- fix MoveInstanceMethodProcessor to handle the cases where the method to move references a member class
- add new tests to MoveInstanceMethodTests
- fixes #1301
See commit.
> Fix move instance method when inner class is referenced

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- add null check for deprecated method quickfix
- fixes #1429
See title.
See issue.
> Fix NPE in QuickFixProcessor

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/branch_in/A_test770.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/branch_out/A_test770.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- fix ExtractMethodAnalyzer.canHandleBranches() to not flag a non-labelled break statement if the for loop is included
- add new test to ExtractMethodTests
- fixes #1291
See original issue.
> Fix false error on extraction of for loop contents

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_in/A_test579.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test579.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
> Fix false extract method failure due to local variable access

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- fix ConvertToMessageFormatFixCore and ConvertToStringFormatFixCore to refine the logic for determining when to use a text block vs a single line - logic now only uses text block if there are 3 or more lines used in the concatenation AND the number of string literal characters is greater than 80
- modify existing tests and add new tests to AssistQuickFixTest15
- fixes #1406
See commit message.
> Fix concat to MessageFormat and String.format

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test79/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test79/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
- fix MoveInstanceMethodProcessor.createMethodBody() to perform any needed adjustments to field modifiers if required by the move
- add new test to MoveInstanceMethodTests
- fixes #1297
Fixes move instance method to check field accesses and modify the access flags of the field if necessary.
> Fix move method to handle field access modifier adjustment

- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.properties
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestRunnerViewPart.java
- fix TestRunnerViewPart.prepareLaunchConfigForRelaunch() to strip the failed first part of a message as we are just rerunning
- also set the ATTR_FAILURES_NAMES to null instead of empty string so when we do failed first again we will create the proper message and do not add the Rerun to start of message as we do this inconsistently (only added after a failed run then rerun)
- fixes #1434
Fixes the console message for a rerun to not have trailing info about failed tests first and makes the message more consistent by not adding Rerun to start of message some times and others not.
See issue.
> Fix Bug 202162 - JUnit messages says failed first but it is not

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression8.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression8.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests16.java
- add check in CallInliner.perform() to see if we are replacing an implicit yield with a non-implicit yield and instead replace with the yield's expression
- add new test to InlineMethodTests16
- fixes #1439
Fixes case where a method returning a single constant is inlined into the case expression of a switch expression.  We don't want to add a yield statement in such a case, just the constant.
> Fix inlining method returning constant into switch expression

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OverriddenAssignmentFixCore.java
- fixes #1454
Fixes possible NPE in OverriddenAssignmentFixCore.moveDown() method.
Test scenario unknown at this time.  Patch was tested by forcing a move down for a variable declaration that is not initialized.
> Fix NPE in OverriddenAssignmentFixCore moveDown method

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MemberVisibilityAdjustor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/in/p1/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/out/p1/Bar.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/out/p1/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInnerToNewTests16.java
- add check in MemberVisibilityAdjustor.rewriteVisibility() to ignore record fields
- add new test to MoveInnerToNewTests16
- fixes #1419
Fixes issue.
> Fix move of record to new file refactoring when component accessed

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AbstractAnnotateAssistTests.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/736
> AbstractAnnotateAssistTests: more information on NPE #736

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/NullAnnotationsQuickFixTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
- fix NullAnnotationsRewriteOperations.ParameterAnnotationRewriteOperation to check for a SimpleType with qualified name or a NameQualifiedType and end up with a NameQualifiedType with the new annotation added
- add new tests to NullAnnotationsQuickFixTest
- fixes #1462
Fixes the quick fix to change a parameter to add nullable annotation so that if the parameter type is qualified, it creates or modifies a NameQualifiedType reference and adds the annotation before the simple name (e.g. `int foo(java.io @Nullable PrintStream) {...
`
> Fix adding null annotation to qualified type of parameter

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
- fix CoreJavadocAccessImpl to properly handle text elements embedded in inlined return statement
- fixes #1464 in conjunction with jdt.core fix
Fixes inline return output to not clip white-space from text elements.
See issue.
> Fix inlined return message to not clip white-space

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AbstractAnnotateAssistTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d5.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d8.java
addresses the ClassCastException
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/736
> AnnotateAssistTest1d8 test failed

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest14.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- modify LocalCorrectionsSubProcessor.createMissingDefaultProposal() to add an additional proposal to add a default label if JVM >= 14 and no other statements exist in switch
- modify test in QuickFixTest14
- fixes #1459
Adds an additional quick fix proposal for an empty switch when Java >= 14 is used to add an empty block default label.
> Allow optional default case label if switch missing all statements

- Jenkinsfile
Should reduce the amount of timeouting builds like https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1479/ .
Builds no longer timeout on Jenkins
> Increase Jenkins timeout to 60 minutes

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/nested_in/A_test655.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/nested_out/A_test655.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- add new findFieldReferencesForType() method to ExtractMethodAnalyzer to find field references in the inner type where selection is made
- add new logic to ExtractMethodRefactoring to recognize a move to an outer class where fields are referenced in inner in which case pass an extra parameter of the inner type and qualify any field references using this extra parameter
- add new test to ExtractMethodTests
- fixes #1458
Fixes extracting from an inner class to an outer class method.
> Add support for extracting method to outer class

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposalCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeMismatchQuickFixTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposal.java
Addresses https://github.com/redhat-developer/vscode-java/issues/3040
Get quickfix for a constructor invocation that does not match the type of the variable it's being assigned to
> Add quickfix to suggest types for constructor type mismatch

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/StaticInnerClassCleanUpCore.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/PerformanceTabPage.java
- move StaticInnerClassCleanUp to StaticInnerClassCleanUpCore in jdt.core.manipulation
- fixes #1492
See title.
Run the jdt.ui cleanup tests.
> Refactor StaticInnerClassCleanUp to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantSemicolonsCleanUpCore.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/UnnecessaryCodeTabPage.java
- refactor and rename to RedundantSemicolonsCleanUpCore
- fixes #1494
See title.
Run jdt.ui cleanup tests.
> Refactor RedundantSemicolonsCleanUp to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDocSnippetStringEvaluator.java
- fix CoreJavaDocSnippetStringEvaluator.getString() to convert < and > to &lt; and &gt;, respectively
- fixes #1496
Fixes Javadoc hover so type parameters show up in a snippet.
See issue.
> Fix Javadoc hover for snippets to show type parameters

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/IJavaDocTagConstants.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/SpellCheckIterator.java
- revert previous fix for param tag spelling errors as it is no longer needed
- add logic to recognize an in-line code or see tag and skip tokens in SpellCheckIterator until closing bracket of in-line tag
- fixes #1502
Fixes spell checking not to flag items within an inlined code tag or inlined see tag.
See issue.
> Do not flag spelling errors in Javadoc code or link tags

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditorInputFactory.java
To work around IllegalStateException "Its not allow to modify JavaModel during ReadOnly action"
As IJavaElement.exists() sometimes updates the classpath during eclipse start and i don't know how to fix that.
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1443
> ClassFileEditorInputFactory: do not use "callReadOnly" #1443

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- Fix UnresolvedElementsBaseSubProcessor.collectTypeProposals() to handle cast expressions and parenthesized cast expressions
- fixes #1318
Fixes the case where a type is missing and used in a cast or parenthesized cast expression.
See issue.
> Suggest import for missing type in a parenthesized cast expression

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
When you add a static method to a **generic** type and add it to the list of content assist favorites you can't use Quick Fix to add the required static import.
Let's say you have a helper class as follows:
```
package content_assist_test;
public class EikesHelper<T>
{
public static void help()
{
}
}
```
Then you configure that static method as a content assist favorite: `content_assist_test.EikesHelper.test`
Then you write a class to test it:
```
public class EikesTest
{
public static void test()
{
help();
}
}
```
The call to the help() method is marked as a compiler error. When you open the Quick Fix menu it looks as follows:
When you execute the Quick Fix a wrong import statement is inserted.
The problem is caused by a small bug in …
> Fix addStaticImportFavoriteProposals for generic types

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
Adds support for enum to the cleanup in charge for refactoring chains of "if else" to switch.
Run the cleanup on code with if else chains or add junit test cases.
> Enum support for if else to switch cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_3.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- add logic to SourceProvider to change static field/method references that don't have a qualifier and collide with field/method names in an inner target class
- fixes #1515
Fixes inlining to an inlined class where there is a static field/method reference with a name that exists in the inner class.  See issue.
> Fix inline method to handle inner class static references

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ProblemNode.java
- org.eclipse.jdt.ui/plugin.properties
- org.eclipse.jdt.ui/plugin.xml
Makes sure that new errors about "Not supported Java version" are sorted with high prio in the Problems view
**Before**
**After**
> Add "Compliance" problems UI support

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test4_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test4_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RenameTempTests.java
- change method above to ignore qualified name references, field accesses, and the original variable declaration for the check
- reinstate RenameTempTests.test4() to work again and not fail
- change warning to error and tweak message
- fixes #1527
See issue.
See issue or test change.
> Tweak RenameLocalVariableProcessor.checkFieldCollision() logic

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- fix ConvertLambdaToMethodReferenceProposalOperation.rewriteAST() method to use type erasure when setting type of method reference
- add new test to AssistQuickFixTest1d8
- fixes #1520
Fixes lambda to method reference quick assist to not add extraneous type parameter.
> Fix lambda to method ref quick assist to not add type parameter

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/cannotMove/testFail18/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
- add new MoveInstanceMethodProcessor.checkOverrideOuterMethod() that checks if a sub-class inner type of the target type calls a method with same name as moved but the method is declared in a different type so an unexpected override will occur
- add new test to MoveInstanceMethodTests
- fixes #1517
See issue.
> Add additional logic to MoveInstanceMethodProcessor

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PluginsNotLoadedTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/MissingTypeCompletionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/TypeCompletionTest.java
- TypeCompletionTest,
- CodeCompletionTest,
- MissingTypeCompletionTest,
- PluginsNotLoadedTest
> Fixed tests failing after requiring minimal 1.8 compliance

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/MethodOverrideTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
- LocalCorrectionsQuickFixTest
- MethodOverrideTest
> Fixed tests failing after requiring minimal 1.8 compliance, part 2

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateToStringTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d5.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AnnotateAssistTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d7.java
- GenerateToStringTest
- AnnotateAssistTest1d5
- AnnotateAssistTest1d8
- AssistQuickFixTest
- AssistQuickFixTest1d7
> Fixed tests failing after requiring minimal 1.8 compliance, part 3

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/VarCleanUpCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest11.java
- fix VarCleanUpCore visitor maybeUserVar() method to return false for a method reference initializer
- add new test to CleanUpTest11
- fixes #1524
See issue.
> Fix local var cleanup to avoid method references

- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractInterface/test108/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination_out/A_test1059.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination_out/A_test1060.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineConstant/canInline17/test0/out/C.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test37_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test38_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test39_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test46/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test47/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test51/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test52/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test53/out/A.java
- PullUpTests
- InlineTempTests (all except test31())
- InlineConstantTests1d7
- ExtractMethodTests
- ExtractInterfaceTests
> Fixed tests failing after requiring minimal 1.8 compliance, part 4

- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail19/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail19/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail21/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail21/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
- remove testFail19() and testFail21() tests which assume static methods in interfaces are forbidden which they are not in 1.8
See title.
Run MoveMembersTest.
> Fix MoveMembersTest failures due to moving to Java 1.8 as min version

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ModifierCorrectionsQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ReturnTypeQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeMismatchQuickFixTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest.java
- UnresolvedMethodsQuickFixTest
- TypeMismatchQuickFixTests
- ReturnTypeQuickFixTest
- ModifierCorrectionsQuickFixTest
> Fixed tests failing after requiring minimal 1.8 compliance, part 5

- org.eclipse.jdt.ui.tests.refactoring/resources/InlineConstant/canInline/test29/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline17/A_test0_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/AddImportTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/BindingsNameTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/JavaElementPropertyTesterTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/OverrideTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateHashCodeEqualsTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest1d7.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpStressTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d6.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/JavadocQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ModifierCorrectionsQuickFixTest1d7.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixEnablementTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeParameterMismatchTest.java
- AddImportTest
- BindingsNameTest
- JavaElementPropertyTesterTest
- OverrideTest
- GenerateHashCodeEqualsTest
- AdvancedQuickAssistTest
- AdvancedQuickAssistTest1d7
- AssistQuickFixTest1d8
- CleanUpStressTest
- CleanUpTest1d5
- CleanUpTest1d6
- JavadocQuickFixTest
- ModifierCorrectionsQuickFixTest1d7
- QuickFixEnablementTest
- TypeParameterMismatchTest
- InlineConstantTests
- InlineTempTests1d7
Muted test failure in InlineTempTests.test31() and created https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1552 for that, it is is a bug in current implementation.
> Fixed tests failing after requiring minimal 1.8 compliance, part 6

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PluginsNotLoadedTest.java
Follow up from
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2536. After switching to minimal 1.8 project compliance in JDT, test `PluginsNotLoadedTest.pluginsNotLoaded` fails complaining about loaded org.eclipse.jdt.junit bundle.
See
https://download.eclipse.org/eclipse/downloads/drops4/I20240725-1800/testresults/html/org.eclipse.jdt.text.tests_ep433I-unit-cen64-gtk3-java22_linux.gtk.x86_64_22.html
Interestingly, it doesn't fail on both Mac platforms, but see below.
While debugging (break point at
`org.eclipse.jdt.internal.junit.ui.JUnitPlugin.start(BundleContext)`) one can see that the class is loaded at
`org.eclipse.jdt.text.tests.MarkOccurrenceTest.markMethodOccurrences()` test, which, surprisingly ... opens Java editor on `junit.framework.TestCase` class and that one tries …
> PluginsNotLoadedTest fails complaining about loaded o.e.jdt.junit bundle

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore to allow conversion if the StringBuffer/StringBuilder is passed to a method as a String or CharSequence argument, even if no toString() call is made
- add new tests to CleanUpTest15 and AssistQuickFixTest15
- fixes #1554
See issue or commit comment.
See new tests or issue.
> Fix StringBuffer to text block to allow passing as string argument

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2775
> Enable test that was disabled because of JDT core bug

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineConstantRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/AdvancedQuickAssistProcessor.java
- flag being used to determine this is no longer the only thing that needs to be checked so disable using it temporarily
- fixes #1565
See issue.
See issue.
> Disable code that determines if method cast is required

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposalCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeMismatchQuickFixTests.java
Fixes #1558
The old implementation would propose replacing the return type with erasure of the type parameter if the compliance was set pre 1.5. If the compliance was 1.5 or later, it would propose replacing the return type with the type parameter as it appears in the declaration of the method being overridden.
Instead, these are now two separate entries which may be generated:
1. **Replace the return type with the erasure of the type parameter**
This entry is only generated if it is valid to use the erasure for the return type. Specifically, if the method declares the type parameters of the method being overriden, and one of type variables has an upper bound that is a parameterized type, then using the type erasure of that variable in place of the variable is not valid, since the type …
> Fix "fix return type" quickfix for type param return type

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
Leverage the new return-type of
JavaCore.getAllJavaSourceVersionsSupportedByCompiler(), adjusted in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2770
> Use new return-type of JC.getAllJavaSourceVersionsSupportedByCompiler()

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
After we dropped support of Java < 1.8 compliance level, we still have to deal with projects that have these setting stored in preferences.
- Make sure we don't allow use unsupported compliance from JRE < 1.8
- Make sure we update value of compliance/source and target to first supported version
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1465
> Deal with unsupported target options in compiler preferences

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/rename/RefactoringAnalyzeUtil.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test31_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
- modify the getModifiedInitializerSource() logic to mark locations where type parameters might need to be added to a method invocation
- in checkFinalConditions() apply all changes and calculate the positions of the marked locations then compile the new source to find all introduced problems in the new source
- if any type match problems are introduced at the marked locations, redo the refactoring and add type parameters in these locations
- re-enable InlineTempTests.test31
- fixes #1573
See issue.
Run InlineTempTests.
> Update InlineTempRefactoring logic for adding method type parameters

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/VarCleanUpCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest10.java
Reproducer for
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1525
The "fix" included seems to be a kind of bold hack. A good fix might need a changes to some underlying classes that can not really handle parametrized types for import removal in the case of type interference.
For the case of using diamond operater the underlying class to remove the imports of the instance expression is fed with the expression without the type so arraylist<> instead of arraylist<File>. The junit tests are fine but I do not trust this approach so much. And it seems to me there is really a lack of support for paramerized types in the classes in charge to handle the import removal. Maybe it is fine because within the scope of the code changes of this cleanup it is good enough?
Try to run it over jdtui …
> Test and preliminary fix for issue with "USE_VAR" cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/invalidSelection/A_testIssue1516.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- modify ExtractMethodRefactoring to test if the new method name collides with an existing method name being used by a class that sub-classes the one creating the new method
- add new test to ExtractMethodtests
- fixes #1516
See issue.
> Fix extract method to recognize name collision with a sub-class

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
- for #1531
Clarifies message when refactoring rename is not possible and instead we allow a lightweight text rename in file.
See issue.
> Clarify message when refactoring rename not possible

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreMarkdownAccessImpl.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/JavadocLookup.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/AutomatedSuite.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
+ add dependency org.commonmark incl. extension for tables
+ use it for rendering
+ markdown variant is detected by inspecting the raw javadoc text, might be replaced by new API in DOM
+ minimal tests incl. examples from the specification in https://openjdk.org/jeps/467
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1472
> [23] JEP 467: Render markdown doc comments

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test61/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test61/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test62/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test62/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail30/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail31/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail32/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail33/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail34/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- add new checking if PullUpRefactoringProcessor to check for an inner class referring to an outer class field or method that will be inaccessible after the pull up
- add new tests to PullUpTests
- fixes #1533
See issue.
> Add outer class checking to Pull Up Refactoring

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
Adapt to new return-type of `IExecutionEnvironmentsManager.getSupportedExecutionEnvironments()`, changed in
https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/474.
~Without that change being submitted, this PR's build cannot succeed (and without this, an I-Build with the other PR applied cannot succeed too).~ Without that change this PR leads to wrong display orders of the EEs.
> Adapt to new return-type of IExecutionEnvironmentsManager.getSupportedExecutionEnvironments()

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/search/JavaMatchFilter.java
+ ~~also enables a filter if applicable to only one from multi-selection~~
Seeing that filter applicability consistently uses "and" semantics for multi selections also for other filters I reverted that part.
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1604
> [23] search filter dialog should show "In Imports" option for module searches

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/AbstractSemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java23SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/testResources/semanticHighlightingTest1/Java23.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightingReconciler.java
Add semantic highlighting for 'module' in an module import declaration (as "Restricted Identifier").
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1589
> [23] Highlight 'module' in module imports

- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/JunitPreferenceInitializer.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1610
Make sure you have hamcrest 3.0 in your TP, e.g. from https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-09/ and have a JDT project with the `JUnit 4 or 5` classpath container.
I'm not exactly sure about the version range, the last time it was updated to only support hamcrest 2.2, but as written in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1610#issuecomment-2308799284, hamcrest 3.0 is probably a drop-in preplacement and both could be supported.
Given that we are late in the release-cycle it might even happen that not everyone is able to update to hamcrest-3.0
CC @laeubi and @iloveeclipse and maybe @merks is also interested.
> Support Hamcrest 3.0 in 'JUnit 4/5' classpath containers

- org.eclipse.jdt.core.manipulation/.settings/.api_filters
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/AbstractFastJavaPartitionScanner.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/ui/text/IJavaPartitions.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/template/java/JavaFormatter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/IndentUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/CodeTemplateSourceViewerConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaPartitionerManager.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaAutoIndentStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/SmartSemicolonAutoEditStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaSourceHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocAutoIndentStrategy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/JavaSourceViewerConfiguration.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
> [23] Partition support for markdown comments #1542

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest23.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/ContentAssistTestSuite.java
- org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaProjectHelper.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java23ProjectTestSetup.java
After https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1542 enabled completion inside markdown comments, this change adds infrastructure and smoketests for end-to-end testing of markdown link completion.
Also adds another forgotten test class to the suite.
> [23] Tests for link completion inside markdown comments.

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
Manually add the "(BETA)" suffix to a version label, if it's still in BETA status.
Tried to make it so only one location needs to be edited to leave BETA and later reenter for 24 etc.
fixes #1588
> [23] Compiler compliance level 23 missing (BETA) label

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/SemanticHighlightings.java
- fix SemanticHighlightings.DeprecatedMemberHighlighing to check if a deprecated member has a since tag which specifies a Java version that is above the project's compliance level
- fixes #1622
See issue.
See issue.
> Do not cross-out deprecated methods with safe since setting

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/TypeVariableUtil.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testGenericsTypeParameterRename/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testGenericsTypeParameterRename/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests1d8.java
- add new methods to TypeVariableUtil to get mappings for an implemented interface
- add calls to get new mappings when the mappings are empty for inherited methods
- add new test to PullUpTests1d8
- fixes #1532
See issue.
> Fix PullUp refactoring to handle implemented interfaces

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/Bindings.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveStaticMembersProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail25/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail25/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail26/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail26/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
- add logic to MoveStaticMembersProcessor to test if moving the member will override a reference to a member of the same name that the target class is referencing
- add new tests to MoveMemberTests
- fixes #1530
See issue.
> Add override checking to Move static member

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceAnalyzer.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/invalid/Test_issue_1529_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/invalid/Test_issue_1529_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- add new check in CallInliner which checks for trying to inline code with a super reference into a static method
- add new hasSuperFieldAccess() method to SourceAnalyzer
- fixes #1529
See issue.
> Fix inline method to check for super class reference into static method

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
- change ConvertForLoopOperation to change the logic that gets the type of size() method call to instead get the type of the expression calling it
- fixes #1617
See issue.
Run JDT UI test suite and test with jdtls.
> Change ConvertForLoopOperation to avoid getting type from size() method

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/jarpackager/JarPackageData.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/jarpackager/JarWriter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/jarpackager/JarWriter2.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/jarpackager/JarWriter3.java
Stream was not closed on IOException
fixes warning:
"Potential resource leak: '<unassigned Closeable value>' may not be
closed"
> JarWriter3: fix Potential resource leak, deprecate for removal

- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview/META-INF/MANIFEST.MF
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/asm/CommentedClassVisitor.java
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/views/BytecodeOutlineView.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDocSnippetStringEvaluator.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/dialogs/StatusInfo.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnusedCodeFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitClasspathFixProcessor.java
- org.eclipse.jdt.ui/internal compatibility/org/eclipse/jdt/internal/ui/dialogs/TypeInfoViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/IndentAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterModifyDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/ContentAssistPreference.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocSnippetStringEvaluator.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/CPListLabelProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/LibrariesWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/SourceContainerWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/DynamicSourcesWorkingSetUpdater.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/WorkingSetModel.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/ExternalizeStringsAction.java
Applying the if/else to switch cleanup to the codebase because two additional cases are supported now.
Not in all cases the code is much clearer after applying the cleanup. However in these cases the code is definitely not very clear before as well. So in real world usages the feature to switch off the cleanup on specific code locations comes in handy.
It should not change the way the code is processing. Might be in some corner cases switch is faster than if else chains.
Note:
There was a bug when processing "JUnitClasspathFixProcessor.java":
The comments for the strings have been removed and not reapplied. Not sure if that is a big deal as it can be applied automatically in a second step.
> dogfooding - if else to switch cleanup

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
Fixes #1598
Switch `&&` to `||` to prevent a `ClassCastException` in the case that the parent node is not a `ProvidesDirective`.
Set a debug point before the line that was changed, and modify the AST so that the parent node is not a `ProvidesDirective`. The method should return on the line after the line that was changed.
I don't have a method to reproduce this without modifying variables in memory, since the bug relies on a faulty error range or AST being generated by the compiler.
> Prevent potential `ClassCastException` in 'add service provider' quickfix

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/JUnitContainerInitializer.java
Since hamcrest version 2 the 'hamcrest-core' artifact only exists to redirect to the new 'hamcrest' artifact containing all of hamcrest. Therefore 'hamcrest-core' does only contains meteadata but no classes. For the 'JUnit 4/5' classpath container it is therefore useless in version 2 and later.
References:
- https://hamcrest.org/JavaHamcrest/distributables.html#previous-versions-of-hamcrest
- https://github.com/hamcrest/JavaHamcrest/releases/tag/v2.1
> Remove empty hamcrest-core 2.x from 'JUnit 4/5' classpath container

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests/pom.xml
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
- pom.xml
Since https://bugs.eclipse.org/73400 folding tries to use a shared scanner (for performance reasons). But that shared scanner may be inappropriately configured.
To minimize interference with https://bugs.eclipse.org/73400 I created a separate field `FoldingStructureComputationContext.fScannerForProject` which is used if a difference between project compliance and workspace defaults is detected.
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1634
> [23] FoldingStructureComputationContext should respect the project compliance level for parsing

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/UselessContinueCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/UselessReturnCleanUp.java
- add logic to UselessContinueCleanUp and UselessReturnCleanUp so they do not remove a return or continue statement if it is in an if then and there is an else with a single statement and the user has also specified to reduce indentation
- fixes #1638
See issue.
> Add logic to useless return/continue cleanups to prevent logic change

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/UselessContinueCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/UselessReturnCleanUp.java
- do not check how many statements are in the else clause, just that there is an else clause
See #1638.  The logic didn't handle the case where there are multipe statements in the else clause.
See #1638 and add an additional println statement to the else.
> Tweak new logic for useless return or useless continue clean-up

- org.eclipse.jdt.ui.tests/test.xml
move jit-exclusion to the correct ant target (hopefully)
fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1639
> [23] many errors, some failure in AutomatedTestSuite with latest from JDT/Core

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDoc2HTMLTextReader.java
Switches from using deprecated internal class to using API
> Move away of deprecated org.eclipse.jface.internal.text.html.SubstitutionTextReader

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/ReorgCopyAction.java
Use CopyProjectAction(IShellProvider) instead.
> Move away of deprecated CopyProjectAction(Shell)

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInnerToTopRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToTopLevel/testBug310510/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToTopLevel/testBug310510/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToTopLevel/testBug310510/out/Inner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToTopLevel16/test_Bug572639_2/out/Layout.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInnerToTopLevelTests.java
- fix MoveInnerToTopRefactoring.TypeReferenceQualifier visitor to not add qualifier to fields of member types that will end up being moved so to prevent call to addImport() to acquire Type
- add new test to MoveInnerToTopLevelTests
- fixes #1658
See issue.
> Bug 310510 - fix move to new type so extraneous import not added

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccess.java
- in the case of a package fragement, when we search for Javadoc content and do not find any package info, just return the empty string so Javadoc hover will at least show the package name
See commit message.
Add a Javadoc see reference to a package in the current project and click on the reference in the Java hover.  The package name should show up with icon and no content rather than nothing popping up.
> Fix reading html content of a package fragment to not return null

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/CleanUpNLSUtils.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/SimplifyBooleanIfElseCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstants.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstantsOptions.java
- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ReduceIndentationCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CodeStyleTabPage.java
- add new SimplifyBooleanIfElseCleanUpCore which reduces an if/else statement where the then statement is a boolean return statement and the else statement is an opposite boolean return statement
- add new tests to CleanUpTest
- add code to ReduceIndentationCleanUp to avoid collision with new clean up
- add new CleanUpNLSUtils class
- fixes #1632
See feature issue.
See new tests.
> Add new simplify boolean if/else cleanup

- Jenkinsfile
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/views/SmokeViewsTest.java
centos-latest is deprecated as per:
https://github.com/eclipse-cbi/jiro-agents/blob/master/README.md
Build verification works
> Build on ubuntu-latest

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
Test case for the jdt.core fix
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2980
> [23] Markdown doc comments with codeblock don't parse Javadoc tags afterwards #2989

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- modify LambdaExressionsFixCore to add a cast if the lambda will end up as an argument that is supposed to be a wildcard type and the bound is not compatible with the initial class instance creation type argument
- add new tests to CleanUpTest1d8
- fixes #1535
Adds a cast when needed to the lambda if it is a method argument where the argument is defined as a wild card type and
the bounds of the type and the class instance creation type arguments aren't sub-type compatible.
> Add additional logic to cast lambda for wildcard argument

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
Test case for https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3006
Adds testcase for https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3006
> [23] Issue with code fence > 3 in markdown comment

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test39/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test39/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
- fix PushDownRefactoringProcessor to look for method invocations and field accesses to super class members that have names that collide with members in any of the destination types and reference them using super expression
- add new test to PushDownTests
- fixes #1679
Fixes a push down operation from changing program logic.  See issue.
> Fix push down to recognize super class name collisions

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test40/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test40/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
- add logic to PushDownRefactoringProcessor.checkReferencesToPushedDownMembers() to ignore members in the declaring CU that will end up being targets of the move (i.e. they extend the declaring class)
- add new test to PushDownTests
- fixes #1691
See issue.
> Fix push down to allow moving fields/methods to inner/local classes

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test41/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test41/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
- modify PushDownRefactoringProcessor to replace any super method invocations and super field accesses to the members being pushed down if they are in a destination of the moved members
- add new test to PushDownTests
- fixes #1692
See issue.
> Fix push down to replace super references where appropriate

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyFiltersActionGroup.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyViewPart.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ShowCallHierarchyFilterDialogAction.java
Before the changes the filters could only be accessed through the "View Menu" (three dots), which is inconvenient considering that the filters button is rather important and frequently used.
After the changes the filters can be accessed by clicking on the icon in the top level bar as well as the old way through the view menu.
> Move filters Button in Call Hierarchy view to the top level Bar

- org.eclipse.jdt.ui/.settings/.api_filters
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1671
> Filter problem of accidental extra version increment

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/AutomatedSuite.java
It adds existing junit5 tests in the sourcetree to the build configuration. Theses tests could not be executed until recently the suites have been migrated from junit4 to junit5. This patch adds the tests to be executed as part of the build.
count the number of tests and check if "VisitorTest" is now part of the test execution.
> add a plain junit5 test to show junit5 tests are now possible

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallHierarchyCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallSearchResultCollector.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallHierarchy.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/FiltersDialog.java
Add a new option to only show the test code when filtering the Call Hierarchy. The option was missing before since one could only either show all code or show only non-test code.
> Show only tests

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallHierarchyCore.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallHierarchy.java
It does not have any effect on the functionality, but it addresses and completes the suggestion from @jukzi which he made here: (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1687)
Because the constants of which the visability is changed here are not part of PR #1687 , this PR is aimed at completing the suggestion made there.
> changing the visability Constants in the CallHierarchy

- README.md
- org.eclipse.jdt.ui.setup/.project
- org.eclipse.jdt.ui.setup/.settings/org.eclipse.core.resources.prefs
- org.eclipse.jdt.ui.setup/JdtUIConfiguration.setup
Add jdt.ui configuration setup.
Additionally add a styled and drag&drop-able Oomph Configuration button to the main README.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2430
This currently depends on https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1707 respectively contains the changed proposed there!
> [Oomph-Setup] Add jdt.ui configuration setup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Adds support to the StringBuilder/StringBuffer to text block cleanup/quick assist so that a call to indexOf() gets converted to a call to String.indexOf() on the converted text block.  Until now, additional method calls to the StringBuilder/StringBuffer that weren't append() or toString() resulted in not converting to the text block.
See #1703 or the new test cases added.
> Text block conversion support for indexOf()

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1695
> [24] Allow JDT to target Java 24 in compiler preferences

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/jarexport/FatJarExportTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/jarexport/PlainJarExportTests.java
System.setProperty("jdt.bug.367669", "non-null");
see
https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/?id=df26c679ec361eae61785b6b440639645b574764
https://bugs.eclipse.org/bugs/show_bug.cgi?id=367669
https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/commit/?id=7bbe9b200e2038f2a18dd4bf9b010385f95ab3de
> remove setproperty for jdt.bug.367669

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- add logic to StringConcatToTextBlockFixCore to handle the case where empty strings are appended
- modify tests in CleanUpTest15 to add some empty strings to existing tests
- for #1703
See commit message and issue.
See issue and test modifications.
> Modify string concat to text block cleanup to handle empty strings

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test65_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test65_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
- fix InlineTempRefactoring.getAlternativeQualification() to not calculate qualified alternatives if not dealing with static reference
- fix InlineTempRefactoring.checkClashes() to handle when there are qualified alternatives
- add new test to InlineTempTests
- fixes #1705
See issue.
> Fix illegal name exception when inlining qualified field name

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/internal/common/VisitorTest.java
- fixes #1723
See issue.
Run VisitorTest.
> Fix set up for VisitorTest now that ASTParser has changed

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedSuppressWarningsCleanUp.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsBaseSubProcessor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
- add new logic for UnusedSuppressWarningsCleanUp.computeNumberOfFixes() that screens the problems for the current literal or returns 1 if removing all unused tokens
- fix SuppressWarningsBaseSubProcessor to remove the call to remove all instances of current literal since the computeNumberOfFixes() call in the clean up will offer an option to do this automatically
- fix the test in QuickFixTest1d8
- fixes #1719
See issue.
> Fix unused suppressed warnings quick fix counts

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaManipulationPlugin.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditorBreadcrumb.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaCodeReader.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/SourceViewerInformationControl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/FilteredElementTreeSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ProjectsWorkbookPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/OpenProjectAction.java
Fix some deprecations by doing what the deprecation message suggests.
Ideally nothing should change in behavior.
> Fixdeprecations

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/templates/TemplateCompletionTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractConstantTests1d7.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/IntroduceFactoryTestsBase.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/WrappingSystemTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/TypeInfoTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest11.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d4.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d6.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d7.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest9.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/NewTypeWizardTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/wizardapi/NewTypeWizardTest17.java
junit asserts generate an error message based on the parameters presented. So when the fixed part and the actual part of an equal assertion is wrong it creates a wrong message about what was expected. The assertion still "works" because in an equal comparison the order does not matter regarding the failure of the junit test but the error message is wrong. 
Another case is when you do the comparison inside of an assertion to check for true. That way junit is inable to generate a useful error message.
This PR fixes some of these issues. It has been generated by using the "Autorefactor" cleanup at
https://github.com/carstenartur/AutoRefactor/tree/master
Afaik this cleanup will not make it into jdt.ui any longer.
I looked at it while checking what could help to migrate tests to junit5. 
Since …
> fix usage of asserts where order or condition is missleading

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
- for < JVM 21 add an if/else that checks for null
- for JVM 21 and up, add case null
- modified SwitchFixCore and modified tests in CleanUpTest12 to also not qualify enums if the switch value is an enum
- fixes #1714
See issue.
See issue.
> Fix if/else to switch to handle null scenarios

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClipboardOperationAction.java
- fix ClipBoardOperationAction.doPasteWithImports() to check if target is in a String or text block in which case do not add imports
- fixes #1716
See issue.
See issue or paste a section of code that uses imported classes into a text block or string literal.
> Fix smart paste to not import when pasting into string or text block

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
See comment.
Perform push down and there should be no exception.
> Fix array indexing exception in PushDownRefactoringProcessor

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/invalidSelection/A_testIssue1758.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- modify ExtractMethodRefactoring.checkForMethodOverride() to also check for a member class
- add new test to ExtractMethodTests
- fixes #1758
See issue.
> Fix extract method refactoring to recognize a member class collision

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RenameUnusedVariableCleanUpCore.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedCodeCleanUpCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnusedCodeFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest22.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTestCaseSuite.java
- org.eclipse.jdt.ui/plugin.xml
- add checks to UnusedCodeFixCore to not create a remove member operation in the case of unused pattern variables and unused lambda parameters when Java is 22 and up
- add RenameUnusedVariableCleanUpCore to JDT UI plug.xml
- add new CleanUpTest22
- fixes #1782
See issue.
> Fix unused variable cleanup to work with unused pattern/lambda vars

- org.eclipse.jdt.core.manipulation/forceQualifierUpdate.txt
- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/forceQualifierUpdate.txt
- org.eclipse.jdt.junit/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/forceQualifierUpdate.txt
- org.eclipse.jdt.ui/pom.xml
Changes to ecj are for handling of switch on String.
See: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2595
> Updated bundles with comparator errors

- org.eclipse.jdt.junit.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestRunSession.java
- org.eclipse.jdt.junit.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit.runtime/pom.xml
- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/RemoteTestRunner.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestViewer.java
- org.eclipse.jdt.ui.unittest.junit.feature/feature.xml
- org.eclipse.jdt.ui.unittest.junit.feature/pom.xml
- org.eclipse.jdt.ui.unittest.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.unittest.junit/pom.xml
- org.eclipse.jdt.ui.unittest.junit/src/org/eclipse/jdt/ui/unittest/junit/launcher/JUnitRemoteTestRunnerClient.java
- org.eclipse.jdt.ui.unittest.junit/src/org/eclipse/jdt/ui/unittest/junit/ui/JUnitTestViewSupport.java
When we click on the 'grouping' element for a ParametrizedTest, the code tries to find the method without the parameter types, but the search actually tries to find a parameter-less method with the same name.
1. Have a JUnit test:
```
@ParameterizedTest
@ValueSource(ints = {1,2,3})
void x(int l) {
fail("Not yet implemented");
}
@ParameterizedTest
@ValueSource(ints = {4})
void y(int l) {
fail("Not yet implemented");
}
@TestFactory
Collection<DynamicTest> dynamicTestsWithCollection() {
return Arrays.asList(DynamicTest.dynamicTest("First test", () -> {
fail("Bad luck");
}), DynamicTest.dynamicTest("Second test", () -> {
fail("Bad luck");
})
);
}
@ParameterizedTest
@MethodSource("testArgs")
void testInvisibleCharacters(String msg) {
}
private static List<String> testArgs() {
return …
```
> Fix clicking on a ParametrizedTest

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/ChangeSignatureProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/ChangeSignature/cannotModify/A_testFailIssue1750.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ChangeSignatureTests.java
- modify ChangeSignatureProcessor to add new checkShadowing2 method which recognizes when rename of method might affect an implementor of the class which is using a method of same name already
- add new test to ChangeSignatureTests
- fixes #1750
See issue.
See issue.
> Fix change signature to recognize a possible logic issue after rename

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceAnalyzer.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/receiver_in/TestQualifiedAnonymousReceiver.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/receiver_out/TestQualifiedAnonymousReceiver.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- fix SourceAnalyzer to denote a qualified this receiver if the qualifier is a type and also to not denote an anonymous class instantiation for implicit receiver
- fixes #1780
See issue.
> Fix inlining method with anonymous class and qualified this reference

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/IProposalRelevance.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest22.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Adds new quick fix for switch on sealed class and no cases.
See new tests.
> Sealedassist

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- change icon for rename to unnamed variable to match rename in file icon
- fixes #1836
See commit comment or issue.
See issue.
> Change the icon for rename to unnamed variable

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedVariablesQuickFixTest.java
- properly check context in an enum method before offering to create a new enum constant and possibly offer a new field or constant instead
- add new tests to UnresolvedVariablesQuickFixTest
- fixes #1839
Fixes Bug 96932.  See issue.
> Fix Bug 96932

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/ContinuousTypingCompletionTest.java
AsyncCompletionProposalPopup defers the actual
AbstractJavaCompletionProposal proposals. Test has to wait for async proposals to be calculated.
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1835
> fix ClassCastException in ContinuousTypingCompletionTest #1835

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/nls/NLSHint.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/nls/NLSHintStripQuotesTest.java
Fixes #1803.
See "Steps to reproduce" in the bug report #1803. With this fix the NSL dialog should open as usually.
> Bugfix for #1803: [Externalize Strings] IndexOutOfBoundsException.

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
Record classes are now handled the same way as normal classes. 
This bug fix was proposed here: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1813
Record classes were not checked for the amount of parameters which their methods had. Normal classes where though. That posed the problem, that when only one argument was given, the code minings were shown for record classes but not for normal classes.
Use this code snippet:
```` java
import java.util.Objects;
class Main {
public static void main(String...args) {
Car c = new Car(3);
Cat car = new Cat(5);
car.equals(c);
car.doSomething(12, 13);
}
}
class Cat {
private int size;
public Cat(int size) {
this.size = size;
}
public Cat(long age) {}
public int getSize() {
return size;
}
public void doSomething(int a, int b) {}
@Override
public …
```
> Record classes are now handled the same as normal classes

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- modify StringConcatToTextBlockFixCore to support the case where the StringBuilder/StringBuffer is passed as an argument and in that case do not replace the StringBuilder/StringBuffer but change it to initialize with a text block
- add new tests to AssistQuickFixTest15 and CleanUpTest15
- fixes #1841
See issue.  Allows conversion of more tests to use text block.
Run clean up on file mentioned in issue or see new tests.
> Enhance StringBuffer/StringBuilder to text block cleanup/quickfix

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest22.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- fix LocalCorrectionsSubProcessor.addPermittedTypes() method to not pass empty importName to the search pattern
- add new test to QuickFixTest22
- fixes #1845
See issue.
> Fix add permitted types quickfix

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessorUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/ConstructorFromSuperclassProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CreateNewObjectProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CreateObjectReferenceProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CreateVariableReferenceProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/MissingAnnotationAttributesProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/ModifierChangeCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/RefactoringCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/ReplaceCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/correction/CUCorrectionProposal.java
- create new LocalCorrectionsBaseSubProcessor in jdt.core.manipulation and have LocalCorrectionsSubProcessor sub-class it
- add new constructors where needed to support specifying a core class and an image
- fixes #1847
See issue.
Run normal JDT test-suite to verify no changes.
> Refactor LocalCorrectionsSubProcessor to jdt.core.manipulation

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail37/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- modify PullUpRefactoring.CheckInvalidOuterFieldAccess checker to also look for class.this references that won't be accessible after pulling up the method
- add new test to PullUpTests
- fixes #1823
See issue.
> Fix pull up scenario referring to outer this type

- org.eclipse.jdt.ui/css/e4-dark_jdt_syntaxhighlighting.css
As we changed the background color of the editor to a darker shade, the background of the breadcrumbs was still using the older color code. This has been changed to the same color code as the editor's.
Before:
After:
> [Dark Theme] Fix for bg color of bread crumb in editor

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/EmbeddedIfCleanUp.java
- modify EmbeddedIfCleanUp to check for line comments on the top and embedded if statement and preserve them in the merged if statement
- add new method to ASTNodes to get trailing line comment for a node plus an offset
- modify the embedded cleanup test in CleanUpTest to add new line comment scenarios
- fixes #1853
See issue.
> Fix embedded if cleanup to preserve line comments

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorCodeMiningConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
This PR will enable the possability to show code minings in all Methods, also those who expect just one argument.
When a method only had one parameter, it was eligible for code minings, except if it was from a record class.  As you can see in the screenshot and snippet, the code minings are shown for car but not for Cat.
```java
import java.util.Objects;
class Main {
public static void main(String...args) {
Car c = new Car(3);
Cat car = new Cat(5);
car.equals(c);
car.doSomething(12, 13);
}
}
class Cat {
private int size;
public Cat(int size) {
this.size = size;
}
public Cat(long age) {}
public int getSize() {
return size;
}
public void doSomething(int a, int b) {}
@Override
public boolean equals(Object obj) {
if (this == obj) return true;
if (obj == null || getClass() != obj.getClass()) …
```
> Provide name for parameters in 1-arg methods when using code minings

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/packageview/WorkingSetDropAdapterTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/workingsets/WorkingSetModel.java
The getter getAllWorkingSets() illegally caches - i.e. modified its state while that is unexpected during setWorkingSets()
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1863
tested by WorkingSetDropAdapterTest
> WorkingSetModel.setActiveWorkingSets: fix IllegalArgumentException #1863

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/AbstractPrimitiveRatherThanWrapperFinder.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StandardComparisonFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/PatternCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/PrimitiveParsingCleanUp.java
Since ECJ min supported version is 1.8 all other code mandates 1.8+ too.
Part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1685
> Remove Java 1.2 and 1.4 checks from JavaModelUtil

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/BracketInserterTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaPairMatcherTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaPairMatcher.java
Remove checks whether running on Java 1.5+ to handle them as ECJ mandates 1.8 thus this is always true.
Removed tests for pre 1.5 behavior and enable tests in JavaPairMatcherTest that were not executed at all.
> Handle < > brackets unconditionally

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.ui/internal compatibility/org/eclipse/jdt/internal/ui/dialogs/TypeSelectionDialog2.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/ParameterEditDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ExpandWithConstructorsConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/dialogs/FilteredTypesSelectionDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/filtertable/TypeFilterInputDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javadocexport/JavadocTreeWizardPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/CodeAssistFavoritesConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ImportOrganizeConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ImportOrganizeInputDialog.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/NameConventionConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ReorgCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/util/ClasspathVMUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewPackageWizardPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
ECJ supports 1.8 as min java version thus this would prevent the case of UI generating/accepting code that the compiler may reject at compile time.
> Stop assuming Java 1.3 source if project doesn't set explicitly

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClipboardOperationAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorColoringConfigurationBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne.java
Ecj supports min Java 8 so testing/supporting older versions in UI creates the risk of generating/accepting code that compiler may reject.
> Default to JAVA 8

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaDoubleClickSelectorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaPairMatcherTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaPairMatcher.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaDoubleClickSelector.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/JavaSourceViewerConfiguration.java
This is only code level cleanup as it is impossible for anyone to use as this was consulting project which can't not be pre 1.8 already.
> Stop support for pre 1.8 source in some editor features

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaCodeScanner.java
Java 8 is the min version ECJ supports thus having complicated way to add "assert"(1.4) and "enum"(1.5) is not needed and can be added to default keywords.
> Simplify JavaCodeScanner

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/FillArgumentNamesCompletionProposalCollector.java
Java 8 is the min version supported by ECJ thus generics are always supported.
> Always propose generics

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/GetterSetterCorrectionBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/GetterSetterUtil.java
- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/ExtractClassRefactoring.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/HierarchyProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
Every project is 1.8+ now as ECJ doesn't support pre 1.8 anymore.
> No need for 1.5 JVM checks in o.e.j.core.manipulation/refactoring

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/OrganizeImportsOperation.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/core/manipulation/dom/ASTResolving.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/template/java/JavaContextCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UtilitiesTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddImportsOperation.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsFix.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
ECJ mandates Java 8 level thus this code is always noop.
> Remove pre Java 1.5 checks form o.e.jdt.ui/core extensions and friends

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/AbstractForLoopJavaContextTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaModelOpCompundUndoTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/buildpath/BuildpathProblemQuickFixTest.java
> Tests should not explicitly set pre 1.8 compliance

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/AbstractToStringGenerator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/CustomBuilderGenerator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/StringBuilderGenerator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/StringFormatGenerator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/ToStringGenerationContext.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/ToStringGenerationSettingsCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringBufferFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringBufferToStringBuilderFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateToStringTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/StringBuilderCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/GenerateToStringAction.java
ECJ mandates 1.8+ and JDT UI converts compiler settings to that unconditionally so this code is simply non-reachable.
> Simplify "string" generation/cleanups by dropping pre 1.5

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/AbstractToStringGenerator.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/ToStringGenerationContext.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/tostringgeneration/ToStringGenerationSettingsCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateToStringTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/GenerateToStringAction.java
ECJ no longer supports pre 1.8 and JDT UI simply converts project settings to 1.8 if lower thus all this code is non reachable.
> Remove pre1.6 support from string generation

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/TypeContextChecker.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
Having code to show errors if Java 5 JVM when Java UI migrates projects to Java 8 is pointless.
> Remove last Java 5 checks from UI

- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RefactoringTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/actions/RefactoringActionsTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/all/AllRefactoringTestsSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/RefactoringCCPTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/changes/RefactoringChangesTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/extensions/RefactoringExtensionPointTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/typeconstraints/RefactoringTypeContraintTestSuite.java
- org.eclipse.jdt.ui.tests.refactoring/test.xml
Avoid duplicate class names to make it easier to find the right one
> make "AllTests" more specific

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- fix StringConcatToTextBlockFixCore.ChangeStringBufferToTextBlock to not assume indexOf() has just one parameter
- modify CleanUpTest15 to add new scenario
- fixes #1903
See issue.
See issue or test modifications.
> Fix StringBuffer/StringBuilder to text block to handle indexOf(x,y)

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test66_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test66_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
- fix InlineTempRefactoring.getAlternativeQualification() method to not add this qualifier to a local variable
- add new test to InlineTempTests
- fixes #1859
See issue.
See new test.
> Fix extraneous this expression being added during inline

- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/IntroduceIndirectionInputPage.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/RefactoringMessages.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ComparingOnCriteriaCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/JoinCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/LambdaExpressionAndMethodRefCleanUp.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/SurroundWithTryWithResourcesAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewAnnotationWizardPage.java
ECJ mandates 1.8 thus this code is not reachable.
Part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1685
> Remove usages of JavaModelUtil.is1d8OrHigher from o.e.jdt.ui

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/StubUtility2Core.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/TypeAnnotationRewrite.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SplitTryResourceFixCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringAvailabilityTesterCore.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/ConvertAnonymousToNestedRefactoring.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveStaticMembersProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/ui/fix/UseIteratorToForLoopCleanUpCore.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Ecj mandates 1.8 thus such guarded code is not reachable
> More removals of JavaModelUtil.is1d8OrHigher

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDocLocations.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/JavaModelUtil.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/buildpath/JUnitContainerWizardPage.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.java
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.properties
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/ExternalNullAnnotationChangeProposals.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ComplianceConfigurationBlock.java
> Final bits of pre 1.8 support removal in JavaModelUtils

- org.eclipse.jdt.bcoview.feature/feature.xml
- org.eclipse.jdt.bcoview/META-INF/MANIFEST.MF
- org.eclipse.jdt.bcoview/pom.xml
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/ui/JdtUtils.java
Checks were done based on compiler settings for the project and ECJ mandates 1.8 as a minimum now.
> Remove code for Java pre 1.5 Java from bytecodeview

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_in/A_testIssue1913_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_in/A_testIssue1913_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_out/A_testIssue1913_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/validSelection_out/A_testIssue1913_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- fix ExtractMethodAnalyzer.checkInitialConditions() to replace the selection if dealing with an Expression that is part of an ExpressionStatement and the logic has calculated there are multiple return values
- modify ExtractMethodRefactoring to recognize if the analyzer has replaced the selection in which case start again and refresh values
- add new tests to ExtractMethodTests
- fixes #1913
See issue.
> Bug 285551 - [extract method] "Ambiguous return value" error

- org.eclipse.jdt.astview.feature/feature.xml
- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/Binding.java
Instead of inlining (with all drawbacks from that) the JLS_LATEST constant remove the inlined constant and use AST.getJLSLatest()
> Simplify latest JLS version in astview

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/util/Progress.java
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1920
> Progress: add missing license header in Progress.java #1920

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/packageview/ContentProviderTests3.java
Currently non trivial code is used in ContentProviderTests3 to trigger a delta event in 5 places. In one of them it is even done wrong where the assert is part of the eventloop because of missing brackets.
> Unify event triggering in ContentProviderTests3

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1856_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1856_1.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- change SourceProvider.getExpressionRanges() to add in comments of return statement when NLS comments are present
- change CallInliner.replaceCall() to try and split the last block at a semi-colon in case it was created by a return statement that had NLS comments
- if the split results in 2 segments, try and form a new statement that adds the new expression and NLS comments
- does not handle modifying existing NLS markers at target
- fixes #1856
See issue.
See new test.
> Fix inline method to attempt to copy over NLS comments when appropriate

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/MethodOverrideTester.java
don't visit redundant superinterfaces more then once
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1922
> fix slow Quick Outline View #1922

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaOutlineInformationControl.java
The Quick Outline View currently applies (i.e., calculates and draws) decorations for override indicators synchronously. In case the calculation of the indicator takes long, it blocks the UI. The ordinary Outline View defers the responsibility of calculating and applying decorations to the `DecorationManager`. This ensures that (1) that task is performed asynchronously via a dedicated job and (2) that the `DecorationManager` takes care of the current user configuration (i.e., whether those indicators shall be shown or not), which the Quick Outline View currently replicates.
With this change, the Quick Outline View uses the same label decorator as the ordinary Outline View, which makes the `DecorationManager` process the override label decorator asynchronously instead of applying it …
> Asynchronously decorate quick outline view via DecorationManager #1922

- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/views/BytecodeReferenceView.java
- org.eclipse.jdt.bcoview/src/org/eclipse/jdt/bcoview/views/HelpUtils.java
As the URL is used to fetch remote content and the url is hardcoded it's safe to go through URI.
Skipped needless String-URL-String conversion for loading web view.
> Fix usage of deprecated URL constructor in o.e.jdt.bcoview

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsBaseSubProcessor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsSubProcessor.java
- add new abstract method alreadyHasProposal() to SuppressWarningsBaseSubProcessor to check if a proposal has already been added
- add implemention of alreadyHasProposal() to SuppressWarningsSubProcessor
- add new test to QuickFixTest1d8
- fixes #1935
Prevents duplicate proposals to add suppress warnings annotations.
> Fix duplicate add suppress warnings proposals

- org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaTestPlugin.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/PackageJavadocTests.java
* Let Bundle.getEntry do full resolving
* If it's actually used to openConnection go through URI creation.
> Stop using deprecated URL constructors in o.e.jdt.ui.tests

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest1d7.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d7.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ChangeNonStaticToStaticTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTestCase.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/PropertiesFileQuickAssistTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/SurroundWithTemplateTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
Class org.eclipse.core.runtime.Preferences has been deprecated for years and method getJavaCorePluginPreferencesNew (returning IEclipsePreferences) is there.
Migrated unit tests to use getJavaCorePluginPreferencesNew.
> Deprecate for removal JavaPlugin.getJavaCorePluginPreferences

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
- add check for number of string literals to new logic that converts the initializer of the StringBuilder/StringBuffer
- modify test in CleanUpTest15
- modify test in AssistQuickFixTest15
- fixes #1944
See issue.
> Fix extraneous text block conversion from StringBuffer/StringBuilder

- org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner/RemoteTestRunner.java
Recommended way is Class.getDeclaredConstructor().newInstance()
> Stop using deprecated Class.newInstance()

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/ContentAssistHistoryTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/ContentAssistHistory.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
Long deprecated o.e.core.runtime.Preferences class would better not be used anymore.
> Migrate ContentAssistHistory to IEclipsePreferences

- org.eclipse.jdt.ui/.settings/.api_filters
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/HierarchyInformationControl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/SubTypeHierarchyViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/SuperTypeHierarchyViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TraditionalHierarchyViewer.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyViewPart.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/TypeHierarchyViewer.java
Fixes eclipse-jdt#1830
Expand an interface from here:
```java
class ReproducerRedundantTypeHierarchy {
interface I0 {}
interface I1 extends I0 {}
interface I2 extends I1, I0 {}
interface I3 extends I2, I1 {}
interface I4 extends I3, I2 {}
interface I5 extends I4, I3 {}
interface I6 extends I5, I4 {}
}
```
The **(Quick) Type Hierarchy** should not expand the same interface twice
---
> Do not expand same class twice in (quick) type hierarchy

- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpPostSaveListener.java
- org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/RefactoringExecutionStarter.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/AddGetterSetterTypeProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/EnablePreviewFeaturesAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/HashCodeEqualsTypeProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/SurroundWithTemplateMenuAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ToStringTypeProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/compare/JavaCompareWithEditionActionImpl.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/infoviews/JavadocView.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackager/CreateJarActionDelegate.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaElementImplementationHyperlink.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/GetterSetterCorrectionSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/PreviewFeaturesSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaContentAssistHandler.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/AbstractAnnotationHover.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/ConfigureProblemSeverityAction.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavaDocAutoIndentStrategy.java
Currently JavaPlugin.getActivePage() fails if no workbench is running, while the method itself can return null if there is no active window anyways. Beside that is unnecessary access the default java plugin even though all code called there is static anyways.
This now changes the following parts:
1) guard getActiveWorkbenchWindow against not running workbench 2) used getActiveWorkbenchWindow instead of similar code in getActivePage like in getActiveWorkbenchShell
3) delete no longer needed private method
> Make JavaPlugin.getActivePage() aware of not running platform and inline

- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/core/indexsearch/IIndexQuery.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/Jsp2JavaReconcileStep.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/Jsp2JavaTagHandler.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/Jsp2JavaTagHandlerFactory.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/JspEditor.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/JspReconcilingStrategy.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jdt/internal/ui/examples/jspeditor/JspSourceViewerConfiguration.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jface/text/source/translation/TagHandlerFactory.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jsp/JspPluginImages.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jsp/JspTypeQuery.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jsp/Util.java
- org.eclipse.jdt.ui.examples.javafamily/src/org/eclipse/jsp/launching/TomcatTab.java
* organize imports
* try with resources
* proper url resolving
* remove useless @see comments
* some pattern matching
> Code improvements in o.e.jdt.ui.examples.javafamily

- org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/util/CreateStubsAction.java
While in the class also:
* use pattern matching
* create arrays with curly
* multi-catch
This useless cast is catched by javac but not by ecj.
> Remove useless cast in CreateStubsAction

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
As compiler no longer supports pre Java 8 it is of no help if AST view
shows AST for unsupported JLS versions.
> Make AST view show only supported JLS versions + modernize code

- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/views/ASTView.java
Rather then explicitly listing versions cycle through the AST supported versions and create for toggle for each of them.
Mnemonics for these toggles are removed now but they have been broken already as there have been conflicts (8 and 18, 9 and 19, 10 and 20, 11 and 21, 12 and 22, 13 and 23) rendering mnemonics useless. This has the good side effect of removing the need to touch AST view for new Java version support.
> Automate JLS selection toggles in AST view

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDependenciesPage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/buildpaths/ModuleDialog.java
Use the new method that filters based on the release. If release option is not set, use target and if it's not there too use the latest version.
> Adjust to JavaCore.defaultRootModules deprecation

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTestUtils.java
I have added test cases to validate the current folding mechanism.
> Adding test cases for folding

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest14.java
- add logic to SwitchExpressionsFixCore to handle default case falling through and defer the default case until after the fallthrough logic is converted
- add new tests to CleanUpTest14
- fixes #1983
See issue.
> Fix switch expression cleanup to handle default case falling through

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
> Add test for #1951

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
- modify LambdaExpressionsFixCore to not convert a single expression statement into a lambda specifying expression if the statement has a line comment such as a non-NLS marker
- fixes #1999
See issue.
> Fix convert to lambda for one statement that has non-NLS marker

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/typehierarchy/HierarchyInformationControl.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2002
See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2005#pullrequestreview-2605627182
Supersedes https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2005
> Fix NPE when opening quick type hierarchy twice #2002

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
- fix PatternInstanceofToSwitchFixCore.PatternToSwitchExpressionOperation to remove all if statements at end of rewriteAST() method
- add new test to CleanUpTest21
- fixes #2012
See issue.
> Fix pattern instanceof clean-up to remove all if statements

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
If the second method starts on the same line where the first one ends, there will still be two foldings. (I accidentally set includeLastLine to true a second time, which caused the issue).
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1992
Testing:
1. Disabled new/experimental folding
2. Fold a, now b should be visible
```java
package org.example.test;
class X {
/*
* a b
*/
void a() {
} void b() {
}
}
```
> Fix folding of 2 consecutive methods

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Currently, the new folding feature does not support folding for local classes, whereas the old folding mechanism does. This fix ensures that local classes can be folded as expected. Additionally, I add a test case for the scenario.
Test:
1. Activate the new folding
2. Fold inner2, now it should be folded
```java
class Outer {
void a() {
class Inner2{
}
}
}
```
> Fix folding of local classes

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/infoviews/JavadocView.java
Partition based selection handling needs to handle markdown, too.
Fixes part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1800
> javadoc Markdown issues

- org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.text.tests/pom.xml
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest1d8.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/LazyJavaTypeCompletionProposal.java
- fix LazyJavaTypeCompletionProposal.computeReplacementString() to not fully qualify if we are completing an annotation type which could already be computed to not be fully qualified (e.g. java.lang)
- add new test to CodeCompletionTest1d8
- fixes #2047
See issue.
> Fix completion of annotation in package-info.java to not fully qualify

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/CodeGenerationMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/CodeGenerationMessages.properties
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/AddImportTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddImportsOperation.java
- modify AddImportsOperation to do a check if the name without qualification is used in the compilation unit for a similar purpose (e.g. method name, variable name, type name) and fail if that is the case
- add new test to AddImporTest
- fixes #2043
See issue or original bug.
> Fix add import operation to avoid name collision

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveStaticMembersProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/a/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/b/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/a/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/b/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/a/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/b/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/a/T.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/b/T.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
- modify MoveStaticMembersProcessor and MoveInstanceMethodProcessor to look for simple types that collide with classes that are already imported in the target
- add new test to MoveMembersTests and MoveInstanceMethodTests
- fixes #2030
See issue or original bug.
> Add checking for import collision when moving methods

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CalleeAnalyzerVisitor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyContentProviderTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyTestHelper.java
- modify CallAnalyzerVisitor to handle MethodReference
- add new test to CallHierarchyContentProviderTest and add support for this in CallHierarchyTestHelper
- fixes #2029
See issue.
> Add method reference support to Call hierarchy callee tree

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/ControlStatementsCleanUp.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpStressTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- refactor ControlStatementsCleanUp and ControlStatementsFix to jdt.core.manipulation
- fix ControlStatementsFix to not look from the if statement start when looking for comments to add after block start
- add new test to CleanUptest
- fixes #2057
See issue.
> Fix adding blocks to not duplicate comment in else

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTestSuite.java
- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui/pom.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/DefaultJavaFoldingPreferenceBlock.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/FoldingMessages.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/FoldingMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Relevant issues: https://bugs.eclipse.org/bugs/show_bug.cgi?id=173796 (and there are also similar ones like https://bugs.eclipse.org/bugs/show_bug.cgi?id=258965 for CDT).
There is also a [Stack Overflow post](https://stackoverflow.com/q/13505413/10871900) asking for how to do that with quite a few upvotes so I'd say it seems like many people are interested in such a feature.
This PR allows to add custom folding regions using comments.
I added new options to the preferences in `Java` > `Editor` > `Folding` (not that I changed this preference page to use `Group`s):  
If a comment containing the start region and a comment containing the end region are present in the same source file, a folding region is added allowing to collapse that section. 
It would be possible to change the defaults …
> custom folding regions

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- modify ControlStatementsFix to look for NLS comments when we have then statement on same line as if because they will belong to then statement and not if and should not be blindly moved
- fixes #2059
See issue.
> Fix add blocks when then statement is on same line as if and nls comment

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- add logic to ControlStatementsFix to look at the last line of the expression instead of the if statement start
- fixes #2060
See issue.
> Fix add block to handle if expressions over multiple lines

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/DestinationContentProvider.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/ReorgUserInputPage.java
Fixes: #1246 - #1337
User can now search from the large tree of projects and packages to move the file to.
Go to any file, right click --> Refactor --> Move --> Dialog Box will open with a treeview of Project and Packages --> Type in the search box and see if the filters are working fine
> Add Filter Mechanism for Target in Move Refactoring - with caching

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
- fix PatternInstanceofToSwitchFixCore to create a block for no statements or one statement that is not an expression statement or a throw statement
- add new tests to CleanUpTest21
- fixes #2066
See issue.
> Fix some pattern instanceof to switch cleanup errors

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
- modify PatternInstanceofToSwitchFixCore to recognize an if equals to null in the chain of ifs and create a separate null case for it
- add and modify CleanUpTest21 with new null case logic
- fixes #2073
See issue.
> Enable null case recognition in PatternInstanceofToSwitchFixCore

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Fixes the issue of double folding when a field declares an anonymous class. Previously, both the field and the anonymous class were folded, resulting in overlapping fold regions. With this change, only the anonymous class is folded, eliminating the duplicate region.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2022
Test:
1. Set a breakpoint at the end of org.eclipse.jdt.text.tests.folding.FoldingTestUtils.getProjectionRangesOfFile(IPackageFragment, String, String).
2. Skip the first visit because that covers the new folding test.
3. Inspect the regions list: there should be exactly two entries, confirming that fields with anonymous classes no longer produce double folding
> Fix too many folding regions in anonymous class

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
Check if the smart casting can be used in deeper parts of the AST, not just directly as the first expression, which is surprisingly common.
Improve the logic which tries to locate casts that can be eliminated with pattern matching
Run the refactoring on a bigger codebase
> Improve the instanceof pattern matching refactoring

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- modify PatternMatchingForInstanceofFixCore to handle conditional expressions in addition to if statements
- add new scenarios to CleanUpTest16
- fixes #2094
See issue.
See issue or new test scenarios.
> Add conditional expression support to pattern instanceof cleanup

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
- modify PatterMatchingForInstanceofFixCore to handle casts in the if statement of the instanceof expression
- add new scenario to CleanUpTest16
- fixes #2094
See issue.
> Fix Pattern instanceof cleanup to handle casts in the if statement

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2111_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2111_1.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- modify SourceProvider.isSimpleFunction() to allow an empty method
- fix CallInliner.replaceCall() to handle an empty method being inlined into a lambda body
- fixes #2111
See issue.
> Allow an empty method to be inlined in a lambda expression body

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/Invocations.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/TargetProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- fix Invocations to handle method references for various methods (e.g. method binding)
- add method reference support to CallInliner.replaceCall()
- add method reference support to TargetProvider.InvocationFinder
- fixes #2118
See issue.
> Fix inlining to support method references

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedSuppressWarningsCleanUp.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/ui/cleanup/CleanUpRequirements.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpRefactoring.java
- modify CleanUpRequirements to have a new boolean setting regarding separate compiler options and add new constructor that sets it explicitly (otherwise, it defaults to false)
- modify CleanUpRefactoring.CleanUpFixpointIterator to not merge options from a cleanup that requires its own options and also modify the next() method to use these special options for such a cleanup which must also request a fresh AST and must be at the end of the cleanup list with others that do the same
- fixes #2123
See issue.
Run tests already in place.
> Ensure unused suppress warnings cleanup uses it own compiler options

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2111_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_3.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2111_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_3.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- modify CallInliner.checkInvocationContext() to allow a non-simple method in a lambda body
- also modify CallInliner.replaceCall() to add support for replacing a lambda body or a method reference with the contents of a non-simple method
- fixes #2111
Adds support for more complex methods to inline into lambda.
See new tests.
> Allow inlining in lambda to support multiple statement methods

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaReconciler.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2074
See the issue and this PR:
https://github.com/eclipse-pde/eclipse.pde/pull/1711
Basically in a self-hosted launch, create some plugin projects,  leave an editor on one source file open, and restart.
> Ensure forceReconciling is called after initialProcess if it was ignored

- org.eclipse.jdt.ui.tests/leaks/org/eclipse/jdt/ui/tests/leaks/JavaLeakTest.java
With https://github.com/eclipse-platform/eclipse.platform.ui/pull/2881, .txt files are opened by default with more advanced "generic code editor" so changed the file names to make sure they are not known by content types catalog and so still opened with "old default" plain text editor.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2129
> Updated test to open plain text editor

- org.eclipse.jdt.ui.tests/leaks/org/eclipse/jdt/ui/tests/leaks/JavaLeakTest.java
"expected" and "actual" were being used wrong.
I noticed it when looking at the stack traces of the failing tests reported in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2129
> Invert the parameters in calls to assertEquals in JavaLeakTest

- org.eclipse.jdt.ui.tests/leaks/org/eclipse/jdt/ui/leaktest/LeakTestCase.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/search/SearchLeakTest.java
The SearchLeakTest starts search, opens an editor and expects it is **exactly** `TextEditor.class`.
Now after changes in
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2881 it finds `ExtensionBasedTextEditor` class, which is a subclass of `TextEditor`, but test logic doesn't like that.
Fixed test expectation and allow opened editor be a subclass of `TextEditor`.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2132
> Fixed too strict test assumptions in SearchLeakTest

- org.eclipse.jdt.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2972
> Touch org.eclipse.jdt.ui to reflect compiler changes

- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ccp/MoveTest.java
- The (positive) test `testDestination_yes_cuFromRoot` could only work with compiler set to use 1.3 JLS.
- The sibling (negative) test `testDestination_no_cuFromRoot` changed to use supported JLS version.
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3883
> Remove test relying on Java 1.3 compilation options

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest23.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/FillArgumentNamesCompletionProposalCollector.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/CompletionProposalLabelProvider.java
Get the new display string for completion proposal via new API CompletionProposal#getDisplayString()
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3773
> Completion within markdown should escape array brackets #3773

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest22.java
- modify PatternInstanceofToSwitchFixCore to recgonize the absence of an else for the last if statement and if the following statement is a return or throws statement, treat it as if it were in an else
- add tests to CleanUpTest21 and CleanUpTest22
- fixes #2143
See issue.
> Add support for trailing return or throws for pattern instanceof cleanup

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
I added support for folding switch statements and switch expressions. Now they can be collapsed. In addition I added test caes for them.
Old switch stament:
Old switch expression
New switch statment:
New switch expression
1. Add both codesampels in a workspace 
2. Now there should be folding buttons
For switch expression:
```java
int b = 0;
int c = switch (b) {
case 1 -> 1;			
default -> 0;			
};
```
For switch statment:
```java
switch (zaehler) {
case 0:
break;
case 1:
break;
default:
break;
}
```
> Added Switch Statment and Switch Expression to the new folding

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- fix PushDownRefactoringProcessor.getReferencingElementsFromProject() method to reset the source string each time we look at a SearchResultGroup as the source may change from group to group and is not guaranteed to be the original compilation unit
Fixes push down to properly look at the right source when searching for references.
> Reset source to result group source when using search in push down

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
- modify ConvertLambdaToMethodReferenceFixCore to recognize when a method invocation in the lambda body has an expression that is a lambda parameter so is not a true variable to base a method reference off of
- add new test to AssistQuickFixTest1d8
- fixes #2152
See issue.
> Fix convert to lambda method reference to recognize a lambda parm

- README.md
- Removed obsoleted links
- Added links to common contributing page.
- Made it more looking like JDT core entry page
> [Documentation] cleaned up project entry page on github

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/FoldingMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
This PR makes the new folding the default and removes the references to its experimental status, as mentioned in #2084.
What I changed:
Before:
After:
How to test:
1. Start a clear workspace
2. Go to the settings and check if the extended folding is activated
> Make the new folding default

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/InitializeFinalFieldProposal.java
`InitializeFinalFieldProposal` now selects more appropriate description using updateType passed to it, which helps better distinguish both types of corrections in UI.
- create new class
- create final field inside it
- create empty constructor
- invoke correction proposals with `Ctrl+Space` or other configured shortcut
- see the different names
Fixes #2157
> [#2157] Describe final field initialization proposal considering type

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/AbstractSemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/AutoboxingSemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/BracketInserterTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/BreakIteratorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/CompilationUnitDocumentProviderTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JUnitProjectTestSetup.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/Java24SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaAutoIndentStrategyTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaBreakIteratorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaColoringTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaDoc2HTMLTextReaderTester.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaDoubleClickSelectorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaElementPrefixPatternMatcherTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaHeuristicScannerTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaModelOpCompundUndoTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaParameterListValidatorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaPartitionerExtensionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaPartitionerTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaStringDoubleClickStrategyTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JavaWordIteratorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/MarkOccurrenceTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/OverrideIndicatorTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PartitionTokenScannerTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PluginsNotLoadedTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/PropertiesFilePartitionerTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/SemanticHighlightingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/SmartSemicolonAutoEditStrategyTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/CodeMiningTriggerTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/semantictokens/SemanticTokensProviderTest.java
some classes are not part of any suite and contain failing tests even before migrating
Make use of Junit 5 instead of Junit 4.
Run Tests through. There should be no difference.
> more Junit 4 to Junit 5 migrations

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- modify VariableDeclarationFixCore to not add final qualifier when there are errors in the file and we are not able to determine if a variable is modified or not
- fixes #2166
Fixes add final qualifier cleanup to not perform a change if the compilation unit has errors.
> Do not add always add final field qualifier when compilation unit has errors

- org.eclipse.jdt.ui/META-INF/MANIFEST.MF
Dependency on new API added via https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2155 
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3918
> Bump up JDT UI dependency on JDT core

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/NewVariableCorrectionProposalCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedTypesQuickFixTest.java
- modify NewVariableCorrectionProposalCore.getDominantNode() to also look for parent being enhanced for statement
- add new test to UnresolvedTypesQuickFixTest
- fixes #2180
See issue.
> Fix quick fix for missing type in enhanced for loop

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
Two superflous newlines (`<br>`) where causing the bold font styling to be place on the wrong chars.
fixes #2183
---
Like I said in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2183#issue-3021815464, this should probably also be fixed upstream, but I don't know where to look. Either way I think this fix makes sense since we don't want to start the preview with two newlines.
> Fix `Create new member record preview`: formatting is off

- org.eclipse.jdt.jeview.feature/feature.xml
- org.eclipse.jdt.jeview/META-INF/MANIFEST.MF
- org.eclipse.jdt.jeview/icons/c/children.svg
- org.eclipse.jdt.jeview/icons/c/codeSelect.svg
- org.eclipse.jdt.jeview/icons/c/info.svg
- org.eclipse.jdt.jeview/icons/c/properties.svg
- org.eclipse.jdt.jeview/icons/c/refresh.svg
- org.eclipse.jdt.jeview/icons/c/setfocus.svg
- org.eclipse.jdt.jeview/icons/view.svg
- org.eclipse.jdt.jeview/plugin.xml
- org.eclipse.jdt.jeview/src/org/eclipse/jdt/jeview/JEPluginImages.java
This PR adds SVGs for all icons in the bundle `org.eclipse.jdt.jeview`.
See also this [PR](https://github.com/eclipse-platform/eclipse.platform/pull/1797) for more information.
> Add SVGs to org.eclipse.jdt.jeview

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
> Fix `Create new member record`: preview is missing `record` keyword

- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/breadcrumb/BreadcrumbItemDropDown.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/viewsupport/javadoc/SignatureStylingColorPreferenceMenuItem.java
Replacing it with imageGcDrawer constructor Image(device, imageGcDrawer, width, height). Later Image(device, width, height) is set to be deprecated. 
- [ x ] I have thoroughly tested my changes
- [ x ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ x ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)
> Replace usages of new Image(device, width, height)

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/in/B.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/out/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/out/B.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
- modify PullUpRefactoringProcessor.PullUASTNodeMapper to replace a this argument to a method with the new argument that gets added
- modify existing PullUpTests where the behavior has been fixed
- add new test to PullUpTests
- fixes #2192
See issue.
> Fix pull up refactoring to properly replace this argument when needed

- Jenkinsfile
Also make sure the issues are published even in case of a failed build, as otherwise they are not visualized and improve order of post-actions.
Additionally record javadoc and maven issues, but don't add a quality-gate for them.
This is similar to
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1932
> [Build] Migrate to new tycho-apitools log and list javadoc/maven issues

- org.eclipse.jdt.astview/META-INF/MANIFEST.MF
- org.eclipse.jdt.astview/icons/e/add.svg
- org.eclipse.jdt.astview/icons/e/clear.svg
- org.eclipse.jdt.astview/icons/e/collapseall.svg
- org.eclipse.jdt.astview/icons/e/expandall.svg
- org.eclipse.jdt.astview/icons/e/refresh.svg
- org.eclipse.jdt.astview/icons/e/setfocus.svg
- org.eclipse.jdt.astview/icons/e/synced.svg
- org.eclipse.jdt.astview/icons/view.svg
- org.eclipse.jdt.astview/plugin.xml
- org.eclipse.jdt.astview/src/org/eclipse/jdt/astview/ASTViewImages.java
This PR adds SVGs for all icons in the bundle `eclipse.jdt.astview`.
See also this [PR](https://github.com/eclipse-platform/eclipse.platform/pull/1797) for more information.
> Add SVGs to org.eclipse.jdt.astview

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnwrapNewArrayOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- fix UnwrapNewArrayOperation.rewriteAST() to properly set the tagged flag to true when non-nls markers exist on the line of an operand (i.e. not just the operand itself)
- add new test to CleanUpTest1d5 = fixes #2202
See issue.
> Fix remove unnecessary array creation clean-up with non-element non-nls

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2210.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2210.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- add checks in CallInliner.computeRealArguments() when adding local variables to add instanceof check for the variable if it is a cast expression and the initial invocation is in a conditional with instanceof checking
- fixes #2210
See issue or bug.
See issue or bug or new test.
> Fix Bug 240537

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/util/ChangedValueChecker.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test127_out.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test162_in.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test162_out.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
- fix ChangedValueChecker to accept an Expression to ignore if assigned to
- fix ChangedValueChecker.UpdateVisitor to ignore the specified Expression on left side of Assignment, if specified
- add new test to ExtractTempTests and fix test cases which behave different with new logic
- fix ExtractTempRefactoring to pass the selected expression to ignore if assigned to and if assigned to, replace with a double assignment (x = y = zzzz)
- also fix ExtractTempRefactoring name logic to bump up the end number rather than concatenating a new digit
- fixes #1901
See issue.
> Fix extract local to not create tmp variables for certain assignments

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnwrapNewArrayOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- use ImportRemover in UnwrapNewArrayOperation.java
- add new test to CleanUpTest1d5
- fixes #2222
See issue.
> Fix Unnecessary Array cleanup to remove unneeded imports

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StandardComparisonFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- fix StandardComparisonFixCore.StandardComparisonFinder to look for known comparisons (Comparable.compareTo, Comparator.compare, and String.compareToIgnoreCase)
- fixes #2221
See issue.
> Fix Standard Comparison clean-up false positive for enablement

- org.eclipse.jdt.junit5.runtime/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit5.runtime/pom.xml
- org.eclipse.jdt.junit5.runtime/src/org/eclipse/jdt/internal/junit5/runner/JUnit5TestLoader.java
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2257
Use the class name in the selector, rather than a class object, to avoid 'locking in' the classloader of the class. Locking in the class prevents thread context classloaders being used in the discovery phase to load classes.
To reproduce the original problem, there are two options:
- Write a JUnit DiscoveryListener which sets a thread context classloader; confirm that with the changes, tests are being loaded with the thread context classloader
- Create a minimal Quarkus application using https://code.quarkus.io/, load it into Eclipse, and then run `GreetingResourceTest` by right clicking on the class name. Without the fix the launch fails, with the fix the launch succeeds.
I've used the Oomph SDK and run an Eclipse with my …
> Use class names for selectors to avoid locking in classloader

- org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantComparisonStatementCleanUp.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantFallingThroughBlockEndCleanUp.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantIfConditionCleanUp.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantModifiersCleanUp.java
- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantSuperCallCleanUp.java
Refactors various clean-ups in jdt.ui to jdt.core.manipulation so jdt.ls can use them.
Run normal test suite.
> Refactor redundant clean-ups to jdt.core.manipulation

- org.eclipse.jdt.junit/META-INF/MANIFEST.MF
- org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestViewer.java
- modify TestViewer.compareName() to use the display names of the elements rather than the full qualified names as the qualified class name is not shown and the user has no idea about why the ordering isn't as expected
- fixes #2244
See issue.
See issue.
> Change Junit name comparator to use display name instead of full name

- org.eclipse.jdt.ui/plugin.xml
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaStickyLinesProvider.java
> Stickylines

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/makestatic/InstanceUsageRewriter.java
- org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
- org.eclipse.jdt.ui.tests.refactoring/pom.xml
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testFieldAccessInAnonymousClassExtendingRefactoredClass/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testFieldAccessInAnonymousClassExtendingRefactoredClass/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testFieldAccessInAnonymousClassExtendingRefactoredClass2/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testFieldAccessInAnonymousClassExtendingRefactoredClass2/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testInnerFieldAccessInAnonymousClass3/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/MakeStatic/testInnerFieldAccessInAnonymousClass3/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MakeStaticRefactoringTests.java
- modify InstanceUsageRewriter.visit(ThisExpression) to not leave qualified this instances in an anonymous class alone
- modify InstanceUsageRewriter.modifyFieldUsage() to modify any anonymous field accesses that are private
- add new tests to MakeStaticRefactoringTests
- fixes #1824
See issue.
> Fix make static anonymous class handling

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDocLocations.java
- fix CoreJavaDocLocations.handleFailedJavadocFetch() to not report ELEMENT_DOES_NOT_EXIST errors
- fixes #1997
See issue.
See issue test.
> Do not log file does not exist message when showing Javadoc hover

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/IntroduceIndirectionRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/IntroduceIndirection/test18_07/in/C.java
- org.eclipse.jdt.ui.tests.refactoring/resources/IntroduceIndirection/test18_07/in/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/resources/IntroduceIndirection/test18_07/out/C.java
- org.eclipse.jdt.ui.tests.refactoring/resources/IntroduceIndirection/test18_07/out/Foo.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/IntroduceIndirectionTests1d8.java
- fix IntroduceIndirectionRefactoring.checkFinalConditions() to handle the case where the declaring class is generic
- add new test to IntroduceIndirectionTests1d8
- fixes #2240
See issue.
> Fix indirection refactoring when extending a generic class

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaCodeScanner.java
Removed Token-level styling for contextual keywords: record, sealed, permits, non-sealed. Semantic highlighting for these keywords was already provided with
`org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightings.RestrictedIdentifiersHighlighting`.
Fixed state screenshot:
1. Create method named `record`
2. See coloring issue described in initial issue #1953 disappeared
3. Create any record or sealed class
4. See keyword highlighting is still there
Fixes #1953
> Remove explicit styling of keywords added in recent Java versions from JavaCodeScanner

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
If the preferences say that "Inner Types" should be folded by default then anonymous classes should be folded.
- Open the preferences
- Go to `Java > Editor > Folding` and check `Inner Types` and `Extended folding >  activate feature`
When opening a new file, anonymous classes should be folded.
You can try with this snippet:
```java
class MyClass {
public static void main(String arg[]) {
// Should be folded by default
AutoCloseable ac = new AutoCloseable() {
@Override
public void close() throws Exception {
// TODO Auto-generated method stub
}
};
}
}
```
> Initially fold anonymous classes with new folding

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/SaveParticipantTest.java
- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpPostSaveListener.java
- fix CleanUpPostSaveListener.saved() method to recognize the new cleanup requirement that separate options are required and not to add them to the conglomerate of options for all cleanups
- as well if the first cleanup requires separate option, then use those options only as such cleanups will also require fresh asts and must be at the end of the cleanup list so will be performed one at a time
- add new test to SaveParticipantTest
- fixes #2288
See issue.
> Fix save actions that include remove unused suppress warnings

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTestUtils.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
In #1825, I contributed custom folding regions but this does not allow using the same marker/prefix for the start and end marker comments.
Looking at classes like [`AddDelegateMethodsAction`](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/e25880c065ecc1534a94da98dd10f7c957b73719/org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/actions/AddDelegateMethodsAction.java), I can see comments splitting the code into different regions where one region ending and another one starting is indicated with the same comment.
Assuming that there are also other projects that would like to use that, I am changing custom folding regions to allow using the same text for start and end markers. The same comment is allowed to be both the end and start of a region.
If the region marker texts aren't mutually exclusive …
> allow overlapping start and end markers for custom folding regions

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
In #2282, I implemented folding of custom regions if the start and end region markers are the same.
This stops processing when the last comment is reached. In that case, I forgot to ensure that all remaining open folding regions need to be created appropriately.
For example, consider the following reproducer:
- Enable extended folding (if disabled)
- Enable custom folding regions
- Set both the start and end region marker comments to `-----` in `Window > Preferences > Java > Editor > Folding`
- Create the following class:
```
package org.example.test;
public class Repro {
// ----- getters/setters -----
public String test(boolean b) {
if (b)
return "a";
return "b";
}
}
```
The region for the `// ----- getters/setters -----` comment is missing.
Use the reproducer above (or similar) and see …
> fix custom folding regions end ignored end of comments are reached

- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_in/A_test203a.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_in/A_test203b.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_in/A_test203c.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_out/A_test203a.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_out/A_test203b.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/destination18_out/A_test203c.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/staticMethods18_in/A_test108.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/staticMethods18_in/A_test109.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/staticMethods18_out/A_test108.java
- org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/staticMethods18_out/A_test109.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests1d8.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/RefactoringMessages.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/code/ExtractMethodInputPage.java
- org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
- modify ExtractMethodRefactoring to add support for final and synchronized specification
- modify ExtractMethodInputPage to add final and synchronized to access modifiers and make it a group
- add new tests to ExtractMethodTests1d8
- fixes #2330
See issue.
See new tests.
> Allow specifying final and synchronized for extract method refactorin

- org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/AbstractMethodCorrectionProposalCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AdvancedQuickAssistTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
- See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1293 . :ghost: This appears to be the exact same issue. I was attempting to refactor some of this code, when I discovered this issue.
- `AbstractMethodCorrectionProposal` (jdt.ui) calls protected methods from `AbstractMethodCorrectionProposalCore` (jdt.core.manipulation), in the same package namespace (split package) and this is not caught as a compilation error
- 'Override' annotation should not be created where already present
- Make the library calls public and add a testcase, though the `IllegalAccessError` does not occur at all in the test run (with the methods set to `protected`)
To reproduce the issue :
**Base.java**
```
package org.example;
public class Base {
public void foo() {
}
}
```
**Common.java**
```
package …
```
> Fix IllegalAccessError for AbstractMethodCorrectionProposalCore.

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreMarkdownAccessImpl.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
- fix CoreMarkdownAccessImpl.removeDocLineIntros to replace all unicode line break characters to regular line break characters before performing the normal logic
- add new test to MarkdownCommentTests
- fixes #1787
See issue.
See new test.
> Fix CoreMarkdownAccessImpl to convert unicode characters

- org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/ImportsFix.java
Show a progress indicator when performing the save action _Organize Imports_
If organizing the imports takes long enough, this dialog will appear
- Activate the save action "Organize imports"
- Add an unnecessary import to a class
- Save the class
Add this busy wait in the method `org.eclipse.jdt.core.manipulation.OrganizeImportsOperation.createTextEdit(IProgressMonitor)`
```java
public TextEdit createTextEdit(IProgressMonitor m) throws CoreException, OperationCanceledException {
SubMonitor subMonitor= SubMonitor.convert(m, Messages.format(JavaManipulationMessages.OrganizeImportsOperation_description, BasicElementLabels.getFileName(fCompilationUnit)), 9);
fNumberOfImportsAdded= 0;
fNumberOfImportsRemoved= 0;
CompilationUnit astRoot= fASTRoot;
if (astRoot == null) {
astRoot= …
```
> Show progress when organizing imports during save

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2356_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2356_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2356_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2356_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- fix CallInliner.replaceCall() to fix the last statement of the last block when replacing a method reference so that it is written as a return statement
- fixes #2356
See issue.
> Fix inline method for replacing method reference

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2314_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2314_2.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2314_1.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2314_2.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- modify CallInliner.replaceCall() logic to handle the case where the method being inlined has a return value but it has been referenced in a lambda method reference where the functional interface method is void
- in this case modify the return statement expression to be an assignment to an unused variable
- fixes #2314
See issue.
> Fix inline of method reference when functional interface is void method

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/util/DelegateEntryComparator.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateDelegateMethodsTest16.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/SourceActionTests.java
- avoid an NPE when sorting delegates as record component accessors are not part of the model by adding checks in DelegateEntryComparator
- add new GenerateDelegateMethodsTest16
- add new test to SourceActionTests
- fixes #2362
See issue.
> Fix add delegate methods for records

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaReconciler.java
- This avoids the display the transient error annotations that are the result of PDE's deferring classpath initialization to a background job.
See https://github.com/eclipse-pde/eclipse.pde/pull/1888 for related details.
---
I acknowledge that there may well exist better solutions and I am willing to help review such alternative solutions in the future. 
My hope is that we can make this low-risk comprise change for m2 so that I can fully test tomorrows SDK build in real-life scenarios tomorrow, before the final m2 build, where I currently always see error annotation in open editors on startup; ones that do not go away, although I do believe that the "do not go away problem" has been solved.  So the remaining problem (transient annotation  that this PR addresses is definitely far less …
> Wait for deferred PDE classpath initializer before initial reconcile

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/SingleUsedFieldCleanUp.java
> Fix SingleUsedFieldCleanUp to remove volatile modifier if field moved

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/CodeScopeBuilder.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2376.java
- org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2376.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
- add new getParent() method to CodeScopeBuilder.Scope
- modify SourceProvider.makeNamesUnique() method to look in parent scopes in addition to current scope for collisions and to only store new names created in the scope if we are not targetting a method reference which will add braces automatically
- in the case where makeNamesUnique() doesn't find the names, store them anyway so the next inlining of the method in the same scope will do the rename
- fixes #2376
See issue.
> Fix multiple inline causing local variable name collisions

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/AutomatedSuite.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/editor/ClassFileInputTests.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditorInputFactory.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/HandleEditorInput.java
Currently the ClassFileEditorInputFactory performs some action to relocate ordinary class files into proper types of the project.
This has some problems:
- recovery should ideally be very fast because this code is called very early even before the UI is visible
- as it is not supported to return `null` error handling is not reliable possible any error will be swallowed and results in a generic error message that is hard to understand by the user and hard to track down because there is no stacktrace to the original code
This now do the following:
- create a new carrier input `HandleEditorInput` that is just a wrapper around a string and except for the case the memento itself is invalid we can always return a non-null value
- the existing `ClassFileEditor#transformEditorInput` method is …
> Move the relocation code from the factory to the ClassFileEditor

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaReconciler.java
This reverts commit 1f01b4197f57f636144e5a5059b9af06f14d79e5.
The code in PDE that used ClasspathContainerInitializer.class family is gone, so this code is meaningless now and only increases code complexity.
See https://github.com/eclipse-pde/eclipse.pde/pull/1898
> Revert "Wait for deferred PDE classpath initializer before initial reconcile"

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileDocumentProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClassFileEditor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/InternalClassFileEditorInput.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java
This is just a draft to show the code.
> Restore the type from class file input in the background

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/CoreASTProvider.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClipboardOperationAction.java
If the copy operation requires an AST, then the AST will be calculated by using forking to a non-UI thread and using a `ProgressMonitorDialog`. This gives the user a chance to cancel the operation while also showing the current progress.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2028
Sadly I don't know of any clean way to recreate the UI freeze described in #2028 , but one could emulate the behavior with a small hack (see below).
Once the lengthy operation is reproducible (or emulated via the hack), do this:
- Create these 2 classes in 2 different files
```java
import java.io.InputStream;
import java.util.ArrayList;
class A {
private void a() {
ArrayList<InputStream> l; // Copy this line
}
}
```
```java
import java.io.BufferedReader;
import java.util.List;
class B { …
```
> Show progress when calculating AST during copy (Ctrl + c) operation #2028

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/ReduceIndentationCleanUp.java
See commit message.
Run CleanUpTest and verify there are no lines printed to console.
> Remove extraneous println in ReduceIndentationCleanUp

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CallSearchResultCollector.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyMessages.properties
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/FiltersDialog.java
- fix CallSearchResultCollector.isIgnored() method to not return false just because show all code is selected
- also fix same method to not immediately return when user has selected tests only or hide tests and the test is false
- fix dialog message to denote that it is a qualified type name filter and not just a name filter (e.g. can't specify a method name)
- fixes #2396
See issue and comment.
See issue.
> Fix type filtering in CallHierarchy view

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
- org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/testFail17/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/testFail18/in/A.java
- org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
- modify PushDownRefactoringProcessor.getReferencingElements() method to also check for fields that are referenced via an instance of the declaring class
- add new tests to PushDownTests
- fixes #2417
See issue.
> Fix push down refactoring to check fields referenced via source class

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/AbstractCompletionTest.java
Use the JDT testplugin one.
JFace.text.tests one is to be removed.
> Stop using jface.text.tests DisplayHelper

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/MarkdownCommentTests.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AbstractAnnotateAssistTests.java
This change prevents working copy leaks in MarkdownCommentTests. Such leaks can call fails in subsequent tests.
Fixes: #2423
> Ensure test file working copies are discarded in JDT UI tests

- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionTest.java
- org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTestUtils.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Currently, the "enhanced folding" does not add information like the Java element the folding regions are associated with to them. Because of this, it is possible that Eclipse confuses/swaps two folding regions when editing the file which resets their expanded/collapsed state (because it considers them moved or doesn't find the folding regions any more).
The information of which element a folding region is associated to is used [in `update()` to correlate "old" folding regions with "new" folding regions](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java#L1317).
With #2302 (that's how I noticed it), the issue solved by this PR causes can also cause parts outside of the visible region to …
> preserve contextual information with enhanced folding

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
The Interfaces field in the New Class dialog was clipped when moving dialog between monitors with different scaling factors (100–300% DPI). This was caused by GridData.heightHint being set to convertHeightInCharsToPixels(3), which can resolve too small after a DPI switch and result in the text field and its adjacent button being cut off.
This change increases the height hint from 3 to 4 character rows when fTypeKind == CLASS_TYPE, ensuring the control renders correctly across all tested DPI scales.
- Run the runtime workspace with following arguments
```
-Dswt.autoScale=quarter
-Dswt.autoScale.updateOnRuntime=true
```
- Primary monitor at 100% zoom, secondary monitor at 200% zoom (scaling)
- Start Eclipse from the file explorer on the 200% monitor.
- Open the "New >>Class" dialog.
- Move …
> New Class dialog: fix cropped Interfaces field on mixed-DPI monitors

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsBaseSubProcessor.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest14.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
- use new SwitchExpressionMissingEnumConstantCaseDespiteDefault problem id to determine if we have a switch expression with a default but missing enum constants in which case abide with the severity setting of missing enum constant rather than treat it as a syntax error
- modify LocalCorrections processor and QuickFixProcessor accordingly
- fixes #2434
See issue.
See issue.
> Fix handling of enum switch expression when warn despite default enabled

- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest17.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=576380
> Bug 576380 - Quick fix not offered when a type that has a permits clause should have a sealed modifier

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- fix VariableDeclarationFixCore.fieldCanBeFinal() method to add call to IVariableBinding.getVariableDeclaration() in lambda visitor because reference to the field in lambda will be ParameterizedFieldBinding and will not be equal to original generic field binding
- fixes #2492
See issue.
> Fix add final for fields cleanup for generic class and lambda

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
- fix logic in ControlStatementsFix.AddBlockOperation.rewriteAST() to recognize that we have an else clause and that the start position will be on a previous line to the else comment
- fixes #2494
See issue.
- [x ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
> Fix control blocks clean-up to preserve else comments properly

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/dom/ASTNodes.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- modify ASTNodes.isMethodMatching() to recognize when looking at a varargs method that tests much be made against the component type of the last argument once the last argument index is reached and we aren't looking at an override of the original method
- add new test to CleanUpTest1d5
- fixes #2513
See issue.
> Fix unnecessary array cleanup to check for ambiguous varargs methods

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/CompletionProposalComputerDescriptor.java
Avoid logging a `RuntimeException` that wraps an `InterruptedException`. These are thrown way down in the `Parser` if the user cancels (clicks outside of) the completion proposal popup.
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/3157
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4302
Once this PR and the requires PRs are merged, it can be tested as specified in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4302
> Don't log InterruptedExceptions in CompletionProposalComputerDescriptor

- org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnwrapNewArrayOperation.java
- org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d5.java
- modify UnwrapNewArrayOperation.rewriteAST() to not only check the array items, but also all arguments for the top-level node
- fixes #2515
See issue.
> Fix UnwrapNewArrayOperation to keep NLS comments for all arguments

- org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
Illegal ASTNode positions should not throw java.lang.Exception
Fix: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2457
```
/// <table>
///   <tr>
///     <th>[top][#topProp}</th>
///   </tr>
/// </table>
public class Table {}
```
Hovering over the Table class will throw an exception
> Illegal ASTNode positions should not throw

- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ProblemSeveritiesConfigurationBlock.java
This patch fixes the following problem:
1. Open Preferences -> Java -> Compiler -> Errors/Warnings 
2. "Enable annotation-based null analysis"
3. Click on the 'Use default annotations for null specifications (*Configure*)
4. Try to modify the annotation names
5. Click on Ok
6. Dialog stays, a following exception is logged:
`
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IJavaProject.findType(String)" because the return value of "org.eclipse.jdt.core.JavaCore.create(org.eclipse.core.resources.IProject)" is null
at org.eclipse.jdt.internal.ui.preferences.ProblemSeveritiesConfigurationBlock$NullAnnotationsConfigurationDialog.getAnnotationKind(ProblemSeveritiesConfigurationBlock.java:634)
at org.eclipse.jdt.internal.ui.preferences.ProblemSeveritiesConfigurationBlock$NullA …
> Do not throw exception for saving the non-project wide nullness setting
